// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileTransferRequest_Direction int32

const (
	FileTransferRequest_UPLOAD   FileTransferRequest_Direction = 0
	FileTransferRequest_DOWNLOAD FileTransferRequest_Direction = 1
)

// Enum value maps for FileTransferRequest_Direction.
var (
	FileTransferRequest_Direction_name = map[int32]string{
		0: "UPLOAD",
		1: "DOWNLOAD",
	}
	FileTransferRequest_Direction_value = map[string]int32{
		"UPLOAD":   0,
		"DOWNLOAD": 1,
	}
)

func (x FileTransferRequest_Direction) Enum() *FileTransferRequest_Direction {
	p := new(FileTransferRequest_Direction)
	*p = x
	return p
}

func (x FileTransferRequest_Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileTransferRequest_Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (FileTransferRequest_Direction) Type() protoreflect.EnumType {
	return &file_agent_v1_agent_proto_enumTypes[0]
}

func (x FileTransferRequest_Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileTransferRequest_Direction.Descriptor instead.
func (FileTransferRequest_Direction) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{10, 0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Csr           []byte                 `protobuf:"bytes,4,opt,name=csr,proto3" json:"csr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *RegisterRequest) GetCsr() []byte {
	if x != nil {
		return x.Csr
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Certificate   []byte                 `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`
	CaCertificate []byte                 `protobuf:"bytes,3,opt,name=ca_certificate,json=caCertificate,proto3" json:"ca_certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *RegisterResponse) GetCaCertificate() []byte {
	if x != nil {
		return x.CaCertificate
	}
	return nil
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_ExecOutput
	//	*AgentMessage_HealthReport
	//	*AgentMessage_FileChunk
	//	*AgentMessage_ResourceReport
	//	*AgentMessage_ProvisionOutput
	//	*AgentMessage_SshKeyResult
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetExecOutput() *ExecOutput {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ExecOutput); ok {
			return x.ExecOutput
		}
	}
	return nil
}

func (x *AgentMessage) GetHealthReport() *HealthReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_HealthReport); ok {
			return x.HealthReport
		}
	}
	return nil
}

func (x *AgentMessage) GetFileChunk() *FileChunk {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_FileChunk); ok {
			return x.FileChunk
		}
	}
	return nil
}

func (x *AgentMessage) GetResourceReport() *ResourceReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ResourceReport); ok {
			return x.ResourceReport
		}
	}
	return nil
}

func (x *AgentMessage) GetProvisionOutput() *ProvisionOutput {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ProvisionOutput); ok {
			return x.ProvisionOutput
		}
	}
	return nil
}

func (x *AgentMessage) GetSshKeyResult() *SSHKeyInstallResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_SshKeyResult); ok {
			return x.SshKeyResult
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_ExecOutput struct {
	ExecOutput *ExecOutput `protobuf:"bytes,2,opt,name=exec_output,json=execOutput,proto3,oneof"`
}

type AgentMessage_HealthReport struct {
	HealthReport *HealthReport `protobuf:"bytes,3,opt,name=health_report,json=healthReport,proto3,oneof"`
}

type AgentMessage_FileChunk struct {
	FileChunk *FileChunk `protobuf:"bytes,4,opt,name=file_chunk,json=fileChunk,proto3,oneof"`
}

type AgentMessage_ResourceReport struct {
	ResourceReport *ResourceReport `protobuf:"bytes,5,opt,name=resource_report,json=resourceReport,proto3,oneof"`
}

type AgentMessage_ProvisionOutput struct {
	ProvisionOutput *ProvisionOutput `protobuf:"bytes,6,opt,name=provision_output,json=provisionOutput,proto3,oneof"`
}

type AgentMessage_SshKeyResult struct {
	SshKeyResult *SSHKeyInstallResult `protobuf:"bytes,7,opt,name=ssh_key_result,json=sshKeyResult,proto3,oneof"`
}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_ExecOutput) isAgentMessage_Payload() {}

func (*AgentMessage_HealthReport) isAgentMessage_Payload() {}

func (*AgentMessage_FileChunk) isAgentMessage_Payload() {}

func (*AgentMessage_ResourceReport) isAgentMessage_Payload() {}

func (*AgentMessage_ProvisionOutput) isAgentMessage_Payload() {}

func (*AgentMessage_SshKeyResult) isAgentMessage_Payload() {}

type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlMessage_ExecCommand
	//	*ControlMessage_FileTransfer
	//	*ControlMessage_CertRotation
	//	*ControlMessage_ProvisionCommand
	//	*ControlMessage_SshKeyInstall
	Payload       isControlMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ControlMessage) GetPayload() isControlMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlMessage) GetExecCommand() *ExecCommand {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_ExecCommand); ok {
			return x.ExecCommand
		}
	}
	return nil
}

func (x *ControlMessage) GetFileTransfer() *FileTransferRequest {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_FileTransfer); ok {
			return x.FileTransfer
		}
	}
	return nil
}

func (x *ControlMessage) GetCertRotation() *CertRotation {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_CertRotation); ok {
			return x.CertRotation
		}
	}
	return nil
}

func (x *ControlMessage) GetProvisionCommand() *ProvisionCommand {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_ProvisionCommand); ok {
			return x.ProvisionCommand
		}
	}
	return nil
}

func (x *ControlMessage) GetSshKeyInstall() *SSHKeyInstallCommand {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_SshKeyInstall); ok {
			return x.SshKeyInstall
		}
	}
	return nil
}

type isControlMessage_Payload interface {
	isControlMessage_Payload()
}

type ControlMessage_ExecCommand struct {
	ExecCommand *ExecCommand `protobuf:"bytes,1,opt,name=exec_command,json=execCommand,proto3,oneof"`
}

type ControlMessage_FileTransfer struct {
	FileTransfer *FileTransferRequest `protobuf:"bytes,2,opt,name=file_transfer,json=fileTransfer,proto3,oneof"`
}

type ControlMessage_CertRotation struct {
	CertRotation *CertRotation `protobuf:"bytes,3,opt,name=cert_rotation,json=certRotation,proto3,oneof"`
}

type ControlMessage_ProvisionCommand struct {
	ProvisionCommand *ProvisionCommand `protobuf:"bytes,4,opt,name=provision_command,json=provisionCommand,proto3,oneof"`
}

type ControlMessage_SshKeyInstall struct {
	SshKeyInstall *SSHKeyInstallCommand `protobuf:"bytes,5,opt,name=ssh_key_install,json=sshKeyInstall,proto3,oneof"`
}

func (*ControlMessage_ExecCommand) isControlMessage_Payload() {}

func (*ControlMessage_FileTransfer) isControlMessage_Payload() {}

func (*ControlMessage_CertRotation) isControlMessage_Payload() {}

func (*ControlMessage_ProvisionCommand) isControlMessage_Payload() {}

func (*ControlMessage_SshKeyInstall) isControlMessage_Payload() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Heartbeat) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ExecCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkingDir    string                 `protobuf:"bytes,5,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecCommand) Reset() {
	*x = ExecCommand{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecCommand) ProtoMessage() {}

func (x *ExecCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecCommand.ProtoReflect.Descriptor instead.
func (*ExecCommand) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ExecCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ExecCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecCommand) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecCommand) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecCommand) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

type ExecOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Stdout        []byte                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Finished      bool                   `protobuf:"varint,4,opt,name=finished,proto3" json:"finished,omitempty"`
	ExitCode      int32                  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecOutput) Reset() {
	*x = ExecOutput{}
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecOutput) ProtoMessage() {}

func (x *ExecOutput) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecOutput.ProtoReflect.Descriptor instead.
func (*ExecOutput) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ExecOutput) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ExecOutput) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ExecOutput) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *ExecOutput) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *ExecOutput) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type HealthReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryTotal   uint64                 `protobuf:"varint,3,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	MemoryUsed    uint64                 `protobuf:"varint,4,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	Disks         []*DiskInfo            `protobuf:"bytes,5,rep,name=disks,proto3" json:"disks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReport) Reset() {
	*x = HealthReport{}
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReport) ProtoMessage() {}

func (x *HealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReport.ProtoReflect.Descriptor instead.
func (*HealthReport) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *HealthReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HealthReport) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *HealthReport) GetMemoryTotal() uint64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *HealthReport) GetMemoryUsed() uint64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *HealthReport) GetDisks() []*DiskInfo {
	if x != nil {
		return x.Disks
	}
	return nil
}

type DiskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPoint    string                 `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	UsedBytes     uint64                 `protobuf:"varint,3,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskInfo) Reset() {
	*x = DiskInfo{}
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskInfo) ProtoMessage() {}

func (x *DiskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskInfo.ProtoReflect.Descriptor instead.
func (*DiskInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *DiskInfo) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *DiskInfo) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *DiskInfo) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Last          bool                   `protobuf:"varint,4,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *FileChunk) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileChunk) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

type FileTransferRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	TransferId    string                        `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Path          string                        `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Direction     FileTransferRequest_Direction `protobuf:"varint,3,opt,name=direction,proto3,enum=agent.v1.FileTransferRequest_Direction" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTransferRequest) Reset() {
	*x = FileTransferRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransferRequest) ProtoMessage() {}

func (x *FileTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransferRequest.ProtoReflect.Descriptor instead.
func (*FileTransferRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *FileTransferRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *FileTransferRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileTransferRequest) GetDirection() FileTransferRequest_Direction {
	if x != nil {
		return x.Direction
	}
	return FileTransferRequest_UPLOAD
}

type CertRotation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NewCertificate []byte                 `protobuf:"bytes,1,opt,name=new_certificate,json=newCertificate,proto3" json:"new_certificate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CertRotation) Reset() {
	*x = CertRotation{}
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertRotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertRotation) ProtoMessage() {}

func (x *CertRotation) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertRotation.ProtoReflect.Descriptor instead.
func (*CertRotation) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *CertRotation) GetNewCertificate() []byte {
	if x != nil {
		return x.NewCertificate
	}
	return nil
}

type NetworkInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ips           []string               `protobuf:"bytes,2,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterface) Reset() {
	*x = NetworkInterface{}
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterface) ProtoMessage() {}

func (x *NetworkInterface) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterface.ProtoReflect.Descriptor instead.
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *NetworkInterface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInterface) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

type ResourceReport struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AgentId           string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CpuModel          string                 `protobuf:"bytes,2,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	CpuCores          int32                  `protobuf:"varint,3,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryTotal       uint64                 `protobuf:"varint,4,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	MemoryAvailable   uint64                 `protobuf:"varint,5,opt,name=memory_available,json=memoryAvailable,proto3" json:"memory_available,omitempty"`
	KernelVersion     string                 `protobuf:"bytes,6,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	DockerVersion     string                 `protobuf:"bytes,7,opt,name=docker_version,json=dockerVersion,proto3" json:"docker_version,omitempty"`
	Disks             []*DiskInfo            `protobuf:"bytes,8,rep,name=disks,proto3" json:"disks,omitempty"`
	NetworkInterfaces []*NetworkInterface    `protobuf:"bytes,9,rep,name=network_interfaces,json=networkInterfaces,proto3" json:"network_interfaces,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResourceReport) Reset() {
	*x = ResourceReport{}
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceReport) ProtoMessage() {}

func (x *ResourceReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceReport.ProtoReflect.Descriptor instead.
func (*ResourceReport) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ResourceReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ResourceReport) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *ResourceReport) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *ResourceReport) GetMemoryTotal() uint64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *ResourceReport) GetMemoryAvailable() uint64 {
	if x != nil {
		return x.MemoryAvailable
	}
	return 0
}

func (x *ResourceReport) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *ResourceReport) GetDockerVersion() string {
	if x != nil {
		return x.DockerVersion
	}
	return ""
}

func (x *ResourceReport) GetDisks() []*DiskInfo {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *ResourceReport) GetNetworkInterfaces() []*NetworkInterface {
	if x != nil {
		return x.NetworkInterfaces
	}
	return nil
}

type ProvisionCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Component     string                 `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`
	Script        []byte                 `protobuf:"bytes,3,opt,name=script,proto3" json:"script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionCommand) Reset() {
	*x = ProvisionCommand{}
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionCommand) ProtoMessage() {}

func (x *ProvisionCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionCommand.ProtoReflect.Descriptor instead.
func (*ProvisionCommand) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ProvisionCommand) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ProvisionCommand) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *ProvisionCommand) GetScript() []byte {
	if x != nil {
		return x.Script
	}
	return nil
}

type ProvisionOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Component     string                 `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`
	Output        []byte                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Finished      bool                   `protobuf:"varint,4,opt,name=finished,proto3" json:"finished,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionOutput) Reset() {
	*x = ProvisionOutput{}
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionOutput) ProtoMessage() {}

func (x *ProvisionOutput) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionOutput.ProtoReflect.Descriptor instead.
func (*ProvisionOutput) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ProvisionOutput) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ProvisionOutput) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *ProvisionOutput) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ProvisionOutput) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *ProvisionOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProvisionOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SSHKeyInstallCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHKeyInstallCommand) Reset() {
	*x = SSHKeyInstallCommand{}
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHKeyInstallCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHKeyInstallCommand) ProtoMessage() {}

func (x *SSHKeyInstallCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHKeyInstallCommand.ProtoReflect.Descriptor instead.
func (*SSHKeyInstallCommand) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *SSHKeyInstallCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SSHKeyInstallCommand) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type SSHKeyInstallResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHKeyInstallResult) Reset() {
	*x = SSHKeyInstallResult{}
	mi := &file_agent_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHKeyInstallResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHKeyInstallResult) ProtoMessage() {}

func (x *SSHKeyInstallResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHKeyInstallResult.ProtoReflect.Descriptor instead.
func (*SSHKeyInstallResult) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *SSHKeyInstallResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SSHKeyInstallResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\bagent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"c\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x10\n" +
	"\x03csr\x18\x04 \x01(\fR\x03csr\"v\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12 \n" +
	"\vcertificate\x18\x02 \x01(\fR\vcertificate\x12%\n" +
	"\x0eca_certificate\x18\x03 \x01(\fR\rcaCertificate\"\xd0\x03\n" +
	"\fAgentMessage\x123\n" +
	"\theartbeat\x18\x01 \x01(\v2\x13.agent.v1.HeartbeatH\x00R\theartbeat\x127\n" +
	"\vexec_output\x18\x02 \x01(\v2\x14.agent.v1.ExecOutputH\x00R\n" +
	"execOutput\x12=\n" +
	"\rhealth_report\x18\x03 \x01(\v2\x16.agent.v1.HealthReportH\x00R\fhealthReport\x124\n" +
	"\n" +
	"file_chunk\x18\x04 \x01(\v2\x13.agent.v1.FileChunkH\x00R\tfileChunk\x12C\n" +
	"\x0fresource_report\x18\x05 \x01(\v2\x18.agent.v1.ResourceReportH\x00R\x0eresourceReport\x12F\n" +
	"\x10provision_output\x18\x06 \x01(\v2\x19.agent.v1.ProvisionOutputH\x00R\x0fprovisionOutput\x12E\n" +
	"\x0essh_key_result\x18\a \x01(\v2\x1d.agent.v1.SSHKeyInstallResultH\x00R\fsshKeyResultB\t\n" +
	"\apayload\"\xf1\x02\n" +
	"\x0eControlMessage\x12:\n" +
	"\fexec_command\x18\x01 \x01(\v2\x15.agent.v1.ExecCommandH\x00R\vexecCommand\x12D\n" +
	"\rfile_transfer\x18\x02 \x01(\v2\x1d.agent.v1.FileTransferRequestH\x00R\ffileTransfer\x12=\n" +
	"\rcert_rotation\x18\x03 \x01(\v2\x16.agent.v1.CertRotationH\x00R\fcertRotation\x12I\n" +
	"\x11provision_command\x18\x04 \x01(\v2\x1a.agent.v1.ProvisionCommandH\x00R\x10provisionCommand\x12H\n" +
	"\x0fssh_key_install\x18\x05 \x01(\v2\x1e.agent.v1.SSHKeyInstallCommandH\x00R\rsshKeyInstallB\t\n" +
	"\apayload\"`\n" +
	"\tHeartbeat\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xe5\x01\n" +
	"\vExecCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x120\n" +
	"\x03env\x18\x04 \x03(\v2\x1e.agent.v1.ExecCommand.EnvEntryR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\x05 \x01(\tR\n" +
	"workingDir\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x94\x01\n" +
	"\n" +
	"ExecOutput\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\fR\x06stderr\x12\x1a\n" +
	"\bfinished\x18\x04 \x01(\bR\bfinished\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\"\xb8\x01\n" +
	"\fHealthReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_total\x18\x03 \x01(\x04R\vmemoryTotal\x12\x1f\n" +
	"\vmemory_used\x18\x04 \x01(\x04R\n" +
	"memoryUsed\x12(\n" +
	"\x05disks\x18\x05 \x03(\v2\x12.agent.v1.DiskInfoR\x05disks\"k\n" +
	"\bDiskInfo\x12\x1f\n" +
	"\vmount_point\x18\x01 \x01(\tR\n" +
	"mountPoint\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x03 \x01(\x04R\tusedBytes\"l\n" +
	"\tFileChunk\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04last\x18\x04 \x01(\bR\x04last\"\xb8\x01\n" +
	"\x13FileTransferRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12E\n" +
	"\tdirection\x18\x03 \x01(\x0e2'.agent.v1.FileTransferRequest.DirectionR\tdirection\"%\n" +
	"\tDirection\x12\n" +
	"\n" +
	"\x06UPLOAD\x10\x00\x12\f\n" +
	"\bDOWNLOAD\x10\x01\"7\n" +
	"\fCertRotation\x12'\n" +
	"\x0fnew_certificate\x18\x01 \x01(\fR\x0enewCertificate\"8\n" +
	"\x10NetworkInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03ips\x18\x02 \x03(\tR\x03ips\"\xf6\x02\n" +
	"\x0eResourceReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tcpu_model\x18\x02 \x01(\tR\bcpuModel\x12\x1b\n" +
	"\tcpu_cores\x18\x03 \x01(\x05R\bcpuCores\x12!\n" +
	"\fmemory_total\x18\x04 \x01(\x04R\vmemoryTotal\x12)\n" +
	"\x10memory_available\x18\x05 \x01(\x04R\x0fmemoryAvailable\x12%\n" +
	"\x0ekernel_version\x18\x06 \x01(\tR\rkernelVersion\x12%\n" +
	"\x0edocker_version\x18\a \x01(\tR\rdockerVersion\x12(\n" +
	"\x05disks\x18\b \x03(\v2\x12.agent.v1.DiskInfoR\x05disks\x12I\n" +
	"\x12network_interfaces\x18\t \x03(\v2\x1a.agent.v1.NetworkInterfaceR\x11networkInterfaces\"_\n" +
	"\x10ProvisionCommand\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1c\n" +
	"\tcomponent\x18\x02 \x01(\tR\tcomponent\x12\x16\n" +
	"\x06script\x18\x03 \x01(\fR\x06script\"\xaa\x01\n" +
	"\x0fProvisionOutput\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1c\n" +
	"\tcomponent\x18\x02 \x01(\tR\tcomponent\x12\x16\n" +
	"\x06output\x18\x03 \x01(\fR\x06output\x12\x1a\n" +
	"\bfinished\x18\x04 \x01(\bR\bfinished\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"M\n" +
	"\x14SSHKeyInstallCommand\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\"E\n" +
	"\x13SSHKeyInstallResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x92\x01\n" +
	"\fAgentService\x12?\n" +
	"\aConnect\x12\x16.agent.v1.AgentMessage\x1a\x18.agent.v1.ControlMessage(\x010\x01\x12A\n" +
	"\bRegister\x12\x19.agent.v1.RegisterRequest\x1a\x1a.agent.v1.RegisterResponseBIZGgithub.com/othmanhaba/nixway-core/internal/agent/proto/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_agent_v1_agent_proto_goTypes = []any{
	(FileTransferRequest_Direction)(0), // 0: agent.v1.FileTransferRequest.Direction
	(*RegisterRequest)(nil),            // 1: agent.v1.RegisterRequest
	(*RegisterResponse)(nil),           // 2: agent.v1.RegisterResponse
	(*AgentMessage)(nil),               // 3: agent.v1.AgentMessage
	(*ControlMessage)(nil),             // 4: agent.v1.ControlMessage
	(*Heartbeat)(nil),                  // 5: agent.v1.Heartbeat
	(*ExecCommand)(nil),                // 6: agent.v1.ExecCommand
	(*ExecOutput)(nil),                 // 7: agent.v1.ExecOutput
	(*HealthReport)(nil),               // 8: agent.v1.HealthReport
	(*DiskInfo)(nil),                   // 9: agent.v1.DiskInfo
	(*FileChunk)(nil),                  // 10: agent.v1.FileChunk
	(*FileTransferRequest)(nil),        // 11: agent.v1.FileTransferRequest
	(*CertRotation)(nil),               // 12: agent.v1.CertRotation
	(*NetworkInterface)(nil),           // 13: agent.v1.NetworkInterface
	(*ResourceReport)(nil),             // 14: agent.v1.ResourceReport
	(*ProvisionCommand)(nil),           // 15: agent.v1.ProvisionCommand
	(*ProvisionOutput)(nil),            // 16: agent.v1.ProvisionOutput
	(*SSHKeyInstallCommand)(nil),       // 17: agent.v1.SSHKeyInstallCommand
	(*SSHKeyInstallResult)(nil),        // 18: agent.v1.SSHKeyInstallResult
	nil,                                // 19: agent.v1.ExecCommand.EnvEntry
	(*timestamppb.Timestamp)(nil),      // 20: google.protobuf.Timestamp
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	5,  // 0: agent.v1.AgentMessage.heartbeat:type_name -> agent.v1.Heartbeat
	7,  // 1: agent.v1.AgentMessage.exec_output:type_name -> agent.v1.ExecOutput
	8,  // 2: agent.v1.AgentMessage.health_report:type_name -> agent.v1.HealthReport
	10, // 3: agent.v1.AgentMessage.file_chunk:type_name -> agent.v1.FileChunk
	14, // 4: agent.v1.AgentMessage.resource_report:type_name -> agent.v1.ResourceReport
	16, // 5: agent.v1.AgentMessage.provision_output:type_name -> agent.v1.ProvisionOutput
	18, // 6: agent.v1.AgentMessage.ssh_key_result:type_name -> agent.v1.SSHKeyInstallResult
	6,  // 7: agent.v1.ControlMessage.exec_command:type_name -> agent.v1.ExecCommand
	11, // 8: agent.v1.ControlMessage.file_transfer:type_name -> agent.v1.FileTransferRequest
	12, // 9: agent.v1.ControlMessage.cert_rotation:type_name -> agent.v1.CertRotation
	15, // 10: agent.v1.ControlMessage.provision_command:type_name -> agent.v1.ProvisionCommand
	17, // 11: agent.v1.ControlMessage.ssh_key_install:type_name -> agent.v1.SSHKeyInstallCommand
	20, // 12: agent.v1.Heartbeat.timestamp:type_name -> google.protobuf.Timestamp
	19, // 13: agent.v1.ExecCommand.env:type_name -> agent.v1.ExecCommand.EnvEntry
	9,  // 14: agent.v1.HealthReport.disks:type_name -> agent.v1.DiskInfo
	0,  // 15: agent.v1.FileTransferRequest.direction:type_name -> agent.v1.FileTransferRequest.Direction
	9,  // 16: agent.v1.ResourceReport.disks:type_name -> agent.v1.DiskInfo
	13, // 17: agent.v1.ResourceReport.network_interfaces:type_name -> agent.v1.NetworkInterface
	3,  // 18: agent.v1.AgentService.Connect:input_type -> agent.v1.AgentMessage
	1,  // 19: agent.v1.AgentService.Register:input_type -> agent.v1.RegisterRequest
	4,  // 20: agent.v1.AgentService.Connect:output_type -> agent.v1.ControlMessage
	2,  // 21: agent.v1.AgentService.Register:output_type -> agent.v1.RegisterResponse
	20, // [20:22] is the sub-list for method output_type
	18, // [18:20] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	file_agent_v1_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_ExecOutput)(nil),
		(*AgentMessage_HealthReport)(nil),
		(*AgentMessage_FileChunk)(nil),
		(*AgentMessage_ResourceReport)(nil),
		(*AgentMessage_ProvisionOutput)(nil),
		(*AgentMessage_SshKeyResult)(nil),
	}
	file_agent_v1_agent_proto_msgTypes[3].OneofWrappers = []any{
		(*ControlMessage_ExecCommand)(nil),
		(*ControlMessage_FileTransfer)(nil),
		(*ControlMessage_CertRotation)(nil),
		(*ControlMessage_ProvisionCommand)(nil),
		(*ControlMessage_SshKeyInstall)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
