/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GithubCallbackRouteImport } from './routes/github/callback'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppTeamsIndexRouteImport } from './routes/_app/teams/index'
import { Route as AuthVerifyEmailTokenRouteImport } from './routes/_auth/verify-email.$token'
import { Route as AuthResetPasswordTokenRouteImport } from './routes/_auth/reset-password.$token'
import { Route as AppTeamsTeamIdRouteImport } from './routes/_app/teams/$teamId'
import { Route as AppSshKeysTeamIdRouteImport } from './routes/_app/ssh-keys.$teamId'
import { Route as AppSettingsTeamIdRouteImport } from './routes/_app/settings.$teamId'
import { Route as AppServersTeamIdRouteImport } from './routes/_app/servers.$teamId'
import { Route as AppProjectsTeamIdRouteImport } from './routes/_app/projects.$teamId'
import { Route as AppClustersTeamIdRouteImport } from './routes/_app/clusters.$teamId'
import { Route as AppAppsAppIdRouteImport } from './routes/_app/apps_.$appId'
import { Route as AppTeamsTeamIdTokensRouteImport } from './routes/_app/teams/$teamId/tokens'
import { Route as AppTeamsTeamIdSettingsRouteImport } from './routes/_app/teams/$teamId/settings'
import { Route as AppTeamsTeamIdAuditLogRouteImport } from './routes/_app/teams/$teamId/audit-log'
import { Route as AppServersTeamIdServerIdRouteImport } from './routes/_app/servers_.$teamId.$serverId'
import { Route as AppProjectsTeamIdProjectIdRouteImport } from './routes/_app/projects_.$teamId.$projectId'
import { Route as AppClustersTeamIdClusterIdRouteImport } from './routes/_app/clusters_.$teamId.$clusterId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubCallbackRoute = GithubCallbackRouteImport.update({
  id: '/github/callback',
  path: '/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsIndexRoute = AppTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AppRoute,
} as any)
const AuthVerifyEmailTokenRoute = AuthVerifyEmailTokenRouteImport.update({
  id: '/verify-email/$token',
  path: '/verify-email/$token',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordTokenRoute = AuthResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => AuthRoute,
} as any)
const AppTeamsTeamIdRoute = AppTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => AppRoute,
} as any)
const AppSshKeysTeamIdRoute = AppSshKeysTeamIdRouteImport.update({
  id: '/ssh-keys/$teamId',
  path: '/ssh-keys/$teamId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTeamIdRoute = AppSettingsTeamIdRouteImport.update({
  id: '/settings/$teamId',
  path: '/settings/$teamId',
  getParentRoute: () => AppRoute,
} as any)
const AppServersTeamIdRoute = AppServersTeamIdRouteImport.update({
  id: '/servers/$teamId',
  path: '/servers/$teamId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsTeamIdRoute = AppProjectsTeamIdRouteImport.update({
  id: '/projects/$teamId',
  path: '/projects/$teamId',
  getParentRoute: () => AppRoute,
} as any)
const AppClustersTeamIdRoute = AppClustersTeamIdRouteImport.update({
  id: '/clusters/$teamId',
  path: '/clusters/$teamId',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsAppIdRoute = AppAppsAppIdRouteImport.update({
  id: '/apps_/$appId',
  path: '/apps/$appId',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsTeamIdTokensRoute = AppTeamsTeamIdTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AppTeamsTeamIdRoute,
} as any)
const AppTeamsTeamIdSettingsRoute = AppTeamsTeamIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppTeamsTeamIdRoute,
} as any)
const AppTeamsTeamIdAuditLogRoute = AppTeamsTeamIdAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AppTeamsTeamIdRoute,
} as any)
const AppServersTeamIdServerIdRoute =
  AppServersTeamIdServerIdRouteImport.update({
    id: '/servers_/$teamId/$serverId',
    path: '/servers/$teamId/$serverId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsTeamIdProjectIdRoute =
  AppProjectsTeamIdProjectIdRouteImport.update({
    id: '/projects_/$teamId/$projectId',
    path: '/projects/$teamId/$projectId',
    getParentRoute: () => AppRoute,
  } as any)
const AppClustersTeamIdClusterIdRoute =
  AppClustersTeamIdClusterIdRouteImport.update({
    id: '/clusters_/$teamId/$clusterId',
    path: '/clusters/$teamId/$clusterId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/github/callback': typeof GithubCallbackRoute
  '/apps/$appId': typeof AppAppsAppIdRoute
  '/clusters/$teamId': typeof AppClustersTeamIdRoute
  '/projects/$teamId': typeof AppProjectsTeamIdRoute
  '/servers/$teamId': typeof AppServersTeamIdRoute
  '/settings/$teamId': typeof AppSettingsTeamIdRoute
  '/ssh-keys/$teamId': typeof AppSshKeysTeamIdRoute
  '/teams/$teamId': typeof AppTeamsTeamIdRouteWithChildren
  '/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/verify-email/$token': typeof AuthVerifyEmailTokenRoute
  '/teams/': typeof AppTeamsIndexRoute
  '/clusters/$teamId/$clusterId': typeof AppClustersTeamIdClusterIdRoute
  '/projects/$teamId/$projectId': typeof AppProjectsTeamIdProjectIdRoute
  '/servers/$teamId/$serverId': typeof AppServersTeamIdServerIdRoute
  '/teams/$teamId/audit-log': typeof AppTeamsTeamIdAuditLogRoute
  '/teams/$teamId/settings': typeof AppTeamsTeamIdSettingsRoute
  '/teams/$teamId/tokens': typeof AppTeamsTeamIdTokensRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/github/callback': typeof GithubCallbackRoute
  '/apps/$appId': typeof AppAppsAppIdRoute
  '/clusters/$teamId': typeof AppClustersTeamIdRoute
  '/projects/$teamId': typeof AppProjectsTeamIdRoute
  '/servers/$teamId': typeof AppServersTeamIdRoute
  '/settings/$teamId': typeof AppSettingsTeamIdRoute
  '/ssh-keys/$teamId': typeof AppSshKeysTeamIdRoute
  '/teams/$teamId': typeof AppTeamsTeamIdRouteWithChildren
  '/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/verify-email/$token': typeof AuthVerifyEmailTokenRoute
  '/teams': typeof AppTeamsIndexRoute
  '/clusters/$teamId/$clusterId': typeof AppClustersTeamIdClusterIdRoute
  '/projects/$teamId/$projectId': typeof AppProjectsTeamIdProjectIdRoute
  '/servers/$teamId/$serverId': typeof AppServersTeamIdServerIdRoute
  '/teams/$teamId/audit-log': typeof AppTeamsTeamIdAuditLogRoute
  '/teams/$teamId/settings': typeof AppTeamsTeamIdSettingsRoute
  '/teams/$teamId/tokens': typeof AppTeamsTeamIdTokensRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/github/callback': typeof GithubCallbackRoute
  '/_app/apps_/$appId': typeof AppAppsAppIdRoute
  '/_app/clusters/$teamId': typeof AppClustersTeamIdRoute
  '/_app/projects/$teamId': typeof AppProjectsTeamIdRoute
  '/_app/servers/$teamId': typeof AppServersTeamIdRoute
  '/_app/settings/$teamId': typeof AppSettingsTeamIdRoute
  '/_app/ssh-keys/$teamId': typeof AppSshKeysTeamIdRoute
  '/_app/teams/$teamId': typeof AppTeamsTeamIdRouteWithChildren
  '/_auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/_auth/verify-email/$token': typeof AuthVerifyEmailTokenRoute
  '/_app/teams/': typeof AppTeamsIndexRoute
  '/_app/clusters_/$teamId/$clusterId': typeof AppClustersTeamIdClusterIdRoute
  '/_app/projects_/$teamId/$projectId': typeof AppProjectsTeamIdProjectIdRoute
  '/_app/servers_/$teamId/$serverId': typeof AppServersTeamIdServerIdRoute
  '/_app/teams/$teamId/audit-log': typeof AppTeamsTeamIdAuditLogRoute
  '/_app/teams/$teamId/settings': typeof AppTeamsTeamIdSettingsRoute
  '/_app/teams/$teamId/tokens': typeof AppTeamsTeamIdTokensRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/github/callback'
    | '/apps/$appId'
    | '/clusters/$teamId'
    | '/projects/$teamId'
    | '/servers/$teamId'
    | '/settings/$teamId'
    | '/ssh-keys/$teamId'
    | '/teams/$teamId'
    | '/reset-password/$token'
    | '/verify-email/$token'
    | '/teams/'
    | '/clusters/$teamId/$clusterId'
    | '/projects/$teamId/$projectId'
    | '/servers/$teamId/$serverId'
    | '/teams/$teamId/audit-log'
    | '/teams/$teamId/settings'
    | '/teams/$teamId/tokens'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/github/callback'
    | '/apps/$appId'
    | '/clusters/$teamId'
    | '/projects/$teamId'
    | '/servers/$teamId'
    | '/settings/$teamId'
    | '/ssh-keys/$teamId'
    | '/teams/$teamId'
    | '/reset-password/$token'
    | '/verify-email/$token'
    | '/teams'
    | '/clusters/$teamId/$clusterId'
    | '/projects/$teamId/$projectId'
    | '/servers/$teamId/$serverId'
    | '/teams/$teamId/audit-log'
    | '/teams/$teamId/settings'
    | '/teams/$teamId/tokens'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/dashboard'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/signup'
    | '/github/callback'
    | '/_app/apps_/$appId'
    | '/_app/clusters/$teamId'
    | '/_app/projects/$teamId'
    | '/_app/servers/$teamId'
    | '/_app/settings/$teamId'
    | '/_app/ssh-keys/$teamId'
    | '/_app/teams/$teamId'
    | '/_auth/reset-password/$token'
    | '/_auth/verify-email/$token'
    | '/_app/teams/'
    | '/_app/clusters_/$teamId/$clusterId'
    | '/_app/projects_/$teamId/$projectId'
    | '/_app/servers_/$teamId/$serverId'
    | '/_app/teams/$teamId/audit-log'
    | '/_app/teams/$teamId/settings'
    | '/_app/teams/$teamId/tokens'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  GithubCallbackRoute: typeof GithubCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github/callback': {
      id: '/github/callback'
      path: '/github/callback'
      fullPath: '/github/callback'
      preLoaderRoute: typeof GithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/': {
      id: '/_app/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof AppTeamsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/verify-email/$token': {
      id: '/_auth/verify-email/$token'
      path: '/verify-email/$token'
      fullPath: '/verify-email/$token'
      preLoaderRoute: typeof AuthVerifyEmailTokenRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password/$token': {
      id: '/_auth/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof AuthResetPasswordTokenRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/teams/$teamId': {
      id: '/_app/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AppTeamsTeamIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ssh-keys/$teamId': {
      id: '/_app/ssh-keys/$teamId'
      path: '/ssh-keys/$teamId'
      fullPath: '/ssh-keys/$teamId'
      preLoaderRoute: typeof AppSshKeysTeamIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/$teamId': {
      id: '/_app/settings/$teamId'
      path: '/settings/$teamId'
      fullPath: '/settings/$teamId'
      preLoaderRoute: typeof AppSettingsTeamIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servers/$teamId': {
      id: '/_app/servers/$teamId'
      path: '/servers/$teamId'
      fullPath: '/servers/$teamId'
      preLoaderRoute: typeof AppServersTeamIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$teamId': {
      id: '/_app/projects/$teamId'
      path: '/projects/$teamId'
      fullPath: '/projects/$teamId'
      preLoaderRoute: typeof AppProjectsTeamIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clusters/$teamId': {
      id: '/_app/clusters/$teamId'
      path: '/clusters/$teamId'
      fullPath: '/clusters/$teamId'
      preLoaderRoute: typeof AppClustersTeamIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps_/$appId': {
      id: '/_app/apps_/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AppAppsAppIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/$teamId/tokens': {
      id: '/_app/teams/$teamId/tokens'
      path: '/tokens'
      fullPath: '/teams/$teamId/tokens'
      preLoaderRoute: typeof AppTeamsTeamIdTokensRouteImport
      parentRoute: typeof AppTeamsTeamIdRoute
    }
    '/_app/teams/$teamId/settings': {
      id: '/_app/teams/$teamId/settings'
      path: '/settings'
      fullPath: '/teams/$teamId/settings'
      preLoaderRoute: typeof AppTeamsTeamIdSettingsRouteImport
      parentRoute: typeof AppTeamsTeamIdRoute
    }
    '/_app/teams/$teamId/audit-log': {
      id: '/_app/teams/$teamId/audit-log'
      path: '/audit-log'
      fullPath: '/teams/$teamId/audit-log'
      preLoaderRoute: typeof AppTeamsTeamIdAuditLogRouteImport
      parentRoute: typeof AppTeamsTeamIdRoute
    }
    '/_app/servers_/$teamId/$serverId': {
      id: '/_app/servers_/$teamId/$serverId'
      path: '/servers/$teamId/$serverId'
      fullPath: '/servers/$teamId/$serverId'
      preLoaderRoute: typeof AppServersTeamIdServerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects_/$teamId/$projectId': {
      id: '/_app/projects_/$teamId/$projectId'
      path: '/projects/$teamId/$projectId'
      fullPath: '/projects/$teamId/$projectId'
      preLoaderRoute: typeof AppProjectsTeamIdProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clusters_/$teamId/$clusterId': {
      id: '/_app/clusters_/$teamId/$clusterId'
      path: '/clusters/$teamId/$clusterId'
      fullPath: '/clusters/$teamId/$clusterId'
      preLoaderRoute: typeof AppClustersTeamIdClusterIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppTeamsTeamIdRouteChildren {
  AppTeamsTeamIdAuditLogRoute: typeof AppTeamsTeamIdAuditLogRoute
  AppTeamsTeamIdSettingsRoute: typeof AppTeamsTeamIdSettingsRoute
  AppTeamsTeamIdTokensRoute: typeof AppTeamsTeamIdTokensRoute
}

const AppTeamsTeamIdRouteChildren: AppTeamsTeamIdRouteChildren = {
  AppTeamsTeamIdAuditLogRoute: AppTeamsTeamIdAuditLogRoute,
  AppTeamsTeamIdSettingsRoute: AppTeamsTeamIdSettingsRoute,
  AppTeamsTeamIdTokensRoute: AppTeamsTeamIdTokensRoute,
}

const AppTeamsTeamIdRouteWithChildren = AppTeamsTeamIdRoute._addFileChildren(
  AppTeamsTeamIdRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppAppsAppIdRoute: typeof AppAppsAppIdRoute
  AppClustersTeamIdRoute: typeof AppClustersTeamIdRoute
  AppProjectsTeamIdRoute: typeof AppProjectsTeamIdRoute
  AppServersTeamIdRoute: typeof AppServersTeamIdRoute
  AppSettingsTeamIdRoute: typeof AppSettingsTeamIdRoute
  AppSshKeysTeamIdRoute: typeof AppSshKeysTeamIdRoute
  AppTeamsTeamIdRoute: typeof AppTeamsTeamIdRouteWithChildren
  AppTeamsIndexRoute: typeof AppTeamsIndexRoute
  AppClustersTeamIdClusterIdRoute: typeof AppClustersTeamIdClusterIdRoute
  AppProjectsTeamIdProjectIdRoute: typeof AppProjectsTeamIdProjectIdRoute
  AppServersTeamIdServerIdRoute: typeof AppServersTeamIdServerIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppAppsAppIdRoute: AppAppsAppIdRoute,
  AppClustersTeamIdRoute: AppClustersTeamIdRoute,
  AppProjectsTeamIdRoute: AppProjectsTeamIdRoute,
  AppServersTeamIdRoute: AppServersTeamIdRoute,
  AppSettingsTeamIdRoute: AppSettingsTeamIdRoute,
  AppSshKeysTeamIdRoute: AppSshKeysTeamIdRoute,
  AppTeamsTeamIdRoute: AppTeamsTeamIdRouteWithChildren,
  AppTeamsIndexRoute: AppTeamsIndexRoute,
  AppClustersTeamIdClusterIdRoute: AppClustersTeamIdClusterIdRoute,
  AppProjectsTeamIdProjectIdRoute: AppProjectsTeamIdProjectIdRoute,
  AppServersTeamIdServerIdRoute: AppServersTeamIdServerIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthResetPasswordTokenRoute: typeof AuthResetPasswordTokenRoute
  AuthVerifyEmailTokenRoute: typeof AuthVerifyEmailTokenRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthResetPasswordTokenRoute: AuthResetPasswordTokenRoute,
  AuthVerifyEmailTokenRoute: AuthVerifyEmailTokenRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  GithubCallbackRoute: GithubCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
