// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_env_vars.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAppEnvVar = `-- name: DeleteAppEnvVar :exec
DELETE FROM app_env_vars WHERE id = $1 AND app_id = $2
`

type DeleteAppEnvVarParams struct {
	ID    uuid.UUID `json:"id"`
	AppID uuid.UUID `json:"app_id"`
}

func (q *Queries) DeleteAppEnvVar(ctx context.Context, arg DeleteAppEnvVarParams) error {
	_, err := q.db.Exec(ctx, deleteAppEnvVar, arg.ID, arg.AppID)
	return err
}

const getAppEnvVarByID = `-- name: GetAppEnvVarByID :one
SELECT id, app_id, environment_id, key, encrypted_value, created_by, updated_by, created_at, updated_at FROM app_env_vars WHERE id = $1 AND app_id = $2
`

type GetAppEnvVarByIDParams struct {
	ID    uuid.UUID `json:"id"`
	AppID uuid.UUID `json:"app_id"`
}

func (q *Queries) GetAppEnvVarByID(ctx context.Context, arg GetAppEnvVarByIDParams) (AppEnvVar, error) {
	row := q.db.QueryRow(ctx, getAppEnvVarByID, arg.ID, arg.AppID)
	var i AppEnvVar
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.EnvironmentID,
		&i.Key,
		&i.EncryptedValue,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppEnvVars = `-- name: ListAppEnvVars :many
SELECT id, app_id, environment_id, key, created_by, updated_by, created_at, updated_at
FROM app_env_vars
WHERE app_id = $1 AND environment_id = $2
ORDER BY key
`

type ListAppEnvVarsParams struct {
	AppID         uuid.UUID `json:"app_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

type ListAppEnvVarsRow struct {
	ID            uuid.UUID   `json:"id"`
	AppID         uuid.UUID   `json:"app_id"`
	EnvironmentID uuid.UUID   `json:"environment_id"`
	Key           string      `json:"key"`
	CreatedBy     pgtype.UUID `json:"created_by"`
	UpdatedBy     pgtype.UUID `json:"updated_by"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

func (q *Queries) ListAppEnvVars(ctx context.Context, arg ListAppEnvVarsParams) ([]ListAppEnvVarsRow, error) {
	rows, err := q.db.Query(ctx, listAppEnvVars, arg.AppID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppEnvVarsRow{}
	for rows.Next() {
		var i ListAppEnvVarsRow
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.EnvironmentID,
			&i.Key,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppEnvVarsWithValues = `-- name: ListAppEnvVarsWithValues :many
SELECT id, app_id, environment_id, key, encrypted_value, created_by, updated_by, created_at, updated_at FROM app_env_vars
WHERE app_id = $1 AND environment_id = $2
ORDER BY key
`

type ListAppEnvVarsWithValuesParams struct {
	AppID         uuid.UUID `json:"app_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) ListAppEnvVarsWithValues(ctx context.Context, arg ListAppEnvVarsWithValuesParams) ([]AppEnvVar, error) {
	rows, err := q.db.Query(ctx, listAppEnvVarsWithValues, arg.AppID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppEnvVar{}
	for rows.Next() {
		var i AppEnvVar
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.EnvironmentID,
			&i.Key,
			&i.EncryptedValue,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAppEnvVar = `-- name: UpsertAppEnvVar :one
INSERT INTO app_env_vars (app_id, environment_id, key, encrypted_value, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $5)
ON CONFLICT (app_id, environment_id, key) DO UPDATE SET
    encrypted_value = EXCLUDED.encrypted_value,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
RETURNING id, app_id, environment_id, key, encrypted_value, created_by, updated_by, created_at, updated_at
`

type UpsertAppEnvVarParams struct {
	AppID          uuid.UUID   `json:"app_id"`
	EnvironmentID  uuid.UUID   `json:"environment_id"`
	Key            string      `json:"key"`
	EncryptedValue []byte      `json:"encrypted_value"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) UpsertAppEnvVar(ctx context.Context, arg UpsertAppEnvVarParams) (AppEnvVar, error) {
	row := q.db.QueryRow(ctx, upsertAppEnvVar,
		arg.AppID,
		arg.EnvironmentID,
		arg.Key,
		arg.EncryptedValue,
		arg.CreatedBy,
	)
	var i AppEnvVar
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.EnvironmentID,
		&i.Key,
		&i.EncryptedValue,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
