// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apps.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createApp = `-- name: CreateApp :one
INSERT INTO apps (
    project_id, name, slug, source_type,
    github_installation_id, repo_full_name, branch, root_path, auto_deploy,
    docker_image, registry_credential_id,
    builder, dockerfile_path,
    port, health_check_path, health_check_interval, health_check_timeout, replicas,
    subdomain, placement_strategy, placement_constraints, pinned_server_ids
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22)
RETURNING id, project_id, name, slug, source_type, github_installation_id, repo_full_name, branch, root_path, auto_deploy, docker_image, registry_credential_id, builder, dockerfile_path, port, health_check_path, health_check_interval, health_check_timeout, replicas, subdomain, custom_domain, domain_verified, status, created_at, updated_at, domains, memory_limit_mb, cpu_limit_millicores, placement_strategy, placement_constraints, pinned_server_ids
`

type CreateAppParams struct {
	ProjectID            uuid.UUID   `json:"project_id"`
	Name                 string      `json:"name"`
	Slug                 string      `json:"slug"`
	SourceType           string      `json:"source_type"`
	GithubInstallationID pgtype.UUID `json:"github_installation_id"`
	RepoFullName         *string     `json:"repo_full_name"`
	Branch               *string     `json:"branch"`
	RootPath             string      `json:"root_path"`
	AutoDeploy           bool        `json:"auto_deploy"`
	DockerImage          *string     `json:"docker_image"`
	RegistryCredentialID pgtype.UUID `json:"registry_credential_id"`
	Builder              string      `json:"builder"`
	DockerfilePath       string      `json:"dockerfile_path"`
	Port                 int32       `json:"port"`
	HealthCheckPath      string      `json:"health_check_path"`
	HealthCheckInterval  int32       `json:"health_check_interval"`
	HealthCheckTimeout   int32       `json:"health_check_timeout"`
	Replicas             int32       `json:"replicas"`
	Subdomain            *string     `json:"subdomain"`
	PlacementStrategy    string      `json:"placement_strategy"`
	PlacementConstraints []byte      `json:"placement_constraints"`
	PinnedServerIds      []uuid.UUID `json:"pinned_server_ids"`
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.db.QueryRow(ctx, createApp,
		arg.ProjectID,
		arg.Name,
		arg.Slug,
		arg.SourceType,
		arg.GithubInstallationID,
		arg.RepoFullName,
		arg.Branch,
		arg.RootPath,
		arg.AutoDeploy,
		arg.DockerImage,
		arg.RegistryCredentialID,
		arg.Builder,
		arg.DockerfilePath,
		arg.Port,
		arg.HealthCheckPath,
		arg.HealthCheckInterval,
		arg.HealthCheckTimeout,
		arg.Replicas,
		arg.Subdomain,
		arg.PlacementStrategy,
		arg.PlacementConstraints,
		arg.PinnedServerIds,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.SourceType,
		&i.GithubInstallationID,
		&i.RepoFullName,
		&i.Branch,
		&i.RootPath,
		&i.AutoDeploy,
		&i.DockerImage,
		&i.RegistryCredentialID,
		&i.Builder,
		&i.DockerfilePath,
		&i.Port,
		&i.HealthCheckPath,
		&i.HealthCheckInterval,
		&i.HealthCheckTimeout,
		&i.Replicas,
		&i.Subdomain,
		&i.CustomDomain,
		&i.DomainVerified,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Domains,
		&i.MemoryLimitMb,
		&i.CpuLimitMillicores,
		&i.PlacementStrategy,
		&i.PlacementConstraints,
		&i.PinnedServerIds,
	)
	return i, err
}

const deleteApp = `-- name: DeleteApp :exec
DELETE FROM apps WHERE id = $1
`

func (q *Queries) DeleteApp(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteApp, id)
	return err
}

const getApp = `-- name: GetApp :one
SELECT id, project_id, name, slug, source_type, github_installation_id, repo_full_name, branch, root_path, auto_deploy, docker_image, registry_credential_id, builder, dockerfile_path, port, health_check_path, health_check_interval, health_check_timeout, replicas, subdomain, custom_domain, domain_verified, status, created_at, updated_at, domains, memory_limit_mb, cpu_limit_millicores, placement_strategy, placement_constraints, pinned_server_ids FROM apps WHERE id = $1
`

func (q *Queries) GetApp(ctx context.Context, id uuid.UUID) (App, error) {
	row := q.db.QueryRow(ctx, getApp, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.SourceType,
		&i.GithubInstallationID,
		&i.RepoFullName,
		&i.Branch,
		&i.RootPath,
		&i.AutoDeploy,
		&i.DockerImage,
		&i.RegistryCredentialID,
		&i.Builder,
		&i.DockerfilePath,
		&i.Port,
		&i.HealthCheckPath,
		&i.HealthCheckInterval,
		&i.HealthCheckTimeout,
		&i.Replicas,
		&i.Subdomain,
		&i.CustomDomain,
		&i.DomainVerified,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Domains,
		&i.MemoryLimitMb,
		&i.CpuLimitMillicores,
		&i.PlacementStrategy,
		&i.PlacementConstraints,
		&i.PinnedServerIds,
	)
	return i, err
}

const getAppDomains = `-- name: GetAppDomains :one
SELECT id, domains FROM apps WHERE id = $1
`

type GetAppDomainsRow struct {
	ID      uuid.UUID `json:"id"`
	Domains []string  `json:"domains"`
}

func (q *Queries) GetAppDomains(ctx context.Context, id uuid.UUID) (GetAppDomainsRow, error) {
	row := q.db.QueryRow(ctx, getAppDomains, id)
	var i GetAppDomainsRow
	err := row.Scan(&i.ID, &i.Domains)
	return i, err
}

const listAppsByProject = `-- name: ListAppsByProject :many
SELECT id, project_id, name, slug, source_type, github_installation_id, repo_full_name, branch, root_path, auto_deploy, docker_image, registry_credential_id, builder, dockerfile_path, port, health_check_path, health_check_interval, health_check_timeout, replicas, subdomain, custom_domain, domain_verified, status, created_at, updated_at, domains, memory_limit_mb, cpu_limit_millicores, placement_strategy, placement_constraints, pinned_server_ids FROM apps
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAppsByProject(ctx context.Context, projectID uuid.UUID) ([]App, error) {
	rows, err := q.db.Query(ctx, listAppsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Slug,
			&i.SourceType,
			&i.GithubInstallationID,
			&i.RepoFullName,
			&i.Branch,
			&i.RootPath,
			&i.AutoDeploy,
			&i.DockerImage,
			&i.RegistryCredentialID,
			&i.Builder,
			&i.DockerfilePath,
			&i.Port,
			&i.HealthCheckPath,
			&i.HealthCheckInterval,
			&i.HealthCheckTimeout,
			&i.Replicas,
			&i.Subdomain,
			&i.CustomDomain,
			&i.DomainVerified,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Domains,
			&i.MemoryLimitMb,
			&i.CpuLimitMillicores,
			&i.PlacementStrategy,
			&i.PlacementConstraints,
			&i.PinnedServerIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsByRepo = `-- name: ListAppsByRepo :many
SELECT a.id, a.project_id, a.name, a.slug, a.source_type, a.github_installation_id, a.repo_full_name, a.branch, a.root_path, a.auto_deploy, a.docker_image, a.registry_credential_id, a.builder, a.dockerfile_path, a.port, a.health_check_path, a.health_check_interval, a.health_check_timeout, a.replicas, a.subdomain, a.custom_domain, a.domain_verified, a.status, a.created_at, a.updated_at, a.domains, a.memory_limit_mb, a.cpu_limit_millicores, a.placement_strategy, a.placement_constraints, a.pinned_server_ids, p.team_id
FROM apps a
JOIN projects p ON p.id = a.project_id
WHERE a.repo_full_name = $1 AND a.auto_deploy = true
`

type ListAppsByRepoRow struct {
	ID                   uuid.UUID   `json:"id"`
	ProjectID            uuid.UUID   `json:"project_id"`
	Name                 string      `json:"name"`
	Slug                 string      `json:"slug"`
	SourceType           string      `json:"source_type"`
	GithubInstallationID pgtype.UUID `json:"github_installation_id"`
	RepoFullName         *string     `json:"repo_full_name"`
	Branch               *string     `json:"branch"`
	RootPath             string      `json:"root_path"`
	AutoDeploy           bool        `json:"auto_deploy"`
	DockerImage          *string     `json:"docker_image"`
	RegistryCredentialID pgtype.UUID `json:"registry_credential_id"`
	Builder              string      `json:"builder"`
	DockerfilePath       string      `json:"dockerfile_path"`
	Port                 int32       `json:"port"`
	HealthCheckPath      string      `json:"health_check_path"`
	HealthCheckInterval  int32       `json:"health_check_interval"`
	HealthCheckTimeout   int32       `json:"health_check_timeout"`
	Replicas             int32       `json:"replicas"`
	Subdomain            *string     `json:"subdomain"`
	CustomDomain         *string     `json:"custom_domain"`
	DomainVerified       bool        `json:"domain_verified"`
	Status               string      `json:"status"`
	CreatedAt            time.Time   `json:"created_at"`
	UpdatedAt            time.Time   `json:"updated_at"`
	Domains              []string    `json:"domains"`
	MemoryLimitMb        int32       `json:"memory_limit_mb"`
	CpuLimitMillicores   int32       `json:"cpu_limit_millicores"`
	PlacementStrategy    string      `json:"placement_strategy"`
	PlacementConstraints []byte      `json:"placement_constraints"`
	PinnedServerIds      []uuid.UUID `json:"pinned_server_ids"`
	TeamID               uuid.UUID   `json:"team_id"`
}

func (q *Queries) ListAppsByRepo(ctx context.Context, repoFullName *string) ([]ListAppsByRepoRow, error) {
	rows, err := q.db.Query(ctx, listAppsByRepo, repoFullName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppsByRepoRow{}
	for rows.Next() {
		var i ListAppsByRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Slug,
			&i.SourceType,
			&i.GithubInstallationID,
			&i.RepoFullName,
			&i.Branch,
			&i.RootPath,
			&i.AutoDeploy,
			&i.DockerImage,
			&i.RegistryCredentialID,
			&i.Builder,
			&i.DockerfilePath,
			&i.Port,
			&i.HealthCheckPath,
			&i.HealthCheckInterval,
			&i.HealthCheckTimeout,
			&i.Replicas,
			&i.Subdomain,
			&i.CustomDomain,
			&i.DomainVerified,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Domains,
			&i.MemoryLimitMb,
			&i.CpuLimitMillicores,
			&i.PlacementStrategy,
			&i.PlacementConstraints,
			&i.PinnedServerIds,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAppDomainVerified = `-- name: SetAppDomainVerified :exec
UPDATE apps SET domain_verified = $2, updated_at = now() WHERE id = $1
`

type SetAppDomainVerifiedParams struct {
	ID             uuid.UUID `json:"id"`
	DomainVerified bool      `json:"domain_verified"`
}

func (q *Queries) SetAppDomainVerified(ctx context.Context, arg SetAppDomainVerifiedParams) error {
	_, err := q.db.Exec(ctx, setAppDomainVerified, arg.ID, arg.DomainVerified)
	return err
}

const setAppDomains = `-- name: SetAppDomains :exec
UPDATE apps SET domains = $2, updated_at = now() WHERE id = $1
`

type SetAppDomainsParams struct {
	ID      uuid.UUID `json:"id"`
	Domains []string  `json:"domains"`
}

func (q *Queries) SetAppDomains(ctx context.Context, arg SetAppDomainsParams) error {
	_, err := q.db.Exec(ctx, setAppDomains, arg.ID, arg.Domains)
	return err
}

const updateApp = `-- name: UpdateApp :one
UPDATE apps
SET name = $2, branch = $3, root_path = $4, auto_deploy = $5,
    builder = $6, dockerfile_path = $7,
    port = $8, health_check_path = $9, health_check_interval = $10,
    health_check_timeout = $11, replicas = $12,
    subdomain = $13, custom_domain = $14,
    status = $15, placement_strategy = $16, placement_constraints = $17,
    pinned_server_ids = $18, updated_at = now()
WHERE id = $1
RETURNING id, project_id, name, slug, source_type, github_installation_id, repo_full_name, branch, root_path, auto_deploy, docker_image, registry_credential_id, builder, dockerfile_path, port, health_check_path, health_check_interval, health_check_timeout, replicas, subdomain, custom_domain, domain_verified, status, created_at, updated_at, domains, memory_limit_mb, cpu_limit_millicores, placement_strategy, placement_constraints, pinned_server_ids
`

type UpdateAppParams struct {
	ID                   uuid.UUID   `json:"id"`
	Name                 string      `json:"name"`
	Branch               *string     `json:"branch"`
	RootPath             string      `json:"root_path"`
	AutoDeploy           bool        `json:"auto_deploy"`
	Builder              string      `json:"builder"`
	DockerfilePath       string      `json:"dockerfile_path"`
	Port                 int32       `json:"port"`
	HealthCheckPath      string      `json:"health_check_path"`
	HealthCheckInterval  int32       `json:"health_check_interval"`
	HealthCheckTimeout   int32       `json:"health_check_timeout"`
	Replicas             int32       `json:"replicas"`
	Subdomain            *string     `json:"subdomain"`
	CustomDomain         *string     `json:"custom_domain"`
	Status               string      `json:"status"`
	PlacementStrategy    string      `json:"placement_strategy"`
	PlacementConstraints []byte      `json:"placement_constraints"`
	PinnedServerIds      []uuid.UUID `json:"pinned_server_ids"`
}

func (q *Queries) UpdateApp(ctx context.Context, arg UpdateAppParams) (App, error) {
	row := q.db.QueryRow(ctx, updateApp,
		arg.ID,
		arg.Name,
		arg.Branch,
		arg.RootPath,
		arg.AutoDeploy,
		arg.Builder,
		arg.DockerfilePath,
		arg.Port,
		arg.HealthCheckPath,
		arg.HealthCheckInterval,
		arg.HealthCheckTimeout,
		arg.Replicas,
		arg.Subdomain,
		arg.CustomDomain,
		arg.Status,
		arg.PlacementStrategy,
		arg.PlacementConstraints,
		arg.PinnedServerIds,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.SourceType,
		&i.GithubInstallationID,
		&i.RepoFullName,
		&i.Branch,
		&i.RootPath,
		&i.AutoDeploy,
		&i.DockerImage,
		&i.RegistryCredentialID,
		&i.Builder,
		&i.DockerfilePath,
		&i.Port,
		&i.HealthCheckPath,
		&i.HealthCheckInterval,
		&i.HealthCheckTimeout,
		&i.Replicas,
		&i.Subdomain,
		&i.CustomDomain,
		&i.DomainVerified,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Domains,
		&i.MemoryLimitMb,
		&i.CpuLimitMillicores,
		&i.PlacementStrategy,
		&i.PlacementConstraints,
		&i.PinnedServerIds,
	)
	return i, err
}

const updateAppResources = `-- name: UpdateAppResources :one
UPDATE apps
SET memory_limit_mb = $2, cpu_limit_millicores = $3, updated_at = now()
WHERE id = $1
RETURNING id, project_id, name, slug, source_type, github_installation_id, repo_full_name, branch, root_path, auto_deploy, docker_image, registry_credential_id, builder, dockerfile_path, port, health_check_path, health_check_interval, health_check_timeout, replicas, subdomain, custom_domain, domain_verified, status, created_at, updated_at, domains, memory_limit_mb, cpu_limit_millicores, placement_strategy, placement_constraints, pinned_server_ids
`

type UpdateAppResourcesParams struct {
	ID                 uuid.UUID `json:"id"`
	MemoryLimitMb      int32     `json:"memory_limit_mb"`
	CpuLimitMillicores int32     `json:"cpu_limit_millicores"`
}

func (q *Queries) UpdateAppResources(ctx context.Context, arg UpdateAppResourcesParams) (App, error) {
	row := q.db.QueryRow(ctx, updateAppResources, arg.ID, arg.MemoryLimitMb, arg.CpuLimitMillicores)
	var i App
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.SourceType,
		&i.GithubInstallationID,
		&i.RepoFullName,
		&i.Branch,
		&i.RootPath,
		&i.AutoDeploy,
		&i.DockerImage,
		&i.RegistryCredentialID,
		&i.Builder,
		&i.DockerfilePath,
		&i.Port,
		&i.HealthCheckPath,
		&i.HealthCheckInterval,
		&i.HealthCheckTimeout,
		&i.Replicas,
		&i.Subdomain,
		&i.CustomDomain,
		&i.DomainVerified,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Domains,
		&i.MemoryLimitMb,
		&i.CpuLimitMillicores,
		&i.PlacementStrategy,
		&i.PlacementConstraints,
		&i.PinnedServerIds,
	)
	return i, err
}

const updateAppScaling = `-- name: UpdateAppScaling :one
UPDATE apps
SET replicas = $2,
    placement_strategy = $3,
    placement_constraints = $4,
    pinned_server_ids = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, name, slug, source_type, github_installation_id, repo_full_name, branch, root_path, auto_deploy, docker_image, registry_credential_id, builder, dockerfile_path, port, health_check_path, health_check_interval, health_check_timeout, replicas, subdomain, custom_domain, domain_verified, status, created_at, updated_at, domains, memory_limit_mb, cpu_limit_millicores, placement_strategy, placement_constraints, pinned_server_ids
`

type UpdateAppScalingParams struct {
	ID                   uuid.UUID   `json:"id"`
	Replicas             int32       `json:"replicas"`
	PlacementStrategy    string      `json:"placement_strategy"`
	PlacementConstraints []byte      `json:"placement_constraints"`
	PinnedServerIds      []uuid.UUID `json:"pinned_server_ids"`
}

func (q *Queries) UpdateAppScaling(ctx context.Context, arg UpdateAppScalingParams) (App, error) {
	row := q.db.QueryRow(ctx, updateAppScaling,
		arg.ID,
		arg.Replicas,
		arg.PlacementStrategy,
		arg.PlacementConstraints,
		arg.PinnedServerIds,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.SourceType,
		&i.GithubInstallationID,
		&i.RepoFullName,
		&i.Branch,
		&i.RootPath,
		&i.AutoDeploy,
		&i.DockerImage,
		&i.RegistryCredentialID,
		&i.Builder,
		&i.DockerfilePath,
		&i.Port,
		&i.HealthCheckPath,
		&i.HealthCheckInterval,
		&i.HealthCheckTimeout,
		&i.Replicas,
		&i.Subdomain,
		&i.CustomDomain,
		&i.DomainVerified,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Domains,
		&i.MemoryLimitMb,
		&i.CpuLimitMillicores,
		&i.PlacementStrategy,
		&i.PlacementConstraints,
		&i.PinnedServerIds,
	)
	return i, err
}
