// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (team_id, actor_id, actor_type, action, resource_type, resource_id, metadata, ip_address)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, team_id, actor_id, actor_type, action, resource_type, resource_id, metadata, ip_address, created_at
`

type CreateAuditLogParams struct {
	TeamID       pgtype.UUID     `json:"team_id"`
	ActorID      pgtype.UUID     `json:"actor_id"`
	ActorType    string          `json:"actor_type"`
	Action       string          `json:"action"`
	ResourceType string          `json:"resource_type"`
	ResourceID   pgtype.UUID     `json:"resource_id"`
	Metadata     json.RawMessage `json:"metadata"`
	IpAddress    *netip.Addr     `json:"ip_address"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.TeamID,
		arg.ActorID,
		arg.ActorType,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Metadata,
		arg.IpAddress,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ActorID,
		&i.ActorType,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Metadata,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT al.id, al.team_id, al.actor_id, al.actor_type, al.action, al.resource_type, al.resource_id, al.metadata, al.ip_address, al.created_at, u.name AS actor_name, u.email AS actor_email
FROM audit_logs al
LEFT JOIN users u ON al.actor_id = u.id
WHERE al.team_id = $1
  AND ($2::UUID IS NULL OR al.actor_id = $2)
  AND ($3::TEXT IS NULL OR al.action = $3)
  AND ($4::TEXT IS NULL OR al.resource_type = $4)
  AND ($5::UUID IS NULL OR al.resource_id = $5)
  AND ($6::TIMESTAMPTZ IS NULL OR al.created_at < $6)
ORDER BY al.created_at DESC
LIMIT $7
`

type ListAuditLogsParams struct {
	TeamID       pgtype.UUID        `json:"team_id"`
	ActorID      pgtype.UUID        `json:"actor_id"`
	Action       *string            `json:"action"`
	ResourceType *string            `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	After        pgtype.Timestamptz `json:"after"`
	PageSize     int32              `json:"page_size"`
}

type ListAuditLogsRow struct {
	ID           uuid.UUID       `json:"id"`
	TeamID       pgtype.UUID     `json:"team_id"`
	ActorID      pgtype.UUID     `json:"actor_id"`
	ActorType    string          `json:"actor_type"`
	Action       string          `json:"action"`
	ResourceType string          `json:"resource_type"`
	ResourceID   pgtype.UUID     `json:"resource_id"`
	Metadata     json.RawMessage `json:"metadata"`
	IpAddress    *netip.Addr     `json:"ip_address"`
	CreatedAt    time.Time       `json:"created_at"`
	ActorName    *string         `json:"actor_name"`
	ActorEmail   *string         `json:"actor_email"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.TeamID,
		arg.ActorID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.After,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ActorID,
			&i.ActorType,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Metadata,
			&i.IpAddress,
			&i.CreatedAt,
			&i.ActorName,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
