// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: autoscaling.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAutoscalingRule = `-- name: CreateAutoscalingRule :one
INSERT INTO autoscaling_rules (
    app_id, name, metric_name, comparison, threshold, duration_seconds,
    action_type, action_value, min_replicas, max_replicas,
    cooldown_up_seconds, cooldown_down_seconds, enabled
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, app_id, name, metric_name, comparison, threshold, duration_seconds, action_type, action_value, min_replicas, max_replicas, cooldown_up_seconds, cooldown_down_seconds, enabled, last_triggered_at, created_at, updated_at
`

type CreateAutoscalingRuleParams struct {
	AppID               uuid.UUID `json:"app_id"`
	Name                string    `json:"name"`
	MetricName          string    `json:"metric_name"`
	Comparison          string    `json:"comparison"`
	Threshold           float64   `json:"threshold"`
	DurationSeconds     int32     `json:"duration_seconds"`
	ActionType          string    `json:"action_type"`
	ActionValue         int32     `json:"action_value"`
	MinReplicas         int32     `json:"min_replicas"`
	MaxReplicas         int32     `json:"max_replicas"`
	CooldownUpSeconds   int32     `json:"cooldown_up_seconds"`
	CooldownDownSeconds int32     `json:"cooldown_down_seconds"`
	Enabled             bool      `json:"enabled"`
}

func (q *Queries) CreateAutoscalingRule(ctx context.Context, arg CreateAutoscalingRuleParams) (AutoscalingRule, error) {
	row := q.db.QueryRow(ctx, createAutoscalingRule,
		arg.AppID,
		arg.Name,
		arg.MetricName,
		arg.Comparison,
		arg.Threshold,
		arg.DurationSeconds,
		arg.ActionType,
		arg.ActionValue,
		arg.MinReplicas,
		arg.MaxReplicas,
		arg.CooldownUpSeconds,
		arg.CooldownDownSeconds,
		arg.Enabled,
	)
	var i AutoscalingRule
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.MetricName,
		&i.Comparison,
		&i.Threshold,
		&i.DurationSeconds,
		&i.ActionType,
		&i.ActionValue,
		&i.MinReplicas,
		&i.MaxReplicas,
		&i.CooldownUpSeconds,
		&i.CooldownDownSeconds,
		&i.Enabled,
		&i.LastTriggeredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAutoscalingRule = `-- name: DeleteAutoscalingRule :exec
DELETE FROM autoscaling_rules WHERE id = $1 AND app_id = $2
`

type DeleteAutoscalingRuleParams struct {
	ID    uuid.UUID `json:"id"`
	AppID uuid.UUID `json:"app_id"`
}

func (q *Queries) DeleteAutoscalingRule(ctx context.Context, arg DeleteAutoscalingRuleParams) error {
	_, err := q.db.Exec(ctx, deleteAutoscalingRule, arg.ID, arg.AppID)
	return err
}

const getAutoscalingRule = `-- name: GetAutoscalingRule :one
SELECT id, app_id, name, metric_name, comparison, threshold, duration_seconds, action_type, action_value, min_replicas, max_replicas, cooldown_up_seconds, cooldown_down_seconds, enabled, last_triggered_at, created_at, updated_at FROM autoscaling_rules WHERE id = $1 AND app_id = $2
`

type GetAutoscalingRuleParams struct {
	ID    uuid.UUID `json:"id"`
	AppID uuid.UUID `json:"app_id"`
}

func (q *Queries) GetAutoscalingRule(ctx context.Context, arg GetAutoscalingRuleParams) (AutoscalingRule, error) {
	row := q.db.QueryRow(ctx, getAutoscalingRule, arg.ID, arg.AppID)
	var i AutoscalingRule
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.MetricName,
		&i.Comparison,
		&i.Threshold,
		&i.DurationSeconds,
		&i.ActionType,
		&i.ActionValue,
		&i.MinReplicas,
		&i.MaxReplicas,
		&i.CooldownUpSeconds,
		&i.CooldownDownSeconds,
		&i.Enabled,
		&i.LastTriggeredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppsWithEnabledAutoscaling = `-- name: ListAppsWithEnabledAutoscaling :many
SELECT DISTINCT app_id FROM autoscaling_rules
WHERE enabled = true
ORDER BY app_id
`

func (q *Queries) ListAppsWithEnabledAutoscaling(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAppsWithEnabledAutoscaling)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var app_id uuid.UUID
		if err := rows.Scan(&app_id); err != nil {
			return nil, err
		}
		items = append(items, app_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutoscalingRulesByApp = `-- name: ListAutoscalingRulesByApp :many
SELECT id, app_id, name, metric_name, comparison, threshold, duration_seconds, action_type, action_value, min_replicas, max_replicas, cooldown_up_seconds, cooldown_down_seconds, enabled, last_triggered_at, created_at, updated_at FROM autoscaling_rules
WHERE app_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAutoscalingRulesByApp(ctx context.Context, appID uuid.UUID) ([]AutoscalingRule, error) {
	rows, err := q.db.Query(ctx, listAutoscalingRulesByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutoscalingRule{}
	for rows.Next() {
		var i AutoscalingRule
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Name,
			&i.MetricName,
			&i.Comparison,
			&i.Threshold,
			&i.DurationSeconds,
			&i.ActionType,
			&i.ActionValue,
			&i.MinReplicas,
			&i.MaxReplicas,
			&i.CooldownUpSeconds,
			&i.CooldownDownSeconds,
			&i.Enabled,
			&i.LastTriggeredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAutoscalingRulesByApp = `-- name: ListEnabledAutoscalingRulesByApp :many
SELECT id, app_id, name, metric_name, comparison, threshold, duration_seconds, action_type, action_value, min_replicas, max_replicas, cooldown_up_seconds, cooldown_down_seconds, enabled, last_triggered_at, created_at, updated_at FROM autoscaling_rules
WHERE app_id = $1 AND enabled = true
ORDER BY created_at ASC
`

func (q *Queries) ListEnabledAutoscalingRulesByApp(ctx context.Context, appID uuid.UUID) ([]AutoscalingRule, error) {
	rows, err := q.db.Query(ctx, listEnabledAutoscalingRulesByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutoscalingRule{}
	for rows.Next() {
		var i AutoscalingRule
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Name,
			&i.MetricName,
			&i.Comparison,
			&i.Threshold,
			&i.DurationSeconds,
			&i.ActionType,
			&i.ActionValue,
			&i.MinReplicas,
			&i.MaxReplicas,
			&i.CooldownUpSeconds,
			&i.CooldownDownSeconds,
			&i.Enabled,
			&i.LastTriggeredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAutoscalingRuleTriggered = `-- name: MarkAutoscalingRuleTriggered :exec
UPDATE autoscaling_rules
SET last_triggered_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkAutoscalingRuleTriggered(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAutoscalingRuleTriggered, id)
	return err
}
