// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: builds.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendBuildLogs = `-- name: AppendBuildLogs :exec
UPDATE builds SET logs = logs || $2 WHERE id = $1
`

type AppendBuildLogsParams struct {
	ID   uuid.UUID `json:"id"`
	Logs string    `json:"logs"`
}

func (q *Queries) AppendBuildLogs(ctx context.Context, arg AppendBuildLogsParams) error {
	_, err := q.db.Exec(ctx, appendBuildLogs, arg.ID, arg.Logs)
	return err
}

const completeBuild = `-- name: CompleteBuild :exec
UPDATE builds
SET status = $2, image_tag = $3, server_id = $4, completed_at = now(), error = $5
WHERE id = $1
`

type CompleteBuildParams struct {
	ID       uuid.UUID   `json:"id"`
	Status   string      `json:"status"`
	ImageTag string      `json:"image_tag"`
	ServerID pgtype.UUID `json:"server_id"`
	Error    *string     `json:"error"`
}

func (q *Queries) CompleteBuild(ctx context.Context, arg CompleteBuildParams) error {
	_, err := q.db.Exec(ctx, completeBuild,
		arg.ID,
		arg.Status,
		arg.ImageTag,
		arg.ServerID,
		arg.Error,
	)
	return err
}

const createBuild = `-- name: CreateBuild :one
INSERT INTO builds (app_id, environment_id, trigger_type, commit_sha, commit_message, branch, builder)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, app_id, environment_id, trigger_type, commit_sha, commit_message, branch, builder, image_tag, server_id, status, logs, started_at, completed_at, error, created_at
`

type CreateBuildParams struct {
	AppID         uuid.UUID `json:"app_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	TriggerType   string    `json:"trigger_type"`
	CommitSha     string    `json:"commit_sha"`
	CommitMessage string    `json:"commit_message"`
	Branch        string    `json:"branch"`
	Builder       string    `json:"builder"`
}

func (q *Queries) CreateBuild(ctx context.Context, arg CreateBuildParams) (Build, error) {
	row := q.db.QueryRow(ctx, createBuild,
		arg.AppID,
		arg.EnvironmentID,
		arg.TriggerType,
		arg.CommitSha,
		arg.CommitMessage,
		arg.Branch,
		arg.Builder,
	)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.EnvironmentID,
		&i.TriggerType,
		&i.CommitSha,
		&i.CommitMessage,
		&i.Branch,
		&i.Builder,
		&i.ImageTag,
		&i.ServerID,
		&i.Status,
		&i.Logs,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getBuild = `-- name: GetBuild :one
SELECT id, app_id, environment_id, trigger_type, commit_sha, commit_message, branch, builder, image_tag, server_id, status, logs, started_at, completed_at, error, created_at FROM builds WHERE id = $1
`

func (q *Queries) GetBuild(ctx context.Context, id uuid.UUID) (Build, error) {
	row := q.db.QueryRow(ctx, getBuild, id)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.EnvironmentID,
		&i.TriggerType,
		&i.CommitSha,
		&i.CommitMessage,
		&i.Branch,
		&i.Builder,
		&i.ImageTag,
		&i.ServerID,
		&i.Status,
		&i.Logs,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestSuccessfulBuild = `-- name: GetLatestSuccessfulBuild :one
SELECT id, app_id, environment_id, trigger_type, commit_sha, commit_message, branch, builder, image_tag, server_id, status, logs, started_at, completed_at, error, created_at FROM builds
WHERE app_id = $1 AND environment_id = $2 AND status = 'built'
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestSuccessfulBuildParams struct {
	AppID         uuid.UUID `json:"app_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) GetLatestSuccessfulBuild(ctx context.Context, arg GetLatestSuccessfulBuildParams) (Build, error) {
	row := q.db.QueryRow(ctx, getLatestSuccessfulBuild, arg.AppID, arg.EnvironmentID)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.EnvironmentID,
		&i.TriggerType,
		&i.CommitSha,
		&i.CommitMessage,
		&i.Branch,
		&i.Builder,
		&i.ImageTag,
		&i.ServerID,
		&i.Status,
		&i.Logs,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const listBuildsByApp = `-- name: ListBuildsByApp :many
SELECT id, app_id, environment_id, trigger_type, commit_sha, commit_message, branch, builder, image_tag, server_id, status, logs, started_at, completed_at, error, created_at FROM builds
WHERE app_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBuildsByAppParams struct {
	AppID  uuid.UUID `json:"app_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListBuildsByApp(ctx context.Context, arg ListBuildsByAppParams) ([]Build, error) {
	rows, err := q.db.Query(ctx, listBuildsByApp, arg.AppID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Build{}
	for rows.Next() {
		var i Build
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.EnvironmentID,
			&i.TriggerType,
			&i.CommitSha,
			&i.CommitMessage,
			&i.Branch,
			&i.Builder,
			&i.ImageTag,
			&i.ServerID,
			&i.Status,
			&i.Logs,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBuildStatus = `-- name: UpdateBuildStatus :exec
UPDATE builds
SET status = $2, started_at = COALESCE(started_at, $3), error = $4
WHERE id = $1
`

type UpdateBuildStatusParams struct {
	ID        uuid.UUID          `json:"id"`
	Status    string             `json:"status"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	Error     *string            `json:"error"`
}

func (q *Queries) UpdateBuildStatus(ctx context.Context, arg UpdateBuildStatusParams) error {
	_, err := q.db.Exec(ctx, updateBuildStatus,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.Error,
	)
	return err
}
