// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cluster_members.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearServerClusterID = `-- name: ClearServerClusterID :exec
UPDATE servers SET cluster_id = NULL WHERE id = $1
`

func (q *Queries) ClearServerClusterID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearServerClusterID, id)
	return err
}

const createClusterMember = `-- name: CreateClusterMember :one
INSERT INTO cluster_members (cluster_id, server_id, wireguard_ip, wireguard_public_key, wireguard_endpoint, listen_port)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, cluster_id, server_id, wireguard_ip, wireguard_public_key, wireguard_endpoint, listen_port, joined_at
`

type CreateClusterMemberParams struct {
	ClusterID          uuid.UUID  `json:"cluster_id"`
	ServerID           uuid.UUID  `json:"server_id"`
	WireguardIp        netip.Addr `json:"wireguard_ip"`
	WireguardPublicKey string     `json:"wireguard_public_key"`
	WireguardEndpoint  string     `json:"wireguard_endpoint"`
	ListenPort         int32      `json:"listen_port"`
}

func (q *Queries) CreateClusterMember(ctx context.Context, arg CreateClusterMemberParams) (ClusterMember, error) {
	row := q.db.QueryRow(ctx, createClusterMember,
		arg.ClusterID,
		arg.ServerID,
		arg.WireguardIp,
		arg.WireguardPublicKey,
		arg.WireguardEndpoint,
		arg.ListenPort,
	)
	var i ClusterMember
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.ServerID,
		&i.WireguardIp,
		&i.WireguardPublicKey,
		&i.WireguardEndpoint,
		&i.ListenPort,
		&i.JoinedAt,
	)
	return i, err
}

const deleteClusterMember = `-- name: DeleteClusterMember :exec
DELETE FROM cluster_members WHERE cluster_id = $1 AND server_id = $2
`

type DeleteClusterMemberParams struct {
	ClusterID uuid.UUID `json:"cluster_id"`
	ServerID  uuid.UUID `json:"server_id"`
}

func (q *Queries) DeleteClusterMember(ctx context.Context, arg DeleteClusterMemberParams) error {
	_, err := q.db.Exec(ctx, deleteClusterMember, arg.ClusterID, arg.ServerID)
	return err
}

const deleteClusterMemberByID = `-- name: DeleteClusterMemberByID :exec
DELETE FROM cluster_members WHERE id = $1
`

func (q *Queries) DeleteClusterMemberByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteClusterMemberByID, id)
	return err
}

const getClusterMemberByClusterAndIP = `-- name: GetClusterMemberByClusterAndIP :one
SELECT id, cluster_id, server_id, wireguard_ip, wireguard_public_key, wireguard_endpoint, listen_port, joined_at FROM cluster_members WHERE cluster_id = $1 AND wireguard_ip = $2
`

type GetClusterMemberByClusterAndIPParams struct {
	ClusterID   uuid.UUID  `json:"cluster_id"`
	WireguardIp netip.Addr `json:"wireguard_ip"`
}

func (q *Queries) GetClusterMemberByClusterAndIP(ctx context.Context, arg GetClusterMemberByClusterAndIPParams) (ClusterMember, error) {
	row := q.db.QueryRow(ctx, getClusterMemberByClusterAndIP, arg.ClusterID, arg.WireguardIp)
	var i ClusterMember
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.ServerID,
		&i.WireguardIp,
		&i.WireguardPublicKey,
		&i.WireguardEndpoint,
		&i.ListenPort,
		&i.JoinedAt,
	)
	return i, err
}

const getClusterMemberByID = `-- name: GetClusterMemberByID :one
SELECT id, cluster_id, server_id, wireguard_ip, wireguard_public_key, wireguard_endpoint, listen_port, joined_at FROM cluster_members WHERE id = $1
`

func (q *Queries) GetClusterMemberByID(ctx context.Context, id uuid.UUID) (ClusterMember, error) {
	row := q.db.QueryRow(ctx, getClusterMemberByID, id)
	var i ClusterMember
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.ServerID,
		&i.WireguardIp,
		&i.WireguardPublicKey,
		&i.WireguardEndpoint,
		&i.ListenPort,
		&i.JoinedAt,
	)
	return i, err
}

const getClusterMemberByServerID = `-- name: GetClusterMemberByServerID :one
SELECT id, cluster_id, server_id, wireguard_ip, wireguard_public_key, wireguard_endpoint, listen_port, joined_at FROM cluster_members WHERE server_id = $1
`

func (q *Queries) GetClusterMemberByServerID(ctx context.Context, serverID uuid.UUID) (ClusterMember, error) {
	row := q.db.QueryRow(ctx, getClusterMemberByServerID, serverID)
	var i ClusterMember
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.ServerID,
		&i.WireguardIp,
		&i.WireguardPublicKey,
		&i.WireguardEndpoint,
		&i.ListenPort,
		&i.JoinedAt,
	)
	return i, err
}

const getClusterMembersForMesh = `-- name: GetClusterMembersForMesh :many
SELECT cm.id, cm.cluster_id, cm.server_id, cm.wireguard_ip, cm.wireguard_public_key,
       cm.wireguard_endpoint, cm.listen_port, s.name AS server_name, s.agent_id
FROM cluster_members cm
JOIN servers s ON cm.server_id = s.id
WHERE cm.cluster_id = $1
`

type GetClusterMembersForMeshRow struct {
	ID                 uuid.UUID  `json:"id"`
	ClusterID          uuid.UUID  `json:"cluster_id"`
	ServerID           uuid.UUID  `json:"server_id"`
	WireguardIp        netip.Addr `json:"wireguard_ip"`
	WireguardPublicKey string     `json:"wireguard_public_key"`
	WireguardEndpoint  string     `json:"wireguard_endpoint"`
	ListenPort         int32      `json:"listen_port"`
	ServerName         string     `json:"server_name"`
	AgentID            *string    `json:"agent_id"`
}

func (q *Queries) GetClusterMembersForMesh(ctx context.Context, clusterID uuid.UUID) ([]GetClusterMembersForMeshRow, error) {
	rows, err := q.db.Query(ctx, getClusterMembersForMesh, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClusterMembersForMeshRow{}
	for rows.Next() {
		var i GetClusterMembersForMeshRow
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.ServerID,
			&i.WireguardIp,
			&i.WireguardPublicKey,
			&i.WireguardEndpoint,
			&i.ListenPort,
			&i.ServerName,
			&i.AgentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClusterMemberIPs = `-- name: ListClusterMemberIPs :many
SELECT wireguard_ip FROM cluster_members WHERE cluster_id = $1
`

func (q *Queries) ListClusterMemberIPs(ctx context.Context, clusterID uuid.UUID) ([]netip.Addr, error) {
	rows, err := q.db.Query(ctx, listClusterMemberIPs, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []netip.Addr{}
	for rows.Next() {
		var wireguard_ip netip.Addr
		if err := rows.Scan(&wireguard_ip); err != nil {
			return nil, err
		}
		items = append(items, wireguard_ip)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClusterMembers = `-- name: ListClusterMembers :many
SELECT cm.id, cm.cluster_id, cm.server_id, cm.wireguard_ip, cm.wireguard_public_key, cm.wireguard_endpoint, cm.listen_port, cm.joined_at, s.name AS server_name, s.public_ip, s.status AS server_status
FROM cluster_members cm
JOIN servers s ON cm.server_id = s.id
WHERE cm.cluster_id = $1
ORDER BY cm.joined_at
`

type ListClusterMembersRow struct {
	ID                 uuid.UUID  `json:"id"`
	ClusterID          uuid.UUID  `json:"cluster_id"`
	ServerID           uuid.UUID  `json:"server_id"`
	WireguardIp        netip.Addr `json:"wireguard_ip"`
	WireguardPublicKey string     `json:"wireguard_public_key"`
	WireguardEndpoint  string     `json:"wireguard_endpoint"`
	ListenPort         int32      `json:"listen_port"`
	JoinedAt           time.Time  `json:"joined_at"`
	ServerName         string     `json:"server_name"`
	PublicIp           netip.Addr `json:"public_ip"`
	ServerStatus       string     `json:"server_status"`
}

func (q *Queries) ListClusterMembers(ctx context.Context, clusterID uuid.UUID) ([]ListClusterMembersRow, error) {
	rows, err := q.db.Query(ctx, listClusterMembers, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClusterMembersRow{}
	for rows.Next() {
		var i ListClusterMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.ServerID,
			&i.WireguardIp,
			&i.WireguardPublicKey,
			&i.WireguardEndpoint,
			&i.ListenPort,
			&i.JoinedAt,
			&i.ServerName,
			&i.PublicIp,
			&i.ServerStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClusterMemberPublicKey = `-- name: UpdateClusterMemberPublicKey :exec
UPDATE cluster_members SET wireguard_public_key = $2 WHERE id = $1
`

type UpdateClusterMemberPublicKeyParams struct {
	ID                 uuid.UUID `json:"id"`
	WireguardPublicKey string    `json:"wireguard_public_key"`
}

func (q *Queries) UpdateClusterMemberPublicKey(ctx context.Context, arg UpdateClusterMemberPublicKeyParams) error {
	_, err := q.db.Exec(ctx, updateClusterMemberPublicKey, arg.ID, arg.WireguardPublicKey)
	return err
}

const updateServerClusterID = `-- name: UpdateServerClusterID :exec
UPDATE servers SET cluster_id = $2 WHERE id = $1
`

type UpdateServerClusterIDParams struct {
	ID        uuid.UUID   `json:"id"`
	ClusterID pgtype.UUID `json:"cluster_id"`
}

func (q *Queries) UpdateServerClusterID(ctx context.Context, arg UpdateServerClusterIDParams) error {
	_, err := q.db.Exec(ctx, updateServerClusterID, arg.ID, arg.ClusterID)
	return err
}

const updateClusterMemberEndpoint = `-- name: UpdateClusterMemberEndpoint :exec
UPDATE cluster_members SET wireguard_endpoint = $2 WHERE server_id = $1
`

type UpdateClusterMemberEndpointParams struct {
	ServerID          uuid.UUID `json:"server_id"`
	WireguardEndpoint string    `json:"wireguard_endpoint"`
}

func (q *Queries) UpdateClusterMemberEndpoint(ctx context.Context, arg UpdateClusterMemberEndpointParams) error {
	_, err := q.db.Exec(ctx, updateClusterMemberEndpoint, arg.ServerID, arg.WireguardEndpoint)
	return err
}
