// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clusters.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
)

const countClusterMembers = `-- name: CountClusterMembers :one
SELECT count(*) FROM cluster_members WHERE cluster_id = $1
`

func (q *Queries) CountClusterMembers(ctx context.Context, clusterID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countClusterMembers, clusterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCluster = `-- name: CreateCluster :one
INSERT INTO clusters (team_id, name, slug, description, region, cidr)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, team_id, name, slug, description, region, cidr, status, created_at, updated_at
`

type CreateClusterParams struct {
	TeamID      uuid.UUID    `json:"team_id"`
	Name        string       `json:"name"`
	Slug        string       `json:"slug"`
	Description string       `json:"description"`
	Region      string       `json:"region"`
	Cidr        netip.Prefix `json:"cidr"`
}

func (q *Queries) CreateCluster(ctx context.Context, arg CreateClusterParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, createCluster,
		arg.TeamID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Region,
		arg.Cidr,
	)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Region,
		&i.Cidr,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCluster = `-- name: DeleteCluster :exec
DELETE FROM clusters WHERE id = $1 AND team_id = $2
`

type DeleteClusterParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) DeleteCluster(ctx context.Context, arg DeleteClusterParams) error {
	_, err := q.db.Exec(ctx, deleteCluster, arg.ID, arg.TeamID)
	return err
}

const getClusterByID = `-- name: GetClusterByID :one
SELECT id, team_id, name, slug, description, region, cidr, status, created_at, updated_at FROM clusters WHERE id = $1 AND team_id = $2
`

type GetClusterByIDParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) GetClusterByID(ctx context.Context, arg GetClusterByIDParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, getClusterByID, arg.ID, arg.TeamID)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Region,
		&i.Cidr,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClusterByIDAnyTeam = `-- name: GetClusterByIDAnyTeam :one
SELECT id, team_id, name, slug, description, region, cidr, status, created_at, updated_at FROM clusters WHERE id = $1
`

func (q *Queries) GetClusterByIDAnyTeam(ctx context.Context, id uuid.UUID) (Cluster, error) {
	row := q.db.QueryRow(ctx, getClusterByIDAnyTeam, id)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Region,
		&i.Cidr,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClusterBySlug = `-- name: GetClusterBySlug :one
SELECT id, team_id, name, slug, description, region, cidr, status, created_at, updated_at FROM clusters WHERE slug = $1 AND team_id = $2
`

type GetClusterBySlugParams struct {
	Slug   string    `json:"slug"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) GetClusterBySlug(ctx context.Context, arg GetClusterBySlugParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, getClusterBySlug, arg.Slug, arg.TeamID)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Region,
		&i.Cidr,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllClusterCIDRs = `-- name: ListAllClusterCIDRs :many
SELECT cidr FROM clusters
`

func (q *Queries) ListAllClusterCIDRs(ctx context.Context) ([]netip.Prefix, error) {
	rows, err := q.db.Query(ctx, listAllClusterCIDRs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []netip.Prefix{}
	for rows.Next() {
		var cidr netip.Prefix
		if err := rows.Scan(&cidr); err != nil {
			return nil, err
		}
		items = append(items, cidr)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClustersByTeam = `-- name: ListClustersByTeam :many
SELECT id, team_id, name, slug, description, region, cidr, status, created_at, updated_at FROM clusters WHERE team_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListClustersByTeam(ctx context.Context, teamID uuid.UUID) ([]Cluster, error) {
	rows, err := q.db.Query(ctx, listClustersByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cluster{}
	for rows.Next() {
		var i Cluster
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Region,
			&i.Cidr,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCluster = `-- name: UpdateCluster :one
UPDATE clusters SET name = $3, description = $4, region = $5, updated_at = now()
WHERE id = $1 AND team_id = $2 RETURNING id, team_id, name, slug, description, region, cidr, status, created_at, updated_at
`

type UpdateClusterParams struct {
	ID          uuid.UUID `json:"id"`
	TeamID      uuid.UUID `json:"team_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Region      string    `json:"region"`
}

func (q *Queries) UpdateCluster(ctx context.Context, arg UpdateClusterParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, updateCluster,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.Description,
		arg.Region,
	)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Region,
		&i.Cidr,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateClusterStatus = `-- name: UpdateClusterStatus :exec
UPDATE clusters SET status = $2, updated_at = now() WHERE id = $1
`

type UpdateClusterStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateClusterStatus(ctx context.Context, arg UpdateClusterStatusParams) error {
	_, err := q.db.Exec(ctx, updateClusterStatus, arg.ID, arg.Status)
	return err
}
