// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: container_logs.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOldContainerLogs = `-- name: DeleteOldContainerLogs :execresult
DELETE FROM container_logs WHERE ingested_at < $1
`

func (q *Queries) DeleteOldContainerLogs(ctx context.Context, ingestedAt time.Time) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteOldContainerLogs, ingestedAt)
}

const insertContainerLog = `-- name: InsertContainerLog :exec
INSERT INTO container_logs (app_id, deployment_id, server_id, container_name, replica_index, line, stream, logged_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertContainerLogParams struct {
	AppID         uuid.UUID   `json:"app_id"`
	DeploymentID  pgtype.UUID `json:"deployment_id"`
	ServerID      uuid.UUID   `json:"server_id"`
	ContainerName string      `json:"container_name"`
	ReplicaIndex  int32       `json:"replica_index"`
	Line          string      `json:"line"`
	Stream        string      `json:"stream"`
	LoggedAt      time.Time   `json:"logged_at"`
}

func (q *Queries) InsertContainerLog(ctx context.Context, arg InsertContainerLogParams) error {
	_, err := q.db.Exec(ctx, insertContainerLog,
		arg.AppID,
		arg.DeploymentID,
		arg.ServerID,
		arg.ContainerName,
		arg.ReplicaIndex,
		arg.Line,
		arg.Stream,
		arg.LoggedAt,
	)
	return err
}

const searchContainerLogs = `-- name: SearchContainerLogs :many
SELECT id, app_id, server_id, container_name, replica_index, line, stream, logged_at
FROM container_logs
WHERE app_id = $1
  AND logged_at >= $2
  AND logged_at <= $3
  AND to_tsvector('english', line) @@ plainto_tsquery('english', $4)
ORDER BY logged_at DESC
LIMIT $5
`

type SearchContainerLogsParams struct {
	AppID          uuid.UUID `json:"app_id"`
	LoggedAt       time.Time `json:"logged_at"`
	LoggedAt_2     time.Time `json:"logged_at_2"`
	PlaintoTsquery string    `json:"plainto_tsquery"`
	Limit          int32     `json:"limit"`
}

type SearchContainerLogsRow struct {
	ID            int64     `json:"id"`
	AppID         uuid.UUID `json:"app_id"`
	ServerID      uuid.UUID `json:"server_id"`
	ContainerName string    `json:"container_name"`
	ReplicaIndex  int32     `json:"replica_index"`
	Line          string    `json:"line"`
	Stream        string    `json:"stream"`
	LoggedAt      time.Time `json:"logged_at"`
}

func (q *Queries) SearchContainerLogs(ctx context.Context, arg SearchContainerLogsParams) ([]SearchContainerLogsRow, error) {
	rows, err := q.db.Query(ctx, searchContainerLogs,
		arg.AppID,
		arg.LoggedAt,
		arg.LoggedAt_2,
		arg.PlaintoTsquery,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchContainerLogsRow{}
	for rows.Next() {
		var i SearchContainerLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.ServerID,
			&i.ContainerName,
			&i.ReplicaIndex,
			&i.Line,
			&i.Stream,
			&i.LoggedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tailContainerLogs = `-- name: TailContainerLogs :many
SELECT id, app_id, server_id, container_name, replica_index, line, stream, logged_at
FROM container_logs
WHERE app_id = $1
ORDER BY logged_at DESC
LIMIT $2
`

type TailContainerLogsParams struct {
	AppID uuid.UUID `json:"app_id"`
	Limit int32     `json:"limit"`
}

type TailContainerLogsRow struct {
	ID            int64     `json:"id"`
	AppID         uuid.UUID `json:"app_id"`
	ServerID      uuid.UUID `json:"server_id"`
	ContainerName string    `json:"container_name"`
	ReplicaIndex  int32     `json:"replica_index"`
	Line          string    `json:"line"`
	Stream        string    `json:"stream"`
	LoggedAt      time.Time `json:"logged_at"`
}

func (q *Queries) TailContainerLogs(ctx context.Context, arg TailContainerLogsParams) ([]TailContainerLogsRow, error) {
	rows, err := q.db.Query(ctx, tailContainerLogs, arg.AppID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TailContainerLogsRow{}
	for rows.Next() {
		var i TailContainerLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.ServerID,
			&i.ContainerName,
			&i.ReplicaIndex,
			&i.Line,
			&i.Stream,
			&i.LoggedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
