// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: database_credential_rotations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDatabaseCredentialRotation = `-- name: CreateDatabaseCredentialRotation :one
INSERT INTO database_credential_rotations (database_id, rotated_by, old_secret_id, status)
VALUES ($1, $2, $3, $4)
RETURNING id, database_id, rotated_by, old_secret_id, new_secret_id, status, linked_apps_restarted, error, created_at, completed_at
`

type CreateDatabaseCredentialRotationParams struct {
	DatabaseID  uuid.UUID   `json:"database_id"`
	RotatedBy   uuid.UUID   `json:"rotated_by"`
	OldSecretID pgtype.UUID `json:"old_secret_id"`
	Status      string      `json:"status"`
}

func (q *Queries) CreateDatabaseCredentialRotation(ctx context.Context, arg CreateDatabaseCredentialRotationParams) (DatabaseCredentialRotation, error) {
	row := q.db.QueryRow(ctx, createDatabaseCredentialRotation,
		arg.DatabaseID,
		arg.RotatedBy,
		arg.OldSecretID,
		arg.Status,
	)
	var i DatabaseCredentialRotation
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.RotatedBy,
		&i.OldSecretID,
		&i.NewSecretID,
		&i.Status,
		&i.LinkedAppsRestarted,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getDatabaseCredentialRotation = `-- name: GetDatabaseCredentialRotation :one
SELECT id, database_id, rotated_by, old_secret_id, new_secret_id, status, linked_apps_restarted, error, created_at, completed_at FROM database_credential_rotations WHERE id = $1
`

func (q *Queries) GetDatabaseCredentialRotation(ctx context.Context, id uuid.UUID) (DatabaseCredentialRotation, error) {
	row := q.db.QueryRow(ctx, getDatabaseCredentialRotation, id)
	var i DatabaseCredentialRotation
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.RotatedBy,
		&i.OldSecretID,
		&i.NewSecretID,
		&i.Status,
		&i.LinkedAppsRestarted,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listDatabaseCredentialRotationsByDatabase = `-- name: ListDatabaseCredentialRotationsByDatabase :many
SELECT id, database_id, rotated_by, old_secret_id, new_secret_id, status, linked_apps_restarted, error, created_at, completed_at FROM database_credential_rotations WHERE database_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDatabaseCredentialRotationsByDatabase(ctx context.Context, databaseID uuid.UUID) ([]DatabaseCredentialRotation, error) {
	rows, err := q.db.Query(ctx, listDatabaseCredentialRotationsByDatabase, databaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatabaseCredentialRotation{}
	for rows.Next() {
		var i DatabaseCredentialRotation
		if err := rows.Scan(
			&i.ID,
			&i.DatabaseID,
			&i.RotatedBy,
			&i.OldSecretID,
			&i.NewSecretID,
			&i.Status,
			&i.LinkedAppsRestarted,
			&i.Error,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDatabaseCredentialRotationCompleted = `-- name: UpdateDatabaseCredentialRotationCompleted :exec
UPDATE database_credential_rotations
SET status = $2,
    new_secret_id = $3,
    linked_apps_restarted = $4,
    completed_at = now(),
    error = $5
WHERE id = $1
`

type UpdateDatabaseCredentialRotationCompletedParams struct {
	ID                  uuid.UUID   `json:"id"`
	Status              string      `json:"status"`
	NewSecretID         pgtype.UUID `json:"new_secret_id"`
	LinkedAppsRestarted int32       `json:"linked_apps_restarted"`
	Error               *string     `json:"error"`
}

func (q *Queries) UpdateDatabaseCredentialRotationCompleted(ctx context.Context, arg UpdateDatabaseCredentialRotationCompletedParams) error {
	_, err := q.db.Exec(ctx, updateDatabaseCredentialRotationCompleted,
		arg.ID,
		arg.Status,
		arg.NewSecretID,
		arg.LinkedAppsRestarted,
		arg.Error,
	)
	return err
}

const updateDatabaseCredentialRotationStatus = `-- name: UpdateDatabaseCredentialRotationStatus :exec
UPDATE database_credential_rotations
SET status = $2, error = $3
WHERE id = $1
`

type UpdateDatabaseCredentialRotationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
	Error  *string   `json:"error"`
}

func (q *Queries) UpdateDatabaseCredentialRotationStatus(ctx context.Context, arg UpdateDatabaseCredentialRotationStatusParams) error {
	_, err := q.db.Exec(ctx, updateDatabaseCredentialRotationStatus, arg.ID, arg.Status, arg.Error)
	return err
}
