// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: database_query_history.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDatabaseQueryHistory = `-- name: CreateDatabaseQueryHistory :one
INSERT INTO database_query_history (
    user_id, database_id, query_text, write_mode,
    execution_time_ms, row_count, error
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, database_id, query_text, write_mode, execution_time_ms, row_count, error, created_at
`

type CreateDatabaseQueryHistoryParams struct {
	UserID          uuid.UUID `json:"user_id"`
	DatabaseID      uuid.UUID `json:"database_id"`
	QueryText       string    `json:"query_text"`
	WriteMode       bool      `json:"write_mode"`
	ExecutionTimeMs *int32    `json:"execution_time_ms"`
	RowCount        *int32    `json:"row_count"`
	Error           *string   `json:"error"`
}

func (q *Queries) CreateDatabaseQueryHistory(ctx context.Context, arg CreateDatabaseQueryHistoryParams) (DatabaseQueryHistory, error) {
	row := q.db.QueryRow(ctx, createDatabaseQueryHistory,
		arg.UserID,
		arg.DatabaseID,
		arg.QueryText,
		arg.WriteMode,
		arg.ExecutionTimeMs,
		arg.RowCount,
		arg.Error,
	)
	var i DatabaseQueryHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DatabaseID,
		&i.QueryText,
		&i.WriteMode,
		&i.ExecutionTimeMs,
		&i.RowCount,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDatabaseQueryHistoryOlderThan = `-- name: DeleteDatabaseQueryHistoryOlderThan :exec
DELETE FROM database_query_history WHERE created_at < $1
`

func (q *Queries) DeleteDatabaseQueryHistoryOlderThan(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteDatabaseQueryHistoryOlderThan, createdAt)
	return err
}

const listDatabaseQueryHistoryByUser = `-- name: ListDatabaseQueryHistoryByUser :many
SELECT id, user_id, database_id, query_text, write_mode, execution_time_ms, row_count, error, created_at FROM database_query_history
WHERE user_id = $1
  AND ($2::UUID IS NULL OR database_id = $2::UUID)
ORDER BY created_at DESC
LIMIT $3
`

type ListDatabaseQueryHistoryByUserParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	DatabaseID pgtype.UUID `json:"database_id"`
	LimitCount int32       `json:"limit_count"`
}

func (q *Queries) ListDatabaseQueryHistoryByUser(ctx context.Context, arg ListDatabaseQueryHistoryByUserParams) ([]DatabaseQueryHistory, error) {
	rows, err := q.db.Query(ctx, listDatabaseQueryHistoryByUser, arg.UserID, arg.DatabaseID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatabaseQueryHistory{}
	for rows.Next() {
		var i DatabaseQueryHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DatabaseID,
			&i.QueryText,
			&i.WriteMode,
			&i.ExecutionTimeMs,
			&i.RowCount,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
