// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: databases.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDatabasesByServer = `-- name: CountDatabasesByServer :many
SELECT server_id, COUNT(*) AS db_count
FROM databases
WHERE cluster_id = $1 AND status != 'deleted'
GROUP BY server_id
`

type CountDatabasesByServerRow struct {
	ServerID uuid.UUID `json:"server_id"`
	DbCount  int64     `json:"db_count"`
}

func (q *Queries) CountDatabasesByServer(ctx context.Context, clusterID uuid.UUID) ([]CountDatabasesByServerRow, error) {
	rows, err := q.db.Query(ctx, countDatabasesByServer, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDatabasesByServerRow{}
	for rows.Next() {
		var i CountDatabasesByServerRow
		if err := rows.Scan(&i.ServerID, &i.DbCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createDatabase = `-- name: CreateDatabase :one
INSERT INTO databases (
    team_id, project_id, cluster_id, server_id, volume_id,
    template_slug, version, name, container_name, status,
    port, superuser_secret_id, appuser_secret_id,
    resource_cpu_millicores, resource_memory_mb,
    backup_schedule, backup_retention_days, backup_storage_type
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
RETURNING id, team_id, project_id, cluster_id, server_id, volume_id, template_slug, version, name, container_name, status, port, dns_record, superuser_secret_id, appuser_secret_id, resource_cpu_millicores, resource_memory_mb, backup_schedule, backup_retention_days, backup_storage_type, created_at, updated_at
`

type CreateDatabaseParams struct {
	TeamID                uuid.UUID   `json:"team_id"`
	ProjectID             uuid.UUID   `json:"project_id"`
	ClusterID             uuid.UUID   `json:"cluster_id"`
	ServerID              uuid.UUID   `json:"server_id"`
	VolumeID              pgtype.UUID `json:"volume_id"`
	TemplateSlug          string      `json:"template_slug"`
	Version               string      `json:"version"`
	Name                  string      `json:"name"`
	ContainerName         string      `json:"container_name"`
	Status                string      `json:"status"`
	Port                  int32       `json:"port"`
	SuperuserSecretID     pgtype.UUID `json:"superuser_secret_id"`
	AppuserSecretID       pgtype.UUID `json:"appuser_secret_id"`
	ResourceCpuMillicores int32       `json:"resource_cpu_millicores"`
	ResourceMemoryMb      int32       `json:"resource_memory_mb"`
	BackupSchedule        *string     `json:"backup_schedule"`
	BackupRetentionDays   *int32      `json:"backup_retention_days"`
	BackupStorageType     *string     `json:"backup_storage_type"`
}

func (q *Queries) CreateDatabase(ctx context.Context, arg CreateDatabaseParams) (Database, error) {
	row := q.db.QueryRow(ctx, createDatabase,
		arg.TeamID,
		arg.ProjectID,
		arg.ClusterID,
		arg.ServerID,
		arg.VolumeID,
		arg.TemplateSlug,
		arg.Version,
		arg.Name,
		arg.ContainerName,
		arg.Status,
		arg.Port,
		arg.SuperuserSecretID,
		arg.AppuserSecretID,
		arg.ResourceCpuMillicores,
		arg.ResourceMemoryMb,
		arg.BackupSchedule,
		arg.BackupRetentionDays,
		arg.BackupStorageType,
	)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ProjectID,
		&i.ClusterID,
		&i.ServerID,
		&i.VolumeID,
		&i.TemplateSlug,
		&i.Version,
		&i.Name,
		&i.ContainerName,
		&i.Status,
		&i.Port,
		&i.DnsRecord,
		&i.SuperuserSecretID,
		&i.AppuserSecretID,
		&i.ResourceCpuMillicores,
		&i.ResourceMemoryMb,
		&i.BackupSchedule,
		&i.BackupRetentionDays,
		&i.BackupStorageType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDatabase = `-- name: DeleteDatabase :exec
DELETE FROM databases WHERE id = $1
`

func (q *Queries) DeleteDatabase(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDatabase, id)
	return err
}

const getDatabase = `-- name: GetDatabase :one
SELECT id, team_id, project_id, cluster_id, server_id, volume_id, template_slug, version, name, container_name, status, port, dns_record, superuser_secret_id, appuser_secret_id, resource_cpu_millicores, resource_memory_mb, backup_schedule, backup_retention_days, backup_storage_type, created_at, updated_at FROM databases WHERE id = $1
`

func (q *Queries) GetDatabase(ctx context.Context, id uuid.UUID) (Database, error) {
	row := q.db.QueryRow(ctx, getDatabase, id)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ProjectID,
		&i.ClusterID,
		&i.ServerID,
		&i.VolumeID,
		&i.TemplateSlug,
		&i.Version,
		&i.Name,
		&i.ContainerName,
		&i.Status,
		&i.Port,
		&i.DnsRecord,
		&i.SuperuserSecretID,
		&i.AppuserSecretID,
		&i.ResourceCpuMillicores,
		&i.ResourceMemoryMb,
		&i.BackupSchedule,
		&i.BackupRetentionDays,
		&i.BackupStorageType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDatabaseByName = `-- name: GetDatabaseByName :one
SELECT id, team_id, project_id, cluster_id, server_id, volume_id, template_slug, version, name, container_name, status, port, dns_record, superuser_secret_id, appuser_secret_id, resource_cpu_millicores, resource_memory_mb, backup_schedule, backup_retention_days, backup_storage_type, created_at, updated_at FROM databases WHERE project_id = $1 AND name = $2
`

type GetDatabaseByNameParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Name      string    `json:"name"`
}

func (q *Queries) GetDatabaseByName(ctx context.Context, arg GetDatabaseByNameParams) (Database, error) {
	row := q.db.QueryRow(ctx, getDatabaseByName, arg.ProjectID, arg.Name)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ProjectID,
		&i.ClusterID,
		&i.ServerID,
		&i.VolumeID,
		&i.TemplateSlug,
		&i.Version,
		&i.Name,
		&i.ContainerName,
		&i.Status,
		&i.Port,
		&i.DnsRecord,
		&i.SuperuserSecretID,
		&i.AppuserSecretID,
		&i.ResourceCpuMillicores,
		&i.ResourceMemoryMb,
		&i.BackupSchedule,
		&i.BackupRetentionDays,
		&i.BackupStorageType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDatabasesByCluster = `-- name: ListDatabasesByCluster :many
SELECT id, team_id, project_id, cluster_id, server_id, volume_id, template_slug, version, name, container_name, status, port, dns_record, superuser_secret_id, appuser_secret_id, resource_cpu_millicores, resource_memory_mb, backup_schedule, backup_retention_days, backup_storage_type, created_at, updated_at FROM databases WHERE cluster_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDatabasesByCluster(ctx context.Context, clusterID uuid.UUID) ([]Database, error) {
	rows, err := q.db.Query(ctx, listDatabasesByCluster, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Database{}
	for rows.Next() {
		var i Database
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ProjectID,
			&i.ClusterID,
			&i.ServerID,
			&i.VolumeID,
			&i.TemplateSlug,
			&i.Version,
			&i.Name,
			&i.ContainerName,
			&i.Status,
			&i.Port,
			&i.DnsRecord,
			&i.SuperuserSecretID,
			&i.AppuserSecretID,
			&i.ResourceCpuMillicores,
			&i.ResourceMemoryMb,
			&i.BackupSchedule,
			&i.BackupRetentionDays,
			&i.BackupStorageType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabasesByProject = `-- name: ListDatabasesByProject :many
SELECT id, team_id, project_id, cluster_id, server_id, volume_id, template_slug, version, name, container_name, status, port, dns_record, superuser_secret_id, appuser_secret_id, resource_cpu_millicores, resource_memory_mb, backup_schedule, backup_retention_days, backup_storage_type, created_at, updated_at FROM databases WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDatabasesByProject(ctx context.Context, projectID uuid.UUID) ([]Database, error) {
	rows, err := q.db.Query(ctx, listDatabasesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Database{}
	for rows.Next() {
		var i Database
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ProjectID,
			&i.ClusterID,
			&i.ServerID,
			&i.VolumeID,
			&i.TemplateSlug,
			&i.Version,
			&i.Name,
			&i.ContainerName,
			&i.Status,
			&i.Port,
			&i.DnsRecord,
			&i.SuperuserSecretID,
			&i.AppuserSecretID,
			&i.ResourceCpuMillicores,
			&i.ResourceMemoryMb,
			&i.BackupSchedule,
			&i.BackupRetentionDays,
			&i.BackupStorageType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDatabaseDNSRecord = `-- name: UpdateDatabaseDNSRecord :exec
UPDATE databases
SET dns_record = $2, updated_at = now()
WHERE id = $1
`

type UpdateDatabaseDNSRecordParams struct {
	ID        uuid.UUID `json:"id"`
	DnsRecord *string   `json:"dns_record"`
}

func (q *Queries) UpdateDatabaseDNSRecord(ctx context.Context, arg UpdateDatabaseDNSRecordParams) error {
	_, err := q.db.Exec(ctx, updateDatabaseDNSRecord, arg.ID, arg.DnsRecord)
	return err
}

const updateDatabaseStatus = `-- name: UpdateDatabaseStatus :one
UPDATE databases
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, team_id, project_id, cluster_id, server_id, volume_id, template_slug, version, name, container_name, status, port, dns_record, superuser_secret_id, appuser_secret_id, resource_cpu_millicores, resource_memory_mb, backup_schedule, backup_retention_days, backup_storage_type, created_at, updated_at
`

type UpdateDatabaseStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateDatabaseStatus(ctx context.Context, arg UpdateDatabaseStatusParams) (Database, error) {
	row := q.db.QueryRow(ctx, updateDatabaseStatus, arg.ID, arg.Status)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ProjectID,
		&i.ClusterID,
		&i.ServerID,
		&i.VolumeID,
		&i.TemplateSlug,
		&i.Version,
		&i.Name,
		&i.ContainerName,
		&i.Status,
		&i.Port,
		&i.DnsRecord,
		&i.SuperuserSecretID,
		&i.AppuserSecretID,
		&i.ResourceCpuMillicores,
		&i.ResourceMemoryMb,
		&i.BackupSchedule,
		&i.BackupRetentionDays,
		&i.BackupStorageType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDatabaseVolume = `-- name: UpdateDatabaseVolume :exec
UPDATE databases
SET volume_id = $2, updated_at = now()
WHERE id = $1
`

type UpdateDatabaseVolumeParams struct {
	ID       uuid.UUID   `json:"id"`
	VolumeID pgtype.UUID `json:"volume_id"`
}

func (q *Queries) UpdateDatabaseVolume(ctx context.Context, arg UpdateDatabaseVolumeParams) error {
	_, err := q.db.Exec(ctx, updateDatabaseVolume, arg.ID, arg.VolumeID)
	return err
}
