// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: database_backups.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBackup = `-- name: CreateBackup :one
INSERT INTO database_backups (database_id, type, status, backup_tool, triggered_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, database_id, type, status, size_bytes, storage_type, storage_path, backup_tool, triggered_by, started_at, completed_at, error
`

type CreateBackupParams struct {
	DatabaseID  uuid.UUID   `json:"database_id"`
	Type        string      `json:"type"`
	Status      string      `json:"status"`
	BackupTool  string      `json:"backup_tool"`
	TriggeredBy pgtype.UUID `json:"triggered_by"`
}

func (q *Queries) CreateBackup(ctx context.Context, arg CreateBackupParams) (DatabaseBackup, error) {
	row := q.db.QueryRow(ctx, createBackup,
		arg.DatabaseID,
		arg.Type,
		arg.Status,
		arg.BackupTool,
		arg.TriggeredBy,
	)
	var i DatabaseBackup
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.Type,
		&i.Status,
		&i.SizeBytes,
		&i.StorageType,
		&i.StoragePath,
		&i.BackupTool,
		&i.TriggeredBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
	)
	return i, err
}

const deleteBackup = `-- name: DeleteBackup :exec
DELETE FROM database_backups WHERE id = $1
`

func (q *Queries) DeleteBackup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBackup, id)
	return err
}

const deleteBackupsOlderThan = `-- name: DeleteBackupsOlderThan :exec
DELETE FROM database_backups
WHERE database_id = $1
  AND started_at < $2
`

type DeleteBackupsOlderThanParams struct {
	DatabaseID uuid.UUID `json:"database_id"`
	StartedAt  time.Time `json:"started_at"`
}

func (q *Queries) DeleteBackupsOlderThan(ctx context.Context, arg DeleteBackupsOlderThanParams) error {
	_, err := q.db.Exec(ctx, deleteBackupsOlderThan, arg.DatabaseID, arg.StartedAt)
	return err
}

const getBackup = `-- name: GetBackup :one
SELECT id, database_id, type, status, size_bytes, storage_type, storage_path, backup_tool, triggered_by, started_at, completed_at, error FROM database_backups WHERE id = $1
`

func (q *Queries) GetBackup(ctx context.Context, id uuid.UUID) (DatabaseBackup, error) {
	row := q.db.QueryRow(ctx, getBackup, id)
	var i DatabaseBackup
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.Type,
		&i.Status,
		&i.SizeBytes,
		&i.StorageType,
		&i.StoragePath,
		&i.BackupTool,
		&i.TriggeredBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
	)
	return i, err
}

const getLatestBackupForDatabase = `-- name: GetLatestBackupForDatabase :one
SELECT id, database_id, type, status, size_bytes, storage_type, storage_path, backup_tool, triggered_by, started_at, completed_at, error FROM database_backups
WHERE database_id = $1 AND status = 'completed'
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetLatestBackupForDatabase(ctx context.Context, databaseID uuid.UUID) (DatabaseBackup, error) {
	row := q.db.QueryRow(ctx, getLatestBackupForDatabase, databaseID)
	var i DatabaseBackup
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.Type,
		&i.Status,
		&i.SizeBytes,
		&i.StorageType,
		&i.StoragePath,
		&i.BackupTool,
		&i.TriggeredBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
	)
	return i, err
}

const listBackupsByDatabase = `-- name: ListBackupsByDatabase :many
SELECT id, database_id, type, status, size_bytes, storage_type, storage_path, backup_tool, triggered_by, started_at, completed_at, error FROM database_backups WHERE database_id = $1 ORDER BY started_at DESC
`

func (q *Queries) ListBackupsByDatabase(ctx context.Context, databaseID uuid.UUID) ([]DatabaseBackup, error) {
	rows, err := q.db.Query(ctx, listBackupsByDatabase, databaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatabaseBackup{}
	for rows.Next() {
		var i DatabaseBackup
		if err := rows.Scan(
			&i.ID,
			&i.DatabaseID,
			&i.Type,
			&i.Status,
			&i.SizeBytes,
			&i.StorageType,
			&i.StoragePath,
			&i.BackupTool,
			&i.TriggeredBy,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackupsOlderThan = `-- name: ListBackupsOlderThan :many
SELECT id, database_id, type, status, size_bytes, storage_type, storage_path, backup_tool, triggered_by, started_at, completed_at, error FROM database_backups
WHERE database_id = $1
  AND started_at < $2
`

type ListBackupsOlderThanParams struct {
	DatabaseID uuid.UUID `json:"database_id"`
	StartedAt  time.Time `json:"started_at"`
}

func (q *Queries) ListBackupsOlderThan(ctx context.Context, arg ListBackupsOlderThanParams) ([]DatabaseBackup, error) {
	rows, err := q.db.Query(ctx, listBackupsOlderThan, arg.DatabaseID, arg.StartedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatabaseBackup{}
	for rows.Next() {
		var i DatabaseBackup
		if err := rows.Scan(
			&i.ID,
			&i.DatabaseID,
			&i.Type,
			&i.Status,
			&i.SizeBytes,
			&i.StorageType,
			&i.StoragePath,
			&i.BackupTool,
			&i.TriggeredBy,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabasesWithBackupSchedule = `-- name: ListDatabasesWithBackupSchedule :many
SELECT id, team_id, project_id, cluster_id, server_id, volume_id, template_slug, version, name, container_name, status, port, dns_record, superuser_secret_id, appuser_secret_id, resource_cpu_millicores, resource_memory_mb, backup_schedule, backup_retention_days, backup_storage_type, created_at, updated_at FROM databases
WHERE backup_schedule IS NOT NULL AND status = 'running'
`

func (q *Queries) ListDatabasesWithBackupSchedule(ctx context.Context) ([]Database, error) {
	rows, err := q.db.Query(ctx, listDatabasesWithBackupSchedule)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Database{}
	for rows.Next() {
		var i Database
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ProjectID,
			&i.ClusterID,
			&i.ServerID,
			&i.VolumeID,
			&i.TemplateSlug,
			&i.Version,
			&i.Name,
			&i.ContainerName,
			&i.Status,
			&i.Port,
			&i.DnsRecord,
			&i.SuperuserSecretID,
			&i.AppuserSecretID,
			&i.ResourceCpuMillicores,
			&i.ResourceMemoryMb,
			&i.BackupSchedule,
			&i.BackupRetentionDays,
			&i.BackupStorageType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBackupCompleted = `-- name: UpdateBackupCompleted :exec
UPDATE database_backups
SET status = 'completed',
    size_bytes = $2,
    storage_path = $3,
    completed_at = now()
WHERE id = $1
`

type UpdateBackupCompletedParams struct {
	ID          uuid.UUID `json:"id"`
	SizeBytes   *int64    `json:"size_bytes"`
	StoragePath *string   `json:"storage_path"`
}

func (q *Queries) UpdateBackupCompleted(ctx context.Context, arg UpdateBackupCompletedParams) error {
	_, err := q.db.Exec(ctx, updateBackupCompleted, arg.ID, arg.SizeBytes, arg.StoragePath)
	return err
}

const updateBackupFailed = `-- name: UpdateBackupFailed :exec
UPDATE database_backups
SET status = 'failed',
    error = $2,
    completed_at = now()
WHERE id = $1
`

type UpdateBackupFailedParams struct {
	ID    uuid.UUID `json:"id"`
	Error *string   `json:"error"`
}

func (q *Queries) UpdateBackupFailed(ctx context.Context, arg UpdateBackupFailedParams) error {
	_, err := q.db.Exec(ctx, updateBackupFailed, arg.ID, arg.Error)
	return err
}

const updateBackupStarted = `-- name: UpdateBackupStarted :exec
UPDATE database_backups
SET status = 'running', started_at = now()
WHERE id = $1
`

func (q *Queries) UpdateBackupStarted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateBackupStarted, id)
	return err
}
