// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: database_saved_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDatabaseSavedQuery = `-- name: CreateDatabaseSavedQuery :one
INSERT INTO database_saved_queries (project_id, user_id, database_id, name, query_text)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, user_id, database_id, name, query_text, created_at, updated_at
`

type CreateDatabaseSavedQueryParams struct {
	ProjectID  uuid.UUID   `json:"project_id"`
	UserID     uuid.UUID   `json:"user_id"`
	DatabaseID pgtype.UUID `json:"database_id"`
	Name       string      `json:"name"`
	QueryText  string      `json:"query_text"`
}

func (q *Queries) CreateDatabaseSavedQuery(ctx context.Context, arg CreateDatabaseSavedQueryParams) (DatabaseSavedQuery, error) {
	row := q.db.QueryRow(ctx, createDatabaseSavedQuery,
		arg.ProjectID,
		arg.UserID,
		arg.DatabaseID,
		arg.Name,
		arg.QueryText,
	)
	var i DatabaseSavedQuery
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.DatabaseID,
		&i.Name,
		&i.QueryText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDatabaseSavedQuery = `-- name: DeleteDatabaseSavedQuery :exec
DELETE FROM database_saved_queries WHERE id = $1
`

func (q *Queries) DeleteDatabaseSavedQuery(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDatabaseSavedQuery, id)
	return err
}

const getDatabaseSavedQuery = `-- name: GetDatabaseSavedQuery :one
SELECT id, project_id, user_id, database_id, name, query_text, created_at, updated_at FROM database_saved_queries WHERE id = $1
`

func (q *Queries) GetDatabaseSavedQuery(ctx context.Context, id uuid.UUID) (DatabaseSavedQuery, error) {
	row := q.db.QueryRow(ctx, getDatabaseSavedQuery, id)
	var i DatabaseSavedQuery
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.DatabaseID,
		&i.Name,
		&i.QueryText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDatabaseSavedQueriesByProject = `-- name: ListDatabaseSavedQueriesByProject :many
SELECT id, project_id, user_id, database_id, name, query_text, created_at, updated_at FROM database_saved_queries
WHERE project_id = $1
ORDER BY name ASC
`

func (q *Queries) ListDatabaseSavedQueriesByProject(ctx context.Context, projectID uuid.UUID) ([]DatabaseSavedQuery, error) {
	rows, err := q.db.Query(ctx, listDatabaseSavedQueriesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatabaseSavedQuery{}
	for rows.Next() {
		var i DatabaseSavedQuery
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.DatabaseID,
			&i.Name,
			&i.QueryText,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDatabaseSavedQuery = `-- name: UpdateDatabaseSavedQuery :one
UPDATE database_saved_queries
SET name = $2, query_text = $3, updated_at = now()
WHERE id = $1
RETURNING id, project_id, user_id, database_id, name, query_text, created_at, updated_at
`

type UpdateDatabaseSavedQueryParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	QueryText string    `json:"query_text"`
}

func (q *Queries) UpdateDatabaseSavedQuery(ctx context.Context, arg UpdateDatabaseSavedQueryParams) (DatabaseSavedQuery, error) {
	row := q.db.QueryRow(ctx, updateDatabaseSavedQuery, arg.ID, arg.Name, arg.QueryText)
	var i DatabaseSavedQuery
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.DatabaseID,
		&i.Name,
		&i.QueryText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
