// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: database_links.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createDatabaseLink = `-- name: CreateDatabaseLink :one
INSERT INTO database_links (database_id, app_id, env_prefix)
VALUES ($1, $2, $3)
RETURNING id, database_id, app_id, env_prefix, created_at
`

type CreateDatabaseLinkParams struct {
	DatabaseID uuid.UUID `json:"database_id"`
	AppID      uuid.UUID `json:"app_id"`
	EnvPrefix  string    `json:"env_prefix"`
}

func (q *Queries) CreateDatabaseLink(ctx context.Context, arg CreateDatabaseLinkParams) (DatabaseLink, error) {
	row := q.db.QueryRow(ctx, createDatabaseLink, arg.DatabaseID, arg.AppID, arg.EnvPrefix)
	var i DatabaseLink
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.AppID,
		&i.EnvPrefix,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDatabaseLink = `-- name: DeleteDatabaseLink :exec
DELETE FROM database_links WHERE id = $1
`

func (q *Queries) DeleteDatabaseLink(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDatabaseLink, id)
	return err
}

const deleteDatabaseLinksByDatabase = `-- name: DeleteDatabaseLinksByDatabase :exec
DELETE FROM database_links WHERE database_id = $1
`

func (q *Queries) DeleteDatabaseLinksByDatabase(ctx context.Context, databaseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDatabaseLinksByDatabase, databaseID)
	return err
}

const getDatabaseLink = `-- name: GetDatabaseLink :one
SELECT id, database_id, app_id, env_prefix, created_at FROM database_links WHERE id = $1
`

func (q *Queries) GetDatabaseLink(ctx context.Context, id uuid.UUID) (DatabaseLink, error) {
	row := q.db.QueryRow(ctx, getDatabaseLink, id)
	var i DatabaseLink
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.AppID,
		&i.EnvPrefix,
		&i.CreatedAt,
	)
	return i, err
}

const listDatabaseLinksByApp = `-- name: ListDatabaseLinksByApp :many
SELECT id, database_id, app_id, env_prefix, created_at FROM database_links WHERE app_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDatabaseLinksByApp(ctx context.Context, appID uuid.UUID) ([]DatabaseLink, error) {
	rows, err := q.db.Query(ctx, listDatabaseLinksByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatabaseLink{}
	for rows.Next() {
		var i DatabaseLink
		if err := rows.Scan(
			&i.ID,
			&i.DatabaseID,
			&i.AppID,
			&i.EnvPrefix,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabaseLinksByDatabase = `-- name: ListDatabaseLinksByDatabase :many
SELECT id, database_id, app_id, env_prefix, created_at FROM database_links WHERE database_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDatabaseLinksByDatabase(ctx context.Context, databaseID uuid.UUID) ([]DatabaseLink, error) {
	rows, err := q.db.Query(ctx, listDatabaseLinksByDatabase, databaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatabaseLink{}
	for rows.Next() {
		var i DatabaseLink
		if err := rows.Scan(
			&i.ID,
			&i.DatabaseID,
			&i.AppID,
			&i.EnvPrefix,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
