// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployments.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendDeploymentLogs = `-- name: AppendDeploymentLogs :exec
UPDATE deployments SET logs = logs || $2 WHERE id = $1
`

type AppendDeploymentLogsParams struct {
	ID   uuid.UUID `json:"id"`
	Logs string    `json:"logs"`
}

func (q *Queries) AppendDeploymentLogs(ctx context.Context, arg AppendDeploymentLogsParams) error {
	_, err := q.db.Exec(ctx, appendDeploymentLogs, arg.ID, arg.Logs)
	return err
}

const completeDeployment = `-- name: CompleteDeployment :exec
UPDATE deployments
SET status = $2, completed_at = now(), error = $3
WHERE id = $1
`

type CompleteDeploymentParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
	Error  *string   `json:"error"`
}

func (q *Queries) CompleteDeployment(ctx context.Context, arg CompleteDeploymentParams) error {
	_, err := q.db.Exec(ctx, completeDeployment, arg.ID, arg.Status, arg.Error)
	return err
}

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (app_id, environment_id, build_id, strategy, replicas_desired, env_snapshot)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, app_id, environment_id, build_id, strategy, replicas_desired, replicas_ready, env_snapshot, status, started_at, completed_at, error, created_at, logs, platform_domain
`

type CreateDeploymentParams struct {
	AppID           uuid.UUID `json:"app_id"`
	EnvironmentID   uuid.UUID `json:"environment_id"`
	BuildID         uuid.UUID `json:"build_id"`
	Strategy        string    `json:"strategy"`
	ReplicasDesired int32     `json:"replicas_desired"`
	EnvSnapshot     []byte    `json:"env_snapshot"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.AppID,
		arg.EnvironmentID,
		arg.BuildID,
		arg.Strategy,
		arg.ReplicasDesired,
		arg.EnvSnapshot,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.EnvironmentID,
		&i.BuildID,
		&i.Strategy,
		&i.ReplicasDesired,
		&i.ReplicasReady,
		&i.EnvSnapshot,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.CreatedAt,
		&i.Logs,
		&i.PlatformDomain,
	)
	return i, err
}

const createDeploymentTarget = `-- name: CreateDeploymentTarget :one
INSERT INTO deployment_targets (deployment_id, server_id)
VALUES ($1, $2)
RETURNING id, deployment_id, server_id, container_id, status, health_check_attempts, started_at, healthy_at, stopped_at, error
`

type CreateDeploymentTargetParams struct {
	DeploymentID uuid.UUID `json:"deployment_id"`
	ServerID     uuid.UUID `json:"server_id"`
}

func (q *Queries) CreateDeploymentTarget(ctx context.Context, arg CreateDeploymentTargetParams) (DeploymentTarget, error) {
	row := q.db.QueryRow(ctx, createDeploymentTarget, arg.DeploymentID, arg.ServerID)
	var i DeploymentTarget
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.ServerID,
		&i.ContainerID,
		&i.Status,
		&i.HealthCheckAttempts,
		&i.StartedAt,
		&i.HealthyAt,
		&i.StoppedAt,
		&i.Error,
	)
	return i, err
}

const createScalingEvent = `-- name: CreateScalingEvent :one
INSERT INTO scaling_events (
    app_id, environment_id, deployment_id, actor_id, actor_type, event_type,
    from_replicas, to_replicas, placement_strategy, metric_name, metric_value,
    rule_name, message, metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, app_id, environment_id, deployment_id, actor_id, actor_type, event_type, from_replicas, to_replicas, placement_strategy, metric_name, metric_value, rule_name, message, metadata, created_at
`

type CreateScalingEventParams struct {
	AppID             uuid.UUID   `json:"app_id"`
	EnvironmentID     pgtype.UUID `json:"environment_id"`
	DeploymentID      pgtype.UUID `json:"deployment_id"`
	ActorID           pgtype.UUID `json:"actor_id"`
	ActorType         string      `json:"actor_type"`
	EventType         string      `json:"event_type"`
	FromReplicas      int32       `json:"from_replicas"`
	ToReplicas        int32       `json:"to_replicas"`
	PlacementStrategy string      `json:"placement_strategy"`
	MetricName        *string     `json:"metric_name"`
	MetricValue       *float64    `json:"metric_value"`
	RuleName          *string     `json:"rule_name"`
	Message           string      `json:"message"`
	Metadata          []byte      `json:"metadata"`
}

func (q *Queries) CreateScalingEvent(ctx context.Context, arg CreateScalingEventParams) (ScalingEvent, error) {
	row := q.db.QueryRow(ctx, createScalingEvent,
		arg.AppID,
		arg.EnvironmentID,
		arg.DeploymentID,
		arg.ActorID,
		arg.ActorType,
		arg.EventType,
		arg.FromReplicas,
		arg.ToReplicas,
		arg.PlacementStrategy,
		arg.MetricName,
		arg.MetricValue,
		arg.RuleName,
		arg.Message,
		arg.Metadata,
	)
	var i ScalingEvent
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.EnvironmentID,
		&i.DeploymentID,
		&i.ActorID,
		&i.ActorType,
		&i.EventType,
		&i.FromReplicas,
		&i.ToReplicas,
		&i.PlacementStrategy,
		&i.MetricName,
		&i.MetricValue,
		&i.RuleName,
		&i.Message,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveDeployment = `-- name: GetActiveDeployment :one
SELECT id, app_id, environment_id, build_id, strategy, replicas_desired, replicas_ready, env_snapshot, status, started_at, completed_at, error, created_at, logs, platform_domain FROM deployments
WHERE app_id = $1 AND environment_id = $2 AND status = 'healthy'
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveDeploymentParams struct {
	AppID         uuid.UUID `json:"app_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) GetActiveDeployment(ctx context.Context, arg GetActiveDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, getActiveDeployment, arg.AppID, arg.EnvironmentID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.EnvironmentID,
		&i.BuildID,
		&i.Strategy,
		&i.ReplicasDesired,
		&i.ReplicasReady,
		&i.EnvSnapshot,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.CreatedAt,
		&i.Logs,
		&i.PlatformDomain,
	)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, app_id, environment_id, build_id, strategy, replicas_desired, replicas_ready, env_snapshot, status, started_at, completed_at, error, created_at, logs, platform_domain FROM deployments WHERE id = $1
`

func (q *Queries) GetDeployment(ctx context.Context, id uuid.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.EnvironmentID,
		&i.BuildID,
		&i.Strategy,
		&i.ReplicasDesired,
		&i.ReplicasReady,
		&i.EnvSnapshot,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.CreatedAt,
		&i.Logs,
		&i.PlatformDomain,
	)
	return i, err
}

const getDeploymentTarget = `-- name: GetDeploymentTarget :one
SELECT id, deployment_id, server_id, container_id, status, health_check_attempts, started_at, healthy_at, stopped_at, error FROM deployment_targets WHERE id = $1
`

func (q *Queries) GetDeploymentTarget(ctx context.Context, id uuid.UUID) (DeploymentTarget, error) {
	row := q.db.QueryRow(ctx, getDeploymentTarget, id)
	var i DeploymentTarget
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.ServerID,
		&i.ContainerID,
		&i.Status,
		&i.HealthCheckAttempts,
		&i.StartedAt,
		&i.HealthyAt,
		&i.StoppedAt,
		&i.Error,
	)
	return i, err
}

const getLastHealthyDeployment = `-- name: GetLastHealthyDeployment :one
SELECT id, app_id, environment_id, build_id, strategy, replicas_desired, replicas_ready, env_snapshot, status, started_at, completed_at, error, created_at, logs, platform_domain FROM deployments
WHERE app_id = $1 AND environment_id = $2 AND status = 'healthy'
ORDER BY created_at DESC
LIMIT 1
`

type GetLastHealthyDeploymentParams struct {
	AppID         uuid.UUID `json:"app_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) GetLastHealthyDeployment(ctx context.Context, arg GetLastHealthyDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, getLastHealthyDeployment, arg.AppID, arg.EnvironmentID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.EnvironmentID,
		&i.BuildID,
		&i.Strategy,
		&i.ReplicasDesired,
		&i.ReplicasReady,
		&i.EnvSnapshot,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.CreatedAt,
		&i.Logs,
		&i.PlatformDomain,
	)
	return i, err
}

const incrementReplicasReady = `-- name: IncrementReplicasReady :exec
UPDATE deployments SET replicas_ready = replicas_ready + 1 WHERE id = $1
`

func (q *Queries) IncrementReplicasReady(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementReplicasReady, id)
	return err
}

const listActiveContainersByApp = `-- name: ListActiveContainersByApp :many
SELECT dt.container_id, dt.server_id, s.name AS server_name, s.agent_id
FROM deployment_targets dt
JOIN deployments d ON d.id = dt.deployment_id
JOIN servers s ON s.id = dt.server_id
WHERE d.app_id = $1 AND d.status = 'healthy' AND dt.status = 'healthy'
`

type ListActiveContainersByAppRow struct {
	ContainerID *string   `json:"container_id"`
	ServerID    uuid.UUID `json:"server_id"`
	ServerName  string    `json:"server_name"`
	AgentID     *string   `json:"agent_id"`
}

func (q *Queries) ListActiveContainersByApp(ctx context.Context, appID uuid.UUID) ([]ListActiveContainersByAppRow, error) {
	rows, err := q.db.Query(ctx, listActiveContainersByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveContainersByAppRow{}
	for rows.Next() {
		var i ListActiveContainersByAppRow
		if err := rows.Scan(
			&i.ContainerID,
			&i.ServerID,
			&i.ServerName,
			&i.AgentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClusterMembersForScheduling = `-- name: ListClusterMembersForScheduling :many
SELECT
    cm.server_id,
    cm.wireguard_ip,
    s.name AS server_name,
    s.status AS server_status,
    s.public_ip,
    s.agent_id,
    sr.cpu_cores,
    sr.memory_total,
    sr.memory_available,
    COALESCE(COUNT(d.id) FILTER (WHERE dt.status = 'healthy'), 0)::INT AS running_replicas
FROM cluster_members cm
JOIN servers s ON s.id = cm.server_id
LEFT JOIN server_resources sr ON sr.server_id = s.id
LEFT JOIN deployment_targets dt ON dt.server_id = s.id
LEFT JOIN deployments d ON d.id = dt.deployment_id AND d.status = 'healthy'
WHERE cm.cluster_id = $1
GROUP BY cm.server_id, cm.wireguard_ip, s.name, s.status, s.public_ip, s.agent_id,
         sr.cpu_cores, sr.memory_total, sr.memory_available
ORDER BY s.name
`

type ListClusterMembersForSchedulingRow struct {
	ServerID        uuid.UUID  `json:"server_id"`
	WireguardIp     netip.Addr `json:"wireguard_ip"`
	ServerName      string     `json:"server_name"`
	ServerStatus    string     `json:"server_status"`
	PublicIp        netip.Addr `json:"public_ip"`
	AgentID         *string    `json:"agent_id"`
	CpuCores        *int32     `json:"cpu_cores"`
	MemoryTotal     *int64     `json:"memory_total"`
	MemoryAvailable *int64     `json:"memory_available"`
	RunningReplicas int32      `json:"running_replicas"`
}

func (q *Queries) ListClusterMembersForScheduling(ctx context.Context, clusterID uuid.UUID) ([]ListClusterMembersForSchedulingRow, error) {
	rows, err := q.db.Query(ctx, listClusterMembersForScheduling, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClusterMembersForSchedulingRow{}
	for rows.Next() {
		var i ListClusterMembersForSchedulingRow
		if err := rows.Scan(
			&i.ServerID,
			&i.WireguardIp,
			&i.ServerName,
			&i.ServerStatus,
			&i.PublicIp,
			&i.AgentID,
			&i.CpuCores,
			&i.MemoryTotal,
			&i.MemoryAvailable,
			&i.RunningReplicas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentTargets = `-- name: ListDeploymentTargets :many
SELECT dt.id, dt.deployment_id, dt.server_id, dt.container_id, dt.status, dt.health_check_attempts, dt.started_at, dt.healthy_at, dt.stopped_at, dt.error, s.name AS server_name, s.public_ip
FROM deployment_targets dt
JOIN servers s ON s.id = dt.server_id
WHERE dt.deployment_id = $1
ORDER BY dt.started_at ASC
`

type ListDeploymentTargetsRow struct {
	ID                  uuid.UUID          `json:"id"`
	DeploymentID        uuid.UUID          `json:"deployment_id"`
	ServerID            uuid.UUID          `json:"server_id"`
	ContainerID         *string            `json:"container_id"`
	Status              string             `json:"status"`
	HealthCheckAttempts int32              `json:"health_check_attempts"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	HealthyAt           pgtype.Timestamptz `json:"healthy_at"`
	StoppedAt           pgtype.Timestamptz `json:"stopped_at"`
	Error               *string            `json:"error"`
	ServerName          string             `json:"server_name"`
	PublicIp            netip.Addr         `json:"public_ip"`
}

func (q *Queries) ListDeploymentTargets(ctx context.Context, deploymentID uuid.UUID) ([]ListDeploymentTargetsRow, error) {
	rows, err := q.db.Query(ctx, listDeploymentTargets, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeploymentTargetsRow{}
	for rows.Next() {
		var i ListDeploymentTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.ServerID,
			&i.ContainerID,
			&i.Status,
			&i.HealthCheckAttempts,
			&i.StartedAt,
			&i.HealthyAt,
			&i.StoppedAt,
			&i.Error,
			&i.ServerName,
			&i.PublicIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByApp = `-- name: ListDeploymentsByApp :many
SELECT d.id, d.app_id, d.environment_id, d.build_id, d.strategy, d.replicas_desired, d.replicas_ready, d.env_snapshot, d.status, d.started_at, d.completed_at, d.error, d.created_at, d.logs, d.platform_domain, b.commit_sha, b.commit_message, b.image_tag
FROM deployments d
JOIN builds b ON b.id = d.build_id
WHERE d.app_id = $1
ORDER BY d.created_at DESC
LIMIT $2 OFFSET $3
`

type ListDeploymentsByAppParams struct {
	AppID  uuid.UUID `json:"app_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListDeploymentsByAppRow struct {
	ID              uuid.UUID          `json:"id"`
	AppID           uuid.UUID          `json:"app_id"`
	EnvironmentID   uuid.UUID          `json:"environment_id"`
	BuildID         uuid.UUID          `json:"build_id"`
	Strategy        string             `json:"strategy"`
	ReplicasDesired int32              `json:"replicas_desired"`
	ReplicasReady   int32              `json:"replicas_ready"`
	EnvSnapshot     []byte             `json:"env_snapshot"`
	Status          string             `json:"status"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Error           *string            `json:"error"`
	CreatedAt       time.Time          `json:"created_at"`
	Logs            string             `json:"logs"`
	PlatformDomain  string             `json:"platform_domain"`
	CommitSha       string             `json:"commit_sha"`
	CommitMessage   string             `json:"commit_message"`
	ImageTag        string             `json:"image_tag"`
}

func (q *Queries) ListDeploymentsByApp(ctx context.Context, arg ListDeploymentsByAppParams) ([]ListDeploymentsByAppRow, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByApp, arg.AppID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeploymentsByAppRow{}
	for rows.Next() {
		var i ListDeploymentsByAppRow
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.EnvironmentID,
			&i.BuildID,
			&i.Strategy,
			&i.ReplicasDesired,
			&i.ReplicasReady,
			&i.EnvSnapshot,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
			&i.CreatedAt,
			&i.Logs,
			&i.PlatformDomain,
			&i.CommitSha,
			&i.CommitMessage,
			&i.ImageTag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScalingEventsByApp = `-- name: ListScalingEventsByApp :many
SELECT id, app_id, environment_id, deployment_id, actor_id, actor_type, event_type, from_replicas, to_replicas, placement_strategy, metric_name, metric_value, rule_name, message, metadata, created_at FROM scaling_events
WHERE app_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListScalingEventsByAppParams struct {
	AppID  uuid.UUID `json:"app_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListScalingEventsByApp(ctx context.Context, arg ListScalingEventsByAppParams) ([]ScalingEvent, error) {
	rows, err := q.db.Query(ctx, listScalingEventsByApp, arg.AppID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScalingEvent{}
	for rows.Next() {
		var i ScalingEvent
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.EnvironmentID,
			&i.DeploymentID,
			&i.ActorID,
			&i.ActorType,
			&i.EventType,
			&i.FromReplicas,
			&i.ToReplicas,
			&i.PlacementStrategy,
			&i.MetricName,
			&i.MetricValue,
			&i.RuleName,
			&i.Message,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeploymentPlatformDomain = `-- name: SetDeploymentPlatformDomain :exec
UPDATE deployments SET platform_domain = $2 WHERE id = $1
`

type SetDeploymentPlatformDomainParams struct {
	ID             uuid.UUID `json:"id"`
	PlatformDomain string    `json:"platform_domain"`
}

func (q *Queries) SetDeploymentPlatformDomain(ctx context.Context, arg SetDeploymentPlatformDomainParams) error {
	_, err := q.db.Exec(ctx, setDeploymentPlatformDomain, arg.ID, arg.PlatformDomain)
	return err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
UPDATE deployments
SET status = $2, started_at = COALESCE(started_at, $3), error = $4
WHERE id = $1
`

type UpdateDeploymentStatusParams struct {
	ID        uuid.UUID          `json:"id"`
	Status    string             `json:"status"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	Error     *string            `json:"error"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.db.Exec(ctx, updateDeploymentStatus,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.Error,
	)
	return err
}

const updateDeploymentTargetStatus = `-- name: UpdateDeploymentTargetStatus :exec
UPDATE deployment_targets
SET status = $2, container_id = COALESCE($3, container_id),
    started_at = COALESCE(started_at, $4),
    healthy_at = $5, stopped_at = $6,
    health_check_attempts = $7, error = $8
WHERE id = $1
`

type UpdateDeploymentTargetStatusParams struct {
	ID                  uuid.UUID          `json:"id"`
	Status              string             `json:"status"`
	ContainerID         *string            `json:"container_id"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	HealthyAt           pgtype.Timestamptz `json:"healthy_at"`
	StoppedAt           pgtype.Timestamptz `json:"stopped_at"`
	HealthCheckAttempts int32              `json:"health_check_attempts"`
	Error               *string            `json:"error"`
}

func (q *Queries) UpdateDeploymentTargetStatus(ctx context.Context, arg UpdateDeploymentTargetStatusParams) error {
	_, err := q.db.Exec(ctx, updateDeploymentTargetStatus,
		arg.ID,
		arg.Status,
		arg.ContainerID,
		arg.StartedAt,
		arg.HealthyAt,
		arg.StoppedAt,
		arg.HealthCheckAttempts,
		arg.Error,
	)
	return err
}
