// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environments.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (project_id, name, slug, is_production)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, name, slug, is_production, created_at
`

type CreateEnvironmentParams struct {
	ProjectID    uuid.UUID `json:"project_id"`
	Name         string    `json:"name"`
	Slug         string    `json:"slug"`
	IsProduction bool      `json:"is_production"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment,
		arg.ProjectID,
		arg.Name,
		arg.Slug,
		arg.IsProduction,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.IsProduction,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEnvironment = `-- name: DeleteEnvironment :exec
DELETE FROM environments WHERE id = $1 AND is_production = false
`

func (q *Queries) DeleteEnvironment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnvironment, id)
	return err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, project_id, name, slug, is_production, created_at FROM environments WHERE id = $1
`

func (q *Queries) GetEnvironment(ctx context.Context, id uuid.UUID) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironment, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.IsProduction,
		&i.CreatedAt,
	)
	return i, err
}

const getEnvironmentBySlug = `-- name: GetEnvironmentBySlug :one
SELECT id, project_id, name, slug, is_production, created_at FROM environments WHERE project_id = $1 AND slug = $2
`

type GetEnvironmentBySlugParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Slug      string    `json:"slug"`
}

func (q *Queries) GetEnvironmentBySlug(ctx context.Context, arg GetEnvironmentBySlugParams) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentBySlug, arg.ProjectID, arg.Slug)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.IsProduction,
		&i.CreatedAt,
	)
	return i, err
}

const listEnvironmentsByProject = `-- name: ListEnvironmentsByProject :many
SELECT id, project_id, name, slug, is_production, created_at FROM environments
WHERE project_id = $1
ORDER BY is_production DESC, name ASC
`

func (q *Queries) ListEnvironmentsByProject(ctx context.Context, projectID uuid.UUID) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Slug,
			&i.IsProduction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
