// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github_webhook_events.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createWebhookEvent = `-- name: CreateWebhookEvent :one
INSERT INTO github_webhook_events (github_app_id, event_type, action, delivery_id, payload)
VALUES ($1, $2, $3, $4, $5) RETURNING id, github_app_id, event_type, action, delivery_id, payload, processed, created_at
`

type CreateWebhookEventParams struct {
	GithubAppID uuid.UUID `json:"github_app_id"`
	EventType   string    `json:"event_type"`
	Action      *string   `json:"action"`
	DeliveryID  string    `json:"delivery_id"`
	Payload     []byte    `json:"payload"`
}

func (q *Queries) CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) (GithubWebhookEvent, error) {
	row := q.db.QueryRow(ctx, createWebhookEvent,
		arg.GithubAppID,
		arg.EventType,
		arg.Action,
		arg.DeliveryID,
		arg.Payload,
	)
	var i GithubWebhookEvent
	err := row.Scan(
		&i.ID,
		&i.GithubAppID,
		&i.EventType,
		&i.Action,
		&i.DeliveryID,
		&i.Payload,
		&i.Processed,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldWebhookEvents = `-- name: DeleteOldWebhookEvents :exec
DELETE FROM github_webhook_events WHERE created_at < $1
`

func (q *Queries) DeleteOldWebhookEvents(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteOldWebhookEvents, createdAt)
	return err
}

const getWebhookEventByDeliveryID = `-- name: GetWebhookEventByDeliveryID :one
SELECT id, github_app_id, event_type, action, delivery_id, payload, processed, created_at FROM github_webhook_events WHERE delivery_id = $1
`

func (q *Queries) GetWebhookEventByDeliveryID(ctx context.Context, deliveryID string) (GithubWebhookEvent, error) {
	row := q.db.QueryRow(ctx, getWebhookEventByDeliveryID, deliveryID)
	var i GithubWebhookEvent
	err := row.Scan(
		&i.ID,
		&i.GithubAppID,
		&i.EventType,
		&i.Action,
		&i.DeliveryID,
		&i.Payload,
		&i.Processed,
		&i.CreatedAt,
	)
	return i, err
}

const listWebhookEvents = `-- name: ListWebhookEvents :many
SELECT id, github_app_id, event_type, action, delivery_id, payload, processed, created_at FROM github_webhook_events
WHERE github_app_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhookEventsParams struct {
	GithubAppID uuid.UUID `json:"github_app_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListWebhookEvents(ctx context.Context, arg ListWebhookEventsParams) ([]GithubWebhookEvent, error) {
	rows, err := q.db.Query(ctx, listWebhookEvents, arg.GithubAppID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubWebhookEvent{}
	for rows.Next() {
		var i GithubWebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.GithubAppID,
			&i.EventType,
			&i.Action,
			&i.DeliveryID,
			&i.Payload,
			&i.Processed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEventsByType = `-- name: ListWebhookEventsByType :many
SELECT id, github_app_id, event_type, action, delivery_id, payload, processed, created_at FROM github_webhook_events
WHERE github_app_id = $1 AND event_type = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListWebhookEventsByTypeParams struct {
	GithubAppID uuid.UUID `json:"github_app_id"`
	EventType   string    `json:"event_type"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListWebhookEventsByType(ctx context.Context, arg ListWebhookEventsByTypeParams) ([]GithubWebhookEvent, error) {
	rows, err := q.db.Query(ctx, listWebhookEventsByType,
		arg.GithubAppID,
		arg.EventType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubWebhookEvent{}
	for rows.Next() {
		var i GithubWebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.GithubAppID,
			&i.EventType,
			&i.Action,
			&i.DeliveryID,
			&i.Payload,
			&i.Processed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookEventProcessed = `-- name: MarkWebhookEventProcessed :exec
UPDATE github_webhook_events SET processed = true WHERE id = $1
`

func (q *Queries) MarkWebhookEventProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markWebhookEventProcessed, id)
	return err
}
