// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github_apps.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGitHubApp = `-- name: CreateGitHubApp :one
INSERT INTO github_apps (team_id, app_id, app_name, app_slug, client_id, client_secret, private_key, webhook_secret, html_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, team_id, app_id, app_name, app_slug, client_id, client_secret, private_key, webhook_secret, html_url, created_at, updated_at
`

type CreateGitHubAppParams struct {
	TeamID        uuid.UUID `json:"team_id"`
	AppID         int64     `json:"app_id"`
	AppName       string    `json:"app_name"`
	AppSlug       string    `json:"app_slug"`
	ClientID      string    `json:"client_id"`
	ClientSecret  []byte    `json:"client_secret"`
	PrivateKey    []byte    `json:"private_key"`
	WebhookSecret []byte    `json:"webhook_secret"`
	HtmlUrl       string    `json:"html_url"`
}

func (q *Queries) CreateGitHubApp(ctx context.Context, arg CreateGitHubAppParams) (GithubApp, error) {
	row := q.db.QueryRow(ctx, createGitHubApp,
		arg.TeamID,
		arg.AppID,
		arg.AppName,
		arg.AppSlug,
		arg.ClientID,
		arg.ClientSecret,
		arg.PrivateKey,
		arg.WebhookSecret,
		arg.HtmlUrl,
	)
	var i GithubApp
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.AppID,
		&i.AppName,
		&i.AppSlug,
		&i.ClientID,
		&i.ClientSecret,
		&i.PrivateKey,
		&i.WebhookSecret,
		&i.HtmlUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGitHubInstallation = `-- name: CreateGitHubInstallation :one
INSERT INTO github_installations (github_app_id, installation_id, account_login, account_type, target_type)
VALUES ($1, $2, $3, $4, $5) RETURNING id, github_app_id, installation_id, account_login, account_type, target_type, suspended_at, created_at, updated_at
`

type CreateGitHubInstallationParams struct {
	GithubAppID    uuid.UUID `json:"github_app_id"`
	InstallationID int64     `json:"installation_id"`
	AccountLogin   string    `json:"account_login"`
	AccountType    string    `json:"account_type"`
	TargetType     string    `json:"target_type"`
}

func (q *Queries) CreateGitHubInstallation(ctx context.Context, arg CreateGitHubInstallationParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, createGitHubInstallation,
		arg.GithubAppID,
		arg.InstallationID,
		arg.AccountLogin,
		arg.AccountType,
		arg.TargetType,
	)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.GithubAppID,
		&i.InstallationID,
		&i.AccountLogin,
		&i.AccountType,
		&i.TargetType,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGitHubApp = `-- name: DeleteGitHubApp :exec
DELETE FROM github_apps WHERE id = $1 AND team_id = $2
`

type DeleteGitHubAppParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) DeleteGitHubApp(ctx context.Context, arg DeleteGitHubAppParams) error {
	_, err := q.db.Exec(ctx, deleteGitHubApp, arg.ID, arg.TeamID)
	return err
}

const deleteGitHubInstallation = `-- name: DeleteGitHubInstallation :exec
DELETE FROM github_installations WHERE github_app_id = $1 AND installation_id = $2
`

type DeleteGitHubInstallationParams struct {
	GithubAppID    uuid.UUID `json:"github_app_id"`
	InstallationID int64     `json:"installation_id"`
}

func (q *Queries) DeleteGitHubInstallation(ctx context.Context, arg DeleteGitHubInstallationParams) error {
	_, err := q.db.Exec(ctx, deleteGitHubInstallation, arg.GithubAppID, arg.InstallationID)
	return err
}

const getGitHubAppByAppID = `-- name: GetGitHubAppByAppID :one
SELECT id, team_id, app_id, app_name, app_slug, client_id, client_secret, private_key, webhook_secret, html_url, created_at, updated_at FROM github_apps WHERE app_id = $1
`

func (q *Queries) GetGitHubAppByAppID(ctx context.Context, appID int64) (GithubApp, error) {
	row := q.db.QueryRow(ctx, getGitHubAppByAppID, appID)
	var i GithubApp
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.AppID,
		&i.AppName,
		&i.AppSlug,
		&i.ClientID,
		&i.ClientSecret,
		&i.PrivateKey,
		&i.WebhookSecret,
		&i.HtmlUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGitHubAppByID = `-- name: GetGitHubAppByID :one
SELECT id, team_id, app_id, app_name, app_slug, client_id, client_secret, private_key, webhook_secret, html_url, created_at, updated_at FROM github_apps WHERE id = $1
`

func (q *Queries) GetGitHubAppByID(ctx context.Context, id uuid.UUID) (GithubApp, error) {
	row := q.db.QueryRow(ctx, getGitHubAppByID, id)
	var i GithubApp
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.AppID,
		&i.AppName,
		&i.AppSlug,
		&i.ClientID,
		&i.ClientSecret,
		&i.PrivateKey,
		&i.WebhookSecret,
		&i.HtmlUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGitHubAppByTeam = `-- name: GetGitHubAppByTeam :one
SELECT id, team_id, app_id, app_name, app_slug, client_id, client_secret, private_key, webhook_secret, html_url, created_at, updated_at FROM github_apps WHERE team_id = $1
`

func (q *Queries) GetGitHubAppByTeam(ctx context.Context, teamID uuid.UUID) (GithubApp, error) {
	row := q.db.QueryRow(ctx, getGitHubAppByTeam, teamID)
	var i GithubApp
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.AppID,
		&i.AppName,
		&i.AppSlug,
		&i.ClientID,
		&i.ClientSecret,
		&i.PrivateKey,
		&i.WebhookSecret,
		&i.HtmlUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGitHubInstallation = `-- name: GetGitHubInstallation :one
SELECT id, github_app_id, installation_id, account_login, account_type, target_type, suspended_at, created_at, updated_at FROM github_installations WHERE github_app_id = $1 AND installation_id = $2
`

type GetGitHubInstallationParams struct {
	GithubAppID    uuid.UUID `json:"github_app_id"`
	InstallationID int64     `json:"installation_id"`
}

func (q *Queries) GetGitHubInstallation(ctx context.Context, arg GetGitHubInstallationParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, getGitHubInstallation, arg.GithubAppID, arg.InstallationID)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.GithubAppID,
		&i.InstallationID,
		&i.AccountLogin,
		&i.AccountType,
		&i.TargetType,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGitHubInstallations = `-- name: ListGitHubInstallations :many
SELECT id, github_app_id, installation_id, account_login, account_type, target_type, suspended_at, created_at, updated_at FROM github_installations WHERE github_app_id = $1 ORDER BY created_at
`

func (q *Queries) ListGitHubInstallations(ctx context.Context, githubAppID uuid.UUID) ([]GithubInstallation, error) {
	rows, err := q.db.Query(ctx, listGitHubInstallations, githubAppID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubInstallation{}
	for rows.Next() {
		var i GithubInstallation
		if err := rows.Scan(
			&i.ID,
			&i.GithubAppID,
			&i.InstallationID,
			&i.AccountLogin,
			&i.AccountType,
			&i.TargetType,
			&i.SuspendedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGitHubInstallationSuspended = `-- name: UpdateGitHubInstallationSuspended :exec
UPDATE github_installations SET suspended_at = $3, updated_at = now()
WHERE github_app_id = $1 AND installation_id = $2
`

type UpdateGitHubInstallationSuspendedParams struct {
	GithubAppID    uuid.UUID          `json:"github_app_id"`
	InstallationID int64              `json:"installation_id"`
	SuspendedAt    pgtype.Timestamptz `json:"suspended_at"`
}

func (q *Queries) UpdateGitHubInstallationSuspended(ctx context.Context, arg UpdateGitHubInstallationSuspendedParams) error {
	_, err := q.db.Exec(ctx, updateGitHubInstallationSuspended, arg.GithubAppID, arg.InstallationID, arg.SuspendedAt)
	return err
}
