// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO team_invites (team_id, email, role, token, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, team_id, email, role, token, invited_by, expires_at, created_at
`

type CreateInviteParams struct {
	TeamID    uuid.UUID `json:"team_id"`
	Email     string    `json:"email"`
	Role      string    `json:"role"`
	Token     string    `json:"token"`
	InvitedBy uuid.UUID `json:"invited_by"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (TeamInvite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.TeamID,
		arg.Email,
		arg.Role,
		arg.Token,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i TeamInvite
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredInvites = `-- name: DeleteExpiredInvites :execrows
DELETE FROM team_invites WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredInvites(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredInvites)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM team_invites WHERE id = $1
`

func (q *Queries) DeleteInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvite, id)
	return err
}

const deleteInviteByToken = `-- name: DeleteInviteByToken :exec
DELETE FROM team_invites WHERE token = $1
`

func (q *Queries) DeleteInviteByToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteInviteByToken, token)
	return err
}

const getInviteByToken = `-- name: GetInviteByToken :one
SELECT id, team_id, email, role, token, invited_by, expires_at, created_at FROM team_invites WHERE token = $1 AND expires_at > now()
`

func (q *Queries) GetInviteByToken(ctx context.Context, token string) (TeamInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByToken, token)
	var i TeamInvite
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInvitesByTeam = `-- name: ListInvitesByTeam :many
SELECT ti.id, ti.team_id, ti.email, ti.role, ti.token, ti.invited_by, ti.expires_at, ti.created_at, u.name AS inviter_name FROM team_invites ti
JOIN users u ON ti.invited_by = u.id
WHERE ti.team_id = $1 AND ti.expires_at > now()
ORDER BY ti.created_at DESC
`

type ListInvitesByTeamRow struct {
	ID          uuid.UUID `json:"id"`
	TeamID      uuid.UUID `json:"team_id"`
	Email       string    `json:"email"`
	Role        string    `json:"role"`
	Token       string    `json:"token"`
	InvitedBy   uuid.UUID `json:"invited_by"`
	ExpiresAt   time.Time `json:"expires_at"`
	CreatedAt   time.Time `json:"created_at"`
	InviterName string    `json:"inviter_name"`
}

func (q *Queries) ListInvitesByTeam(ctx context.Context, teamID uuid.UUID) ([]ListInvitesByTeamRow, error) {
	rows, err := q.db.Query(ctx, listInvitesByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitesByTeamRow{}
	for rows.Next() {
		var i ListInvitesByTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Email,
			&i.Role,
			&i.Token,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.InviterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
