// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memberships.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countOwners = `-- name: CountOwners :one
SELECT COUNT(*) FROM team_memberships WHERE team_id = $1 AND role = 'owner'
`

func (q *Queries) CountOwners(ctx context.Context, teamID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwners, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO team_memberships (team_id, user_id, role) VALUES ($1, $2, $3) RETURNING id, team_id, user_id, role, created_at
`

type CreateMembershipParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.TeamID, arg.UserID, arg.Role)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM team_memberships WHERE team_id = $1 AND user_id = $2
`

type DeleteMembershipParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.TeamID, arg.UserID)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT id, team_id, user_id, role, created_at FROM team_memberships WHERE team_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.TeamID, arg.UserID)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listMembersByTeam = `-- name: ListMembersByTeam :many
SELECT tm.id, tm.team_id, tm.user_id, tm.role, tm.created_at, u.email, u.name AS user_name FROM team_memberships tm
JOIN users u ON tm.user_id = u.id
WHERE tm.team_id = $1
ORDER BY tm.created_at
`

type ListMembersByTeamRow struct {
	ID        uuid.UUID `json:"id"`
	TeamID    uuid.UUID `json:"team_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`
	UserName  string    `json:"user_name"`
}

func (q *Queries) ListMembersByTeam(ctx context.Context, teamID uuid.UUID) ([]ListMembersByTeamRow, error) {
	rows, err := q.db.Query(ctx, listMembersByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersByTeamRow{}
	for rows.Next() {
		var i ListMembersByTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
UPDATE team_memberships SET role = $3 WHERE team_id = $1 AND user_id = $2
`

type UpdateMemberRoleParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateMemberRole, arg.TeamID, arg.UserID, arg.Role)
	return err
}
