// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mesh_events.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMeshEvent = `-- name: CreateMeshEvent :one
INSERT INTO mesh_events (cluster_id, event_type, member_id, details)
VALUES ($1, $2, $3, $4) RETURNING id, cluster_id, event_type, member_id, details, created_at
`

type CreateMeshEventParams struct {
	ClusterID uuid.UUID       `json:"cluster_id"`
	EventType string          `json:"event_type"`
	MemberID  pgtype.UUID     `json:"member_id"`
	Details   json.RawMessage `json:"details"`
}

func (q *Queries) CreateMeshEvent(ctx context.Context, arg CreateMeshEventParams) (MeshEvent, error) {
	row := q.db.QueryRow(ctx, createMeshEvent,
		arg.ClusterID,
		arg.EventType,
		arg.MemberID,
		arg.Details,
	)
	var i MeshEvent
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.EventType,
		&i.MemberID,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const listMeshEvents = `-- name: ListMeshEvents :many
SELECT id, cluster_id, event_type, member_id, details, created_at FROM mesh_events
WHERE cluster_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMeshEventsParams struct {
	ClusterID uuid.UUID `json:"cluster_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListMeshEvents(ctx context.Context, arg ListMeshEventsParams) ([]MeshEvent, error) {
	rows, err := q.db.Query(ctx, listMeshEvents, arg.ClusterID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MeshEvent{}
	for rows.Next() {
		var i MeshEvent
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.EventType,
			&i.MemberID,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeshEventsByType = `-- name: ListMeshEventsByType :many
SELECT id, cluster_id, event_type, member_id, details, created_at FROM mesh_events
WHERE cluster_id = $1 AND event_type = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListMeshEventsByTypeParams struct {
	ClusterID uuid.UUID `json:"cluster_id"`
	EventType string    `json:"event_type"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListMeshEventsByType(ctx context.Context, arg ListMeshEventsByTypeParams) ([]MeshEvent, error) {
	rows, err := q.db.Query(ctx, listMeshEventsByType,
		arg.ClusterID,
		arg.EventType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MeshEvent{}
	for rows.Next() {
		var i MeshEvent
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.EventType,
			&i.MemberID,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
