// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID         uuid.UUID          `json:"id"`
	TeamID     uuid.UUID          `json:"team_id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	TokenHash  string             `json:"token_hash"`
	Scopes     []string           `json:"scopes"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

type AuditLog struct {
	ID           uuid.UUID       `json:"id"`
	TeamID       pgtype.UUID     `json:"team_id"`
	ActorID      pgtype.UUID     `json:"actor_id"`
	ActorType    string          `json:"actor_type"`
	Action       string          `json:"action"`
	ResourceType string          `json:"resource_type"`
	ResourceID   pgtype.UUID     `json:"resource_id"`
	Metadata     json.RawMessage `json:"metadata"`
	IpAddress    *netip.Addr     `json:"ip_address"`
	CreatedAt    time.Time       `json:"created_at"`
}

type ProvisioningJob struct {
	ID          uuid.UUID          `json:"id"`
	ServerID    uuid.UUID          `json:"server_id"`
	Components  []string           `json:"components"`
	Status      string             `json:"status"`
	Logs        string             `json:"logs"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Error       *string            `json:"error"`
	CreatedAt   time.Time          `json:"created_at"`
}

type Server struct {
	ID         uuid.UUID          `json:"id"`
	TeamID     uuid.UUID          `json:"team_id"`
	AgentID    *string            `json:"agent_id"`
	Name       string             `json:"name"`
	Hostname   string             `json:"hostname"`
	PublicIp   netip.Addr         `json:"public_ip"`
	SshPort    int32              `json:"ssh_port"`
	SshUser    string             `json:"ssh_user"`
	Os         *string            `json:"os"`
	OsVersion  *string            `json:"os_version"`
	Arch       *string            `json:"arch"`
	Status     string             `json:"status"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  time.Time          `json:"created_at"`
	UpdatedAt  time.Time          `json:"updated_at"`
}

type ServerResource struct {
	ServerID          uuid.UUID       `json:"server_id"`
	CpuModel          *string         `json:"cpu_model"`
	CpuCores          *int32          `json:"cpu_cores"`
	MemoryTotal       *int64          `json:"memory_total"`
	MemoryAvailable   *int64          `json:"memory_available"`
	KernelVersion     *string         `json:"kernel_version"`
	DockerVersion     *string         `json:"docker_version"`
	Disks             json.RawMessage `json:"disks"`
	NetworkInterfaces json.RawMessage `json:"network_interfaces"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type ServerSshKey struct {
	ServerID uuid.UUID `json:"server_id"`
	SshKeyID uuid.UUID `json:"ssh_key_id"`
}

type ServerTag struct {
	ID       uuid.UUID `json:"id"`
	ServerID uuid.UUID `json:"server_id"`
	Key      string    `json:"key"`
	Value    string    `json:"value"`
}

type SshKey struct {
	ID                  uuid.UUID `json:"id"`
	TeamID              uuid.UUID `json:"team_id"`
	Name                string    `json:"name"`
	PublicKey           string    `json:"public_key"`
	PrivateKeyEncrypted []byte    `json:"private_key_encrypted"`
	KeyType             string    `json:"key_type"`
	Fingerprint         string    `json:"fingerprint"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

type Team struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TeamInvite struct {
	ID        uuid.UUID `json:"id"`
	TeamID    uuid.UUID `json:"team_id"`
	Email     string    `json:"email"`
	Role      string    `json:"role"`
	Token     string    `json:"token"`
	InvitedBy uuid.UUID `json:"invited_by"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type TeamMembership struct {
	ID        uuid.UUID `json:"id"`
	TeamID    uuid.UUID `json:"team_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID                   uuid.UUID          `json:"id"`
	Email                string             `json:"email"`
	PasswordHash         string             `json:"password_hash"`
	Name                 string             `json:"name"`
	EmailVerified        bool               `json:"email_verified"`
	EmailVerifyToken     *string            `json:"email_verify_token"`
	EmailVerifyExpires   pgtype.Timestamptz `json:"email_verify_expires"`
	PasswordResetToken   *string            `json:"password_reset_token"`
	PasswordResetExpires pgtype.Timestamptz `json:"password_reset_expires"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
}
