// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID         uuid.UUID          `json:"id"`
	TeamID     uuid.UUID          `json:"team_id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	TokenHash  string             `json:"token_hash"`
	Scopes     []string           `json:"scopes"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

type AuditLog struct {
	ID           uuid.UUID       `json:"id"`
	TeamID       pgtype.UUID     `json:"team_id"`
	ActorID      pgtype.UUID     `json:"actor_id"`
	ActorType    string          `json:"actor_type"`
	Action       string          `json:"action"`
	ResourceType string          `json:"resource_type"`
	ResourceID   pgtype.UUID     `json:"resource_id"`
	Metadata     json.RawMessage `json:"metadata"`
	IpAddress    *netip.Addr     `json:"ip_address"`
	CreatedAt    time.Time       `json:"created_at"`
}

type Cluster struct {
	ID          uuid.UUID    `json:"id"`
	TeamID      uuid.UUID    `json:"team_id"`
	Name        string       `json:"name"`
	Slug        string       `json:"slug"`
	Description string       `json:"description"`
	Region      string       `json:"region"`
	Cidr        netip.Prefix `json:"cidr"`
	Status      string       `json:"status"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
}

type ClusterMember struct {
	ID                 uuid.UUID  `json:"id"`
	ClusterID          uuid.UUID  `json:"cluster_id"`
	ServerID           uuid.UUID  `json:"server_id"`
	WireguardIp        netip.Addr `json:"wireguard_ip"`
	WireguardPublicKey string     `json:"wireguard_public_key"`
	WireguardEndpoint  string     `json:"wireguard_endpoint"`
	ListenPort         int32      `json:"listen_port"`
	JoinedAt           time.Time  `json:"joined_at"`
}

type GithubApp struct {
	ID            uuid.UUID `json:"id"`
	TeamID        uuid.UUID `json:"team_id"`
	AppID         int64     `json:"app_id"`
	AppName       string    `json:"app_name"`
	AppSlug       string    `json:"app_slug"`
	ClientID      string    `json:"client_id"`
	ClientSecret  []byte    `json:"client_secret"`
	PrivateKey    []byte    `json:"private_key"`
	WebhookSecret []byte    `json:"webhook_secret"`
	HtmlUrl       string    `json:"html_url"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type GithubInstallation struct {
	ID             uuid.UUID          `json:"id"`
	GithubAppID    uuid.UUID          `json:"github_app_id"`
	InstallationID int64              `json:"installation_id"`
	AccountLogin   string             `json:"account_login"`
	AccountType    string             `json:"account_type"`
	TargetType     string             `json:"target_type"`
	SuspendedAt    pgtype.Timestamptz `json:"suspended_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

type GithubWebhookEvent struct {
	ID          uuid.UUID `json:"id"`
	GithubAppID uuid.UUID `json:"github_app_id"`
	EventType   string    `json:"event_type"`
	Action      *string   `json:"action"`
	DeliveryID  string    `json:"delivery_id"`
	Payload     []byte    `json:"payload"`
	Processed   bool      `json:"processed"`
	CreatedAt   time.Time `json:"created_at"`
}

type MeshEvent struct {
	ID        uuid.UUID       `json:"id"`
	ClusterID uuid.UUID       `json:"cluster_id"`
	EventType string          `json:"event_type"`
	MemberID  pgtype.UUID     `json:"member_id"`
	Details   json.RawMessage `json:"details"`
	CreatedAt time.Time       `json:"created_at"`
}

type ProvisioningJob struct {
	ID          uuid.UUID          `json:"id"`
	ServerID    uuid.UUID          `json:"server_id"`
	Components  []string           `json:"components"`
	Status      string             `json:"status"`
	Logs        string             `json:"logs"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Error       *string            `json:"error"`
	CreatedAt   time.Time          `json:"created_at"`
}

type RegistryCredential struct {
	ID                 uuid.UUID          `json:"id"`
	TeamID             uuid.UUID          `json:"team_id"`
	Name               string             `json:"name"`
	RegistryType       string             `json:"registry_type"`
	RegistryUrl        string             `json:"registry_url"`
	Username           string             `json:"username"`
	Password           []byte             `json:"password"`
	Region             *string            `json:"region"`
	AwsAccessKeyID     *string            `json:"aws_access_key_id"`
	AwsSecretAccessKey []byte             `json:"aws_secret_access_key"`
	ValidatedAt        pgtype.Timestamptz `json:"validated_at"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

type Secret struct {
	ID             uuid.UUID          `json:"id"`
	TeamID         uuid.UUID          `json:"team_id"`
	Environment    string             `json:"environment"`
	Key            string             `json:"key"`
	EncryptedValue []byte             `json:"encrypted_value"`
	Version        int32              `json:"version"`
	RevealedAt     pgtype.Timestamptz `json:"revealed_at"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	UpdatedBy      pgtype.UUID        `json:"updated_by"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

type SecretAccessLog struct {
	ID        uuid.UUID   `json:"id"`
	SecretID  uuid.UUID   `json:"secret_id"`
	TeamID    uuid.UUID   `json:"team_id"`
	ActorID   pgtype.UUID `json:"actor_id"`
	ActorType string      `json:"actor_type"`
	Action    string      `json:"action"`
	IpAddress *netip.Addr `json:"ip_address"`
	CreatedAt time.Time   `json:"created_at"`
}

type Server struct {
	ID         uuid.UUID          `json:"id"`
	TeamID     uuid.UUID          `json:"team_id"`
	AgentID    *string            `json:"agent_id"`
	Name       string             `json:"name"`
	Hostname   string             `json:"hostname"`
	PublicIp   netip.Addr         `json:"public_ip"`
	SshPort    int32              `json:"ssh_port"`
	SshUser    string             `json:"ssh_user"`
	Os         *string            `json:"os"`
	OsVersion  *string            `json:"os_version"`
	Arch       *string            `json:"arch"`
	Status     string             `json:"status"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  time.Time          `json:"created_at"`
	UpdatedAt  time.Time          `json:"updated_at"`
	ClusterID  pgtype.UUID        `json:"cluster_id"`
}

type ServerResource struct {
	ServerID          uuid.UUID       `json:"server_id"`
	CpuModel          *string         `json:"cpu_model"`
	CpuCores          *int32          `json:"cpu_cores"`
	MemoryTotal       *int64          `json:"memory_total"`
	MemoryAvailable   *int64          `json:"memory_available"`
	KernelVersion     *string         `json:"kernel_version"`
	DockerVersion     *string         `json:"docker_version"`
	Disks             json.RawMessage `json:"disks"`
	NetworkInterfaces json.RawMessage `json:"network_interfaces"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type ServerSshKey struct {
	ServerID uuid.UUID `json:"server_id"`
	SshKeyID uuid.UUID `json:"ssh_key_id"`
}

type ServerTag struct {
	ID       uuid.UUID `json:"id"`
	ServerID uuid.UUID `json:"server_id"`
	Key      string    `json:"key"`
	Value    string    `json:"value"`
}

type SshKey struct {
	ID                  uuid.UUID `json:"id"`
	TeamID              uuid.UUID `json:"team_id"`
	Name                string    `json:"name"`
	PublicKey           string    `json:"public_key"`
	PrivateKeyEncrypted []byte    `json:"private_key_encrypted"`
	KeyType             string    `json:"key_type"`
	Fingerprint         string    `json:"fingerprint"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

type Team struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TeamInvite struct {
	ID        uuid.UUID `json:"id"`
	TeamID    uuid.UUID `json:"team_id"`
	Email     string    `json:"email"`
	Role      string    `json:"role"`
	Token     string    `json:"token"`
	InvitedBy uuid.UUID `json:"invited_by"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type TeamMembership struct {
	ID        uuid.UUID `json:"id"`
	TeamID    uuid.UUID `json:"team_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID                   uuid.UUID          `json:"id"`
	Email                string             `json:"email"`
	PasswordHash         string             `json:"password_hash"`
	Name                 string             `json:"name"`
	EmailVerified        bool               `json:"email_verified"`
	EmailVerifyToken     *string            `json:"email_verify_token"`
	EmailVerifyExpires   pgtype.Timestamptz `json:"email_verify_expires"`
	PasswordResetToken   *string            `json:"password_reset_token"`
	PasswordResetExpires pgtype.Timestamptz `json:"password_reset_expires"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
}

type WireguardPeer struct {
	ID              uuid.UUID          `json:"id"`
	MemberID        uuid.UUID          `json:"member_id"`
	PeerMemberID    uuid.UUID          `json:"peer_member_id"`
	Status          string             `json:"status"`
	LastHandshakeAt pgtype.Timestamptz `json:"last_handshake_at"`
	LastCheckAt     pgtype.Timestamptz `json:"last_check_at"`
	RttMs           *int32             `json:"rtt_ms"`
	CreatedAt       time.Time          `json:"created_at"`
}
