// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: observability.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAlertEvent = `-- name: CreateAlertEvent :one
INSERT INTO alert_events (rule_id, team_id, scope_type, scope_id, state, metric_value, threshold, message, notified_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, rule_id, team_id, scope_type, scope_id, state, metric_value, threshold, message, notified_at, created_at
`

type CreateAlertEventParams struct {
	RuleID      uuid.UUID          `json:"rule_id"`
	TeamID      uuid.UUID          `json:"team_id"`
	ScopeType   string             `json:"scope_type"`
	ScopeID     uuid.UUID          `json:"scope_id"`
	State       string             `json:"state"`
	MetricValue *float64           `json:"metric_value"`
	Threshold   float64            `json:"threshold"`
	Message     string             `json:"message"`
	NotifiedAt  pgtype.Timestamptz `json:"notified_at"`
}

func (q *Queries) CreateAlertEvent(ctx context.Context, arg CreateAlertEventParams) (AlertEvent, error) {
	row := q.db.QueryRow(ctx, createAlertEvent,
		arg.RuleID,
		arg.TeamID,
		arg.ScopeType,
		arg.ScopeID,
		arg.State,
		arg.MetricValue,
		arg.Threshold,
		arg.Message,
		arg.NotifiedAt,
	)
	var i AlertEvent
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.TeamID,
		&i.ScopeType,
		&i.ScopeID,
		&i.State,
		&i.MetricValue,
		&i.Threshold,
		&i.Message,
		&i.NotifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAlertRule = `-- name: CreateAlertRule :one
INSERT INTO alert_rules (
    team_id,
    scope_type,
    scope_id,
    name,
    metric_name,
    comparison,
    threshold,
    duration_seconds,
    severity,
    enabled,
    notification_channels
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, COALESCE($11, true), $10)
RETURNING id, team_id, scope_type, scope_id, name, metric_name, comparison, threshold, duration_seconds, severity, enabled, notification_channels, last_state, last_value, last_evaluated_at, state_changed_at, created_at, updated_at
`

type CreateAlertRuleParams struct {
	TeamID               uuid.UUID   `json:"team_id"`
	ScopeType            string      `json:"scope_type"`
	ScopeID              uuid.UUID   `json:"scope_id"`
	Name                 string      `json:"name"`
	MetricName           string      `json:"metric_name"`
	Comparison           string      `json:"comparison"`
	Threshold            float64     `json:"threshold"`
	DurationSeconds      int32       `json:"duration_seconds"`
	Severity             string      `json:"severity"`
	NotificationChannels []uuid.UUID `json:"notification_channels"`
	Enabled              interface{} `json:"enabled"`
}

func (q *Queries) CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, createAlertRule,
		arg.TeamID,
		arg.ScopeType,
		arg.ScopeID,
		arg.Name,
		arg.MetricName,
		arg.Comparison,
		arg.Threshold,
		arg.DurationSeconds,
		arg.Severity,
		arg.NotificationChannels,
		arg.Enabled,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Name,
		&i.MetricName,
		&i.Comparison,
		&i.Threshold,
		&i.DurationSeconds,
		&i.Severity,
		&i.Enabled,
		&i.NotificationChannels,
		&i.LastState,
		&i.LastValue,
		&i.LastEvaluatedAt,
		&i.StateChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAlertSilence = `-- name: CreateAlertSilence :one
INSERT INTO alert_silences (team_id, rule_id, scope_type, scope_id, reason, starts_at, ends_at)
VALUES ($1, $4, $5, $6, $2, COALESCE($7, now()), $3)
RETURNING id, team_id, rule_id, scope_type, scope_id, reason, starts_at, ends_at, created_at
`

type CreateAlertSilenceParams struct {
	TeamID    uuid.UUID   `json:"team_id"`
	Reason    string      `json:"reason"`
	EndsAt    time.Time   `json:"ends_at"`
	RuleID    pgtype.UUID `json:"rule_id"`
	ScopeType *string     `json:"scope_type"`
	ScopeID   pgtype.UUID `json:"scope_id"`
	StartsAt  interface{} `json:"starts_at"`
}

func (q *Queries) CreateAlertSilence(ctx context.Context, arg CreateAlertSilenceParams) (AlertSilence, error) {
	row := q.db.QueryRow(ctx, createAlertSilence,
		arg.TeamID,
		arg.Reason,
		arg.EndsAt,
		arg.RuleID,
		arg.ScopeType,
		arg.ScopeID,
		arg.StartsAt,
	)
	var i AlertSilence
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.RuleID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Reason,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const createNotificationChannel = `-- name: CreateNotificationChannel :one
INSERT INTO notification_channels (team_id, name, type, target, enabled)
VALUES ($1, $2, $3, $4, COALESCE($5, true))
RETURNING id, team_id, name, type, target, enabled, created_at, updated_at
`

type CreateNotificationChannelParams struct {
	TeamID  uuid.UUID   `json:"team_id"`
	Name    string      `json:"name"`
	Type    string      `json:"type"`
	Target  string      `json:"target"`
	Enabled interface{} `json:"enabled"`
}

func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, createNotificationChannel,
		arg.TeamID,
		arg.Name,
		arg.Type,
		arg.Target,
		arg.Enabled,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Type,
		&i.Target,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAlertRule = `-- name: DeleteAlertRule :exec
DELETE FROM alert_rules
WHERE id = $1
  AND team_id = $2
`

type DeleteAlertRuleParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) DeleteAlertRule(ctx context.Context, arg DeleteAlertRuleParams) error {
	_, err := q.db.Exec(ctx, deleteAlertRule, arg.ID, arg.TeamID)
	return err
}

const deleteMetricSamplesForScope = `-- name: DeleteMetricSamplesForScope :exec
DELETE FROM metric_samples
WHERE scope_type = $1
  AND scope_id = $2
`

type DeleteMetricSamplesForScopeParams struct {
	ScopeType string    `json:"scope_type"`
	ScopeID   uuid.UUID `json:"scope_id"`
}

func (q *Queries) DeleteMetricSamplesForScope(ctx context.Context, arg DeleteMetricSamplesForScopeParams) error {
	_, err := q.db.Exec(ctx, deleteMetricSamplesForScope, arg.ScopeType, arg.ScopeID)
	return err
}

const deleteOldMetricSamples = `-- name: DeleteOldMetricSamples :exec
DELETE FROM metric_samples
WHERE sampled_at < $1
`

func (q *Queries) DeleteOldMetricSamples(ctx context.Context, sampledAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteOldMetricSamples, sampledAt)
	return err
}

const getAlertRule = `-- name: GetAlertRule :one
SELECT id, team_id, scope_type, scope_id, name, metric_name, comparison, threshold, duration_seconds, severity, enabled, notification_channels, last_state, last_value, last_evaluated_at, state_changed_at, created_at, updated_at
FROM alert_rules
WHERE id = $1
`

func (q *Queries) GetAlertRule(ctx context.Context, id uuid.UUID) (AlertRule, error) {
	row := q.db.QueryRow(ctx, getAlertRule, id)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Name,
		&i.MetricName,
		&i.Comparison,
		&i.Threshold,
		&i.DurationSeconds,
		&i.Severity,
		&i.Enabled,
		&i.NotificationChannels,
		&i.LastState,
		&i.LastValue,
		&i.LastEvaluatedAt,
		&i.StateChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestMetricSample = `-- name: GetLatestMetricSample :one
SELECT id, scope_type, scope_id, metric_name, value, labels, sampled_at
FROM metric_samples
WHERE scope_type = $1
  AND scope_id = $2
  AND metric_name = $3
ORDER BY sampled_at DESC
LIMIT 1
`

type GetLatestMetricSampleParams struct {
	ScopeType  string    `json:"scope_type"`
	ScopeID    uuid.UUID `json:"scope_id"`
	MetricName string    `json:"metric_name"`
}

func (q *Queries) GetLatestMetricSample(ctx context.Context, arg GetLatestMetricSampleParams) (MetricSample, error) {
	row := q.db.QueryRow(ctx, getLatestMetricSample, arg.ScopeType, arg.ScopeID, arg.MetricName)
	var i MetricSample
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.ScopeID,
		&i.MetricName,
		&i.Value,
		&i.Labels,
		&i.SampledAt,
	)
	return i, err
}

const insertMetricSample = `-- name: InsertMetricSample :one
INSERT INTO metric_samples (scope_type, scope_id, metric_name, value, labels, sampled_at)
VALUES ($1, $2, $3, $4, $5, COALESCE($6, now()))
RETURNING id, scope_type, scope_id, metric_name, value, labels, sampled_at
`

type InsertMetricSampleParams struct {
	ScopeType  string      `json:"scope_type"`
	ScopeID    uuid.UUID   `json:"scope_id"`
	MetricName string      `json:"metric_name"`
	Value      float64     `json:"value"`
	Labels     []byte      `json:"labels"`
	SampledAt  interface{} `json:"sampled_at"`
}

func (q *Queries) InsertMetricSample(ctx context.Context, arg InsertMetricSampleParams) (MetricSample, error) {
	row := q.db.QueryRow(ctx, insertMetricSample,
		arg.ScopeType,
		arg.ScopeID,
		arg.MetricName,
		arg.Value,
		arg.Labels,
		arg.SampledAt,
	)
	var i MetricSample
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.ScopeID,
		&i.MetricName,
		&i.Value,
		&i.Labels,
		&i.SampledAt,
	)
	return i, err
}

const isAlertSilenced = `-- name: IsAlertSilenced :one
SELECT EXISTS (
    SELECT 1
    FROM alert_silences
    WHERE team_id = $1
      AND starts_at <= now()
      AND ends_at > now()
      AND (
        rule_id = $2
        OR (rule_id IS NULL AND scope_type = $3 AND scope_id = $4)
      )
)::BOOLEAN
`

type IsAlertSilencedParams struct {
	TeamID    uuid.UUID   `json:"team_id"`
	RuleID    pgtype.UUID `json:"rule_id"`
	ScopeType *string     `json:"scope_type"`
	ScopeID   pgtype.UUID `json:"scope_id"`
}

func (q *Queries) IsAlertSilenced(ctx context.Context, arg IsAlertSilencedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isAlertSilenced,
		arg.TeamID,
		arg.RuleID,
		arg.ScopeType,
		arg.ScopeID,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listAlertEventsByScope = `-- name: ListAlertEventsByScope :many
SELECT id, rule_id, team_id, scope_type, scope_id, state, metric_value, threshold, message, notified_at, created_at
FROM alert_events
WHERE team_id = $1
  AND scope_type = $2
  AND scope_id = $3
ORDER BY created_at DESC
LIMIT $4
`

type ListAlertEventsByScopeParams struct {
	TeamID    uuid.UUID `json:"team_id"`
	ScopeType string    `json:"scope_type"`
	ScopeID   uuid.UUID `json:"scope_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListAlertEventsByScope(ctx context.Context, arg ListAlertEventsByScopeParams) ([]AlertEvent, error) {
	rows, err := q.db.Query(ctx, listAlertEventsByScope,
		arg.TeamID,
		arg.ScopeType,
		arg.ScopeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertEvent{}
	for rows.Next() {
		var i AlertEvent
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.TeamID,
			&i.ScopeType,
			&i.ScopeID,
			&i.State,
			&i.MetricValue,
			&i.Threshold,
			&i.Message,
			&i.NotifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertEventsByTeam = `-- name: ListAlertEventsByTeam :many
SELECT id, rule_id, team_id, scope_type, scope_id, state, metric_value, threshold, message, notified_at, created_at
FROM alert_events
WHERE team_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListAlertEventsByTeamParams struct {
	TeamID uuid.UUID `json:"team_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListAlertEventsByTeam(ctx context.Context, arg ListAlertEventsByTeamParams) ([]AlertEvent, error) {
	rows, err := q.db.Query(ctx, listAlertEventsByTeam, arg.TeamID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertEvent{}
	for rows.Next() {
		var i AlertEvent
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.TeamID,
			&i.ScopeType,
			&i.ScopeID,
			&i.State,
			&i.MetricValue,
			&i.Threshold,
			&i.Message,
			&i.NotifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertRulesByScope = `-- name: ListAlertRulesByScope :many
SELECT id, team_id, scope_type, scope_id, name, metric_name, comparison, threshold, duration_seconds, severity, enabled, notification_channels, last_state, last_value, last_evaluated_at, state_changed_at, created_at, updated_at
FROM alert_rules
WHERE team_id = $1
  AND scope_type = $2
  AND scope_id = $3
ORDER BY created_at DESC
`

type ListAlertRulesByScopeParams struct {
	TeamID    uuid.UUID `json:"team_id"`
	ScopeType string    `json:"scope_type"`
	ScopeID   uuid.UUID `json:"scope_id"`
}

func (q *Queries) ListAlertRulesByScope(ctx context.Context, arg ListAlertRulesByScopeParams) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, listAlertRulesByScope, arg.TeamID, arg.ScopeType, arg.ScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertRule{}
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ScopeType,
			&i.ScopeID,
			&i.Name,
			&i.MetricName,
			&i.Comparison,
			&i.Threshold,
			&i.DurationSeconds,
			&i.Severity,
			&i.Enabled,
			&i.NotificationChannels,
			&i.LastState,
			&i.LastValue,
			&i.LastEvaluatedAt,
			&i.StateChangedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertRulesByTeam = `-- name: ListAlertRulesByTeam :many
SELECT id, team_id, scope_type, scope_id, name, metric_name, comparison, threshold, duration_seconds, severity, enabled, notification_channels, last_state, last_value, last_evaluated_at, state_changed_at, created_at, updated_at
FROM alert_rules
WHERE team_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAlertRulesByTeam(ctx context.Context, teamID uuid.UUID) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, listAlertRulesByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertRule{}
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ScopeType,
			&i.ScopeID,
			&i.Name,
			&i.MetricName,
			&i.Comparison,
			&i.Threshold,
			&i.DurationSeconds,
			&i.Severity,
			&i.Enabled,
			&i.NotificationChannels,
			&i.LastState,
			&i.LastValue,
			&i.LastEvaluatedAt,
			&i.StateChangedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAlertRules = `-- name: ListEnabledAlertRules :many
SELECT id, team_id, scope_type, scope_id, name, metric_name, comparison, threshold, duration_seconds, severity, enabled, notification_channels, last_state, last_value, last_evaluated_at, state_changed_at, created_at, updated_at
FROM alert_rules
WHERE enabled = true
ORDER BY created_at ASC
`

func (q *Queries) ListEnabledAlertRules(ctx context.Context) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, listEnabledAlertRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertRule{}
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ScopeType,
			&i.ScopeID,
			&i.Name,
			&i.MetricName,
			&i.Comparison,
			&i.Threshold,
			&i.DurationSeconds,
			&i.Severity,
			&i.Enabled,
			&i.NotificationChannels,
			&i.LastState,
			&i.LastValue,
			&i.LastEvaluatedAt,
			&i.StateChangedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestMetricSamplesForScope = `-- name: ListLatestMetricSamplesForScope :many
SELECT DISTINCT ON (metric_name) id, scope_type, scope_id, metric_name, value, labels, sampled_at
FROM metric_samples
WHERE scope_type = $1
  AND scope_id = $2
ORDER BY metric_name, sampled_at DESC
`

type ListLatestMetricSamplesForScopeParams struct {
	ScopeType string    `json:"scope_type"`
	ScopeID   uuid.UUID `json:"scope_id"`
}

func (q *Queries) ListLatestMetricSamplesForScope(ctx context.Context, arg ListLatestMetricSamplesForScopeParams) ([]MetricSample, error) {
	rows, err := q.db.Query(ctx, listLatestMetricSamplesForScope, arg.ScopeType, arg.ScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricSample{}
	for rows.Next() {
		var i MetricSample
		if err := rows.Scan(
			&i.ID,
			&i.ScopeType,
			&i.ScopeID,
			&i.MetricName,
			&i.Value,
			&i.Labels,
			&i.SampledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetricSamples = `-- name: ListMetricSamples :many
SELECT id, scope_type, scope_id, metric_name, value, labels, sampled_at
FROM metric_samples
WHERE scope_type = $1
  AND scope_id = $2
  AND metric_name = $3
  AND sampled_at >= $4
ORDER BY sampled_at ASC
LIMIT $5
`

type ListMetricSamplesParams struct {
	ScopeType  string    `json:"scope_type"`
	ScopeID    uuid.UUID `json:"scope_id"`
	MetricName string    `json:"metric_name"`
	SampledAt  time.Time `json:"sampled_at"`
	Limit      int32     `json:"limit"`
}

func (q *Queries) ListMetricSamples(ctx context.Context, arg ListMetricSamplesParams) ([]MetricSample, error) {
	rows, err := q.db.Query(ctx, listMetricSamples,
		arg.ScopeType,
		arg.ScopeID,
		arg.MetricName,
		arg.SampledAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricSample{}
	for rows.Next() {
		var i MetricSample
		if err := rows.Scan(
			&i.ID,
			&i.ScopeType,
			&i.ScopeID,
			&i.MetricName,
			&i.Value,
			&i.Labels,
			&i.SampledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannelsByIDs = `-- name: ListNotificationChannelsByIDs :many
SELECT id, team_id, name, type, target, enabled, created_at, updated_at
FROM notification_channels
WHERE team_id = $1
  AND id = ANY($2::uuid[])
  AND enabled = true
ORDER BY created_at DESC
`

type ListNotificationChannelsByIDsParams struct {
	TeamID  uuid.UUID   `json:"team_id"`
	Column2 []uuid.UUID `json:"column_2"`
}

func (q *Queries) ListNotificationChannelsByIDs(ctx context.Context, arg ListNotificationChannelsByIDsParams) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listNotificationChannelsByIDs, arg.TeamID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Type,
			&i.Target,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannelsByTeam = `-- name: ListNotificationChannelsByTeam :many
SELECT id, team_id, name, type, target, enabled, created_at, updated_at
FROM notification_channels
WHERE team_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListNotificationChannelsByTeam(ctx context.Context, teamID uuid.UUID) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listNotificationChannelsByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Type,
			&i.Target,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlertRule = `-- name: UpdateAlertRule :one
UPDATE alert_rules
SET name = $3,
    metric_name = $4,
    comparison = $5,
    threshold = $6,
    duration_seconds = $7,
    severity = $8,
    enabled = $9,
    notification_channels = $10,
    updated_at = now()
WHERE id = $1
  AND team_id = $2
RETURNING id, team_id, scope_type, scope_id, name, metric_name, comparison, threshold, duration_seconds, severity, enabled, notification_channels, last_state, last_value, last_evaluated_at, state_changed_at, created_at, updated_at
`

type UpdateAlertRuleParams struct {
	ID                   uuid.UUID   `json:"id"`
	TeamID               uuid.UUID   `json:"team_id"`
	Name                 string      `json:"name"`
	MetricName           string      `json:"metric_name"`
	Comparison           string      `json:"comparison"`
	Threshold            float64     `json:"threshold"`
	DurationSeconds      int32       `json:"duration_seconds"`
	Severity             string      `json:"severity"`
	Enabled              bool        `json:"enabled"`
	NotificationChannels []uuid.UUID `json:"notification_channels"`
}

func (q *Queries) UpdateAlertRule(ctx context.Context, arg UpdateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, updateAlertRule,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.MetricName,
		arg.Comparison,
		arg.Threshold,
		arg.DurationSeconds,
		arg.Severity,
		arg.Enabled,
		arg.NotificationChannels,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Name,
		&i.MetricName,
		&i.Comparison,
		&i.Threshold,
		&i.DurationSeconds,
		&i.Severity,
		&i.Enabled,
		&i.NotificationChannels,
		&i.LastState,
		&i.LastValue,
		&i.LastEvaluatedAt,
		&i.StateChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAlertRuleState = `-- name: UpdateAlertRuleState :one
UPDATE alert_rules
SET last_state = $2,
    last_value = $3,
    last_evaluated_at = now(),
    state_changed_at = CASE WHEN last_state <> $2 THEN now() ELSE state_changed_at END,
    updated_at = now()
WHERE id = $1
RETURNING id, team_id, scope_type, scope_id, name, metric_name, comparison, threshold, duration_seconds, severity, enabled, notification_channels, last_state, last_value, last_evaluated_at, state_changed_at, created_at, updated_at
`

type UpdateAlertRuleStateParams struct {
	ID        uuid.UUID `json:"id"`
	LastState string    `json:"last_state"`
	LastValue *float64  `json:"last_value"`
}

func (q *Queries) UpdateAlertRuleState(ctx context.Context, arg UpdateAlertRuleStateParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, updateAlertRuleState, arg.ID, arg.LastState, arg.LastValue)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Name,
		&i.MetricName,
		&i.Comparison,
		&i.Threshold,
		&i.DurationSeconds,
		&i.Severity,
		&i.Enabled,
		&i.NotificationChannels,
		&i.LastState,
		&i.LastValue,
		&i.LastEvaluatedAt,
		&i.StateChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
