// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countProjectsByCluster = `-- name: CountProjectsByCluster :one
SELECT count(*) FROM projects WHERE cluster_id = $1
`

func (q *Queries) CountProjectsByCluster(ctx context.Context, clusterID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectsByCluster, clusterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (team_id, cluster_id, name, slug, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, team_id, cluster_id, name, slug, description, status, created_at, updated_at
`

type CreateProjectParams struct {
	TeamID      uuid.UUID `json:"team_id"`
	ClusterID   uuid.UUID `json:"cluster_id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description string    `json:"description"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.TeamID,
		arg.ClusterID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ClusterID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, team_id, cluster_id, name, slug, description, status, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ClusterID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByTeamAndSlug = `-- name: GetProjectByTeamAndSlug :one
SELECT id, team_id, cluster_id, name, slug, description, status, created_at, updated_at FROM projects WHERE team_id = $1 AND slug = $2
`

type GetProjectByTeamAndSlugParams struct {
	TeamID uuid.UUID `json:"team_id"`
	Slug   string    `json:"slug"`
}

func (q *Queries) GetProjectByTeamAndSlug(ctx context.Context, arg GetProjectByTeamAndSlugParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByTeamAndSlug, arg.TeamID, arg.Slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ClusterID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsByTeam = `-- name: ListProjectsByTeam :many
SELECT p.id, p.team_id, p.cluster_id, p.name, p.slug, p.description, p.status, p.created_at, p.updated_at, c.name AS cluster_name
FROM projects p
JOIN clusters c ON c.id = p.cluster_id
WHERE p.team_id = $1
ORDER BY p.created_at DESC
`

type ListProjectsByTeamRow struct {
	ID          uuid.UUID `json:"id"`
	TeamID      uuid.UUID `json:"team_id"`
	ClusterID   uuid.UUID `json:"cluster_id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description string    `json:"description"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	ClusterName string    `json:"cluster_name"`
}

func (q *Queries) ListProjectsByTeam(ctx context.Context, teamID uuid.UUID) ([]ListProjectsByTeamRow, error) {
	rows, err := q.db.Query(ctx, listProjectsByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsByTeamRow{}
	for rows.Next() {
		var i ListProjectsByTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ClusterID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClusterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $2, description = $3, status = $4, updated_at = now()
WHERE id = $1
RETURNING id, team_id, cluster_id, name, slug, description, status, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Status      string    `json:"status"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ClusterID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
