// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provisioning_jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendProvisioningLog = `-- name: AppendProvisioningLog :exec
UPDATE provisioning_jobs SET logs = logs || $2 WHERE id = $1
`

type AppendProvisioningLogParams struct {
	ID   uuid.UUID `json:"id"`
	Logs string    `json:"logs"`
}

func (q *Queries) AppendProvisioningLog(ctx context.Context, arg AppendProvisioningLogParams) error {
	_, err := q.db.Exec(ctx, appendProvisioningLog, arg.ID, arg.Logs)
	return err
}

const createProvisioningJob = `-- name: CreateProvisioningJob :one
INSERT INTO provisioning_jobs (server_id, components, status)
VALUES ($1, $2, 'pending') RETURNING id, server_id, components, status, logs, started_at, completed_at, error, created_at
`

type CreateProvisioningJobParams struct {
	ServerID   uuid.UUID `json:"server_id"`
	Components []string  `json:"components"`
}

func (q *Queries) CreateProvisioningJob(ctx context.Context, arg CreateProvisioningJobParams) (ProvisioningJob, error) {
	row := q.db.QueryRow(ctx, createProvisioningJob, arg.ServerID, arg.Components)
	var i ProvisioningJob
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Components,
		&i.Status,
		&i.Logs,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestProvisioningJob = `-- name: GetLatestProvisioningJob :one
SELECT id, server_id, components, status, logs, started_at, completed_at, error, created_at FROM provisioning_jobs WHERE server_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestProvisioningJob(ctx context.Context, serverID uuid.UUID) (ProvisioningJob, error) {
	row := q.db.QueryRow(ctx, getLatestProvisioningJob, serverID)
	var i ProvisioningJob
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Components,
		&i.Status,
		&i.Logs,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getProvisioningJob = `-- name: GetProvisioningJob :one
SELECT id, server_id, components, status, logs, started_at, completed_at, error, created_at FROM provisioning_jobs WHERE id = $1
`

func (q *Queries) GetProvisioningJob(ctx context.Context, id uuid.UUID) (ProvisioningJob, error) {
	row := q.db.QueryRow(ctx, getProvisioningJob, id)
	var i ProvisioningJob
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Components,
		&i.Status,
		&i.Logs,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const updateProvisioningJobStatus = `-- name: UpdateProvisioningJobStatus :exec
UPDATE provisioning_jobs SET status = $2, started_at = $3, completed_at = $4, error = $5 WHERE id = $1
`

type UpdateProvisioningJobStatusParams struct {
	ID          uuid.UUID          `json:"id"`
	Status      string             `json:"status"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Error       *string            `json:"error"`
}

func (q *Queries) UpdateProvisioningJobStatus(ctx context.Context, arg UpdateProvisioningJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateProvisioningJobStatus,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.Error,
	)
	return err
}
