// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registry_credentials.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRegistryCredential = `-- name: CreateRegistryCredential :one
INSERT INTO registry_credentials (team_id, name, registry_type, registry_url, username, password, region, aws_access_key_id, aws_secret_access_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, team_id, name, registry_type, registry_url, username, password, region, aws_access_key_id, aws_secret_access_key, validated_at, created_at, updated_at
`

type CreateRegistryCredentialParams struct {
	TeamID             uuid.UUID `json:"team_id"`
	Name               string    `json:"name"`
	RegistryType       string    `json:"registry_type"`
	RegistryUrl        string    `json:"registry_url"`
	Username           string    `json:"username"`
	Password           []byte    `json:"password"`
	Region             *string   `json:"region"`
	AwsAccessKeyID     *string   `json:"aws_access_key_id"`
	AwsSecretAccessKey []byte    `json:"aws_secret_access_key"`
}

func (q *Queries) CreateRegistryCredential(ctx context.Context, arg CreateRegistryCredentialParams) (RegistryCredential, error) {
	row := q.db.QueryRow(ctx, createRegistryCredential,
		arg.TeamID,
		arg.Name,
		arg.RegistryType,
		arg.RegistryUrl,
		arg.Username,
		arg.Password,
		arg.Region,
		arg.AwsAccessKeyID,
		arg.AwsSecretAccessKey,
	)
	var i RegistryCredential
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.RegistryType,
		&i.RegistryUrl,
		&i.Username,
		&i.Password,
		&i.Region,
		&i.AwsAccessKeyID,
		&i.AwsSecretAccessKey,
		&i.ValidatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRegistryCredential = `-- name: DeleteRegistryCredential :exec
DELETE FROM registry_credentials WHERE id = $1 AND team_id = $2
`

type DeleteRegistryCredentialParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) DeleteRegistryCredential(ctx context.Context, arg DeleteRegistryCredentialParams) error {
	_, err := q.db.Exec(ctx, deleteRegistryCredential, arg.ID, arg.TeamID)
	return err
}

const getRegistryCredentialByID = `-- name: GetRegistryCredentialByID :one
SELECT id, team_id, name, registry_type, registry_url, username, password, region, aws_access_key_id, aws_secret_access_key, validated_at, created_at, updated_at FROM registry_credentials WHERE id = $1 AND team_id = $2
`

type GetRegistryCredentialByIDParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) GetRegistryCredentialByID(ctx context.Context, arg GetRegistryCredentialByIDParams) (RegistryCredential, error) {
	row := q.db.QueryRow(ctx, getRegistryCredentialByID, arg.ID, arg.TeamID)
	var i RegistryCredential
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.RegistryType,
		&i.RegistryUrl,
		&i.Username,
		&i.Password,
		&i.Region,
		&i.AwsAccessKeyID,
		&i.AwsSecretAccessKey,
		&i.ValidatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRegistryCredentials = `-- name: ListRegistryCredentials :many
SELECT id, team_id, name, registry_type, registry_url, username, password, region, aws_access_key_id, aws_secret_access_key, validated_at, created_at, updated_at FROM registry_credentials WHERE team_id = $1 ORDER BY created_at
`

func (q *Queries) ListRegistryCredentials(ctx context.Context, teamID uuid.UUID) ([]RegistryCredential, error) {
	rows, err := q.db.Query(ctx, listRegistryCredentials, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RegistryCredential{}
	for rows.Next() {
		var i RegistryCredential
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.RegistryType,
			&i.RegistryUrl,
			&i.Username,
			&i.Password,
			&i.Region,
			&i.AwsAccessKeyID,
			&i.AwsSecretAccessKey,
			&i.ValidatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRegistryCredential = `-- name: UpdateRegistryCredential :one
UPDATE registry_credentials SET
    name = $3,
    registry_type = $4,
    registry_url = $5,
    username = $6,
    password = $7,
    region = $8,
    aws_access_key_id = $9,
    aws_secret_access_key = $10,
    validated_at = $11,
    updated_at = now()
WHERE id = $1 AND team_id = $2 RETURNING id, team_id, name, registry_type, registry_url, username, password, region, aws_access_key_id, aws_secret_access_key, validated_at, created_at, updated_at
`

type UpdateRegistryCredentialParams struct {
	ID                 uuid.UUID          `json:"id"`
	TeamID             uuid.UUID          `json:"team_id"`
	Name               string             `json:"name"`
	RegistryType       string             `json:"registry_type"`
	RegistryUrl        string             `json:"registry_url"`
	Username           string             `json:"username"`
	Password           []byte             `json:"password"`
	Region             *string            `json:"region"`
	AwsAccessKeyID     *string            `json:"aws_access_key_id"`
	AwsSecretAccessKey []byte             `json:"aws_secret_access_key"`
	ValidatedAt        pgtype.Timestamptz `json:"validated_at"`
}

func (q *Queries) UpdateRegistryCredential(ctx context.Context, arg UpdateRegistryCredentialParams) (RegistryCredential, error) {
	row := q.db.QueryRow(ctx, updateRegistryCredential,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.RegistryType,
		arg.RegistryUrl,
		arg.Username,
		arg.Password,
		arg.Region,
		arg.AwsAccessKeyID,
		arg.AwsSecretAccessKey,
		arg.ValidatedAt,
	)
	var i RegistryCredential
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.RegistryType,
		&i.RegistryUrl,
		&i.Username,
		&i.Password,
		&i.Region,
		&i.AwsAccessKeyID,
		&i.AwsSecretAccessKey,
		&i.ValidatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRegistryValidatedAt = `-- name: UpdateRegistryValidatedAt :exec
UPDATE registry_credentials SET validated_at = now() WHERE id = $1
`

func (q *Queries) UpdateRegistryValidatedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateRegistryValidatedAt, id)
	return err
}
