// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: secrets.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSecret = `-- name: CreateSecret :one
INSERT INTO secrets (team_id, environment, key, encrypted_value, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $5) RETURNING id, team_id, environment, key, encrypted_value, version, revealed_at, created_by, updated_by, created_at, updated_at
`

type CreateSecretParams struct {
	TeamID         uuid.UUID   `json:"team_id"`
	Environment    string      `json:"environment"`
	Key            string      `json:"key"`
	EncryptedValue []byte      `json:"encrypted_value"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, createSecret,
		arg.TeamID,
		arg.Environment,
		arg.Key,
		arg.EncryptedValue,
		arg.CreatedBy,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Environment,
		&i.Key,
		&i.EncryptedValue,
		&i.Version,
		&i.RevealedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSecret = `-- name: DeleteSecret :exec
DELETE FROM secrets WHERE id = $1 AND team_id = $2
`

type DeleteSecretParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) DeleteSecret(ctx context.Context, arg DeleteSecretParams) error {
	_, err := q.db.Exec(ctx, deleteSecret, arg.ID, arg.TeamID)
	return err
}

const deleteSecretByKey = `-- name: DeleteSecretByKey :exec
DELETE FROM secrets WHERE team_id = $1 AND environment = $2 AND key = $3
`

type DeleteSecretByKeyParams struct {
	TeamID      uuid.UUID `json:"team_id"`
	Environment string    `json:"environment"`
	Key         string    `json:"key"`
}

func (q *Queries) DeleteSecretByKey(ctx context.Context, arg DeleteSecretByKeyParams) error {
	_, err := q.db.Exec(ctx, deleteSecretByKey, arg.TeamID, arg.Environment, arg.Key)
	return err
}

const getSecretByID = `-- name: GetSecretByID :one
SELECT id, team_id, environment, key, encrypted_value, version, revealed_at, created_by, updated_by, created_at, updated_at FROM secrets WHERE id = $1 AND team_id = $2
`

type GetSecretByIDParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) GetSecretByID(ctx context.Context, arg GetSecretByIDParams) (Secret, error) {
	row := q.db.QueryRow(ctx, getSecretByID, arg.ID, arg.TeamID)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Environment,
		&i.Key,
		&i.EncryptedValue,
		&i.Version,
		&i.RevealedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSecretByKey = `-- name: GetSecretByKey :one
SELECT id, team_id, environment, key, encrypted_value, version, revealed_at, created_by, updated_by, created_at, updated_at FROM secrets WHERE team_id = $1 AND environment = $2 AND key = $3
`

type GetSecretByKeyParams struct {
	TeamID      uuid.UUID `json:"team_id"`
	Environment string    `json:"environment"`
	Key         string    `json:"key"`
}

func (q *Queries) GetSecretByKey(ctx context.Context, arg GetSecretByKeyParams) (Secret, error) {
	row := q.db.QueryRow(ctx, getSecretByKey, arg.TeamID, arg.Environment, arg.Key)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Environment,
		&i.Key,
		&i.EncryptedValue,
		&i.Version,
		&i.RevealedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSecrets = `-- name: ListSecrets :many
SELECT id, team_id, environment, key, version, revealed_at, created_by, updated_by, created_at, updated_at
FROM secrets
WHERE team_id = $1 AND environment = $2
ORDER BY key
`

type ListSecretsParams struct {
	TeamID      uuid.UUID `json:"team_id"`
	Environment string    `json:"environment"`
}

type ListSecretsRow struct {
	ID          uuid.UUID          `json:"id"`
	TeamID      uuid.UUID          `json:"team_id"`
	Environment string             `json:"environment"`
	Key         string             `json:"key"`
	Version     int32              `json:"version"`
	RevealedAt  pgtype.Timestamptz `json:"revealed_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

func (q *Queries) ListSecrets(ctx context.Context, arg ListSecretsParams) ([]ListSecretsRow, error) {
	rows, err := q.db.Query(ctx, listSecrets, arg.TeamID, arg.Environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretsRow{}
	for rows.Next() {
		var i ListSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Environment,
			&i.Key,
			&i.Version,
			&i.RevealedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretsByTeam = `-- name: ListSecretsByTeam :many
SELECT id, team_id, environment, key, version, revealed_at, created_by, updated_by, created_at, updated_at
FROM secrets
WHERE team_id = $1
ORDER BY environment, key
`

type ListSecretsByTeamRow struct {
	ID          uuid.UUID          `json:"id"`
	TeamID      uuid.UUID          `json:"team_id"`
	Environment string             `json:"environment"`
	Key         string             `json:"key"`
	Version     int32              `json:"version"`
	RevealedAt  pgtype.Timestamptz `json:"revealed_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

func (q *Queries) ListSecretsByTeam(ctx context.Context, teamID uuid.UUID) ([]ListSecretsByTeamRow, error) {
	rows, err := q.db.Query(ctx, listSecretsByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretsByTeamRow{}
	for rows.Next() {
		var i ListSecretsByTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Environment,
			&i.Key,
			&i.Version,
			&i.RevealedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSecretRevealedAt = `-- name: SetSecretRevealedAt :exec
UPDATE secrets SET revealed_at = now() WHERE id = $1
`

func (q *Queries) SetSecretRevealedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setSecretRevealedAt, id)
	return err
}

const updateSecretValue = `-- name: UpdateSecretValue :one
UPDATE secrets SET
    encrypted_value = $3,
    version = version + 1,
    revealed_at = NULL,
    updated_by = $4,
    updated_at = now()
WHERE id = $1 AND team_id = $2 RETURNING id, team_id, environment, key, encrypted_value, version, revealed_at, created_by, updated_by, created_at, updated_at
`

type UpdateSecretValueParams struct {
	ID             uuid.UUID   `json:"id"`
	TeamID         uuid.UUID   `json:"team_id"`
	EncryptedValue []byte      `json:"encrypted_value"`
	UpdatedBy      pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpdateSecretValue(ctx context.Context, arg UpdateSecretValueParams) (Secret, error) {
	row := q.db.QueryRow(ctx, updateSecretValue,
		arg.ID,
		arg.TeamID,
		arg.EncryptedValue,
		arg.UpdatedBy,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Environment,
		&i.Key,
		&i.EncryptedValue,
		&i.Version,
		&i.RevealedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
