// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: secret_access_log.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSecretAccessLogs = `-- name: CountSecretAccessLogs :one
SELECT count(*) FROM secret_access_log WHERE secret_id = $1
`

func (q *Queries) CountSecretAccessLogs(ctx context.Context, secretID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSecretAccessLogs, secretID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSecretAccessLog = `-- name: CreateSecretAccessLog :one
INSERT INTO secret_access_log (secret_id, team_id, actor_id, actor_type, action, ip_address)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, secret_id, team_id, actor_id, actor_type, action, ip_address, created_at
`

type CreateSecretAccessLogParams struct {
	SecretID  uuid.UUID   `json:"secret_id"`
	TeamID    uuid.UUID   `json:"team_id"`
	ActorID   pgtype.UUID `json:"actor_id"`
	ActorType string      `json:"actor_type"`
	Action    string      `json:"action"`
	IpAddress *netip.Addr `json:"ip_address"`
}

func (q *Queries) CreateSecretAccessLog(ctx context.Context, arg CreateSecretAccessLogParams) (SecretAccessLog, error) {
	row := q.db.QueryRow(ctx, createSecretAccessLog,
		arg.SecretID,
		arg.TeamID,
		arg.ActorID,
		arg.ActorType,
		arg.Action,
		arg.IpAddress,
	)
	var i SecretAccessLog
	err := row.Scan(
		&i.ID,
		&i.SecretID,
		&i.TeamID,
		&i.ActorID,
		&i.ActorType,
		&i.Action,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const listSecretAccessLogs = `-- name: ListSecretAccessLogs :many
SELECT id, secret_id, team_id, actor_id, actor_type, action, ip_address, created_at FROM secret_access_log
WHERE secret_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSecretAccessLogsParams struct {
	SecretID uuid.UUID `json:"secret_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListSecretAccessLogs(ctx context.Context, arg ListSecretAccessLogsParams) ([]SecretAccessLog, error) {
	rows, err := q.db.Query(ctx, listSecretAccessLogs, arg.SecretID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SecretAccessLog{}
	for rows.Next() {
		var i SecretAccessLog
		if err := rows.Scan(
			&i.ID,
			&i.SecretID,
			&i.TeamID,
			&i.ActorID,
			&i.ActorType,
			&i.Action,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretAccessLogsByTeam = `-- name: ListSecretAccessLogsByTeam :many
SELECT id, secret_id, team_id, actor_id, actor_type, action, ip_address, created_at FROM secret_access_log
WHERE team_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSecretAccessLogsByTeamParams struct {
	TeamID uuid.UUID `json:"team_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListSecretAccessLogsByTeam(ctx context.Context, arg ListSecretAccessLogsByTeamParams) ([]SecretAccessLog, error) {
	rows, err := q.db.Query(ctx, listSecretAccessLogsByTeam, arg.TeamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SecretAccessLog{}
	for rows.Next() {
		var i SecretAccessLog
		if err := rows.Scan(
			&i.ID,
			&i.SecretID,
			&i.TeamID,
			&i.ActorID,
			&i.ActorType,
			&i.Action,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
