// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: server_metrics.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getAverageMetricsForApp = `-- name: GetAverageMetricsForApp :one
SELECT
    COALESCE(AVG(sm.cpu_percent), 0)::DOUBLE PRECISION AS cpu_percent,
    COALESCE(AVG(
        CASE WHEN sm.memory_total > 0
            THEN (sm.memory_used::DOUBLE PRECISION / sm.memory_total::DOUBLE PRECISION) * 100
            ELSE 0
        END
    ), 0)::DOUBLE PRECISION AS memory_percent,
    COUNT(sm.server_id)::INT AS sample_count
FROM deployments d
JOIN deployment_targets dt ON dt.deployment_id = d.id
JOIN server_metrics sm ON sm.server_id = dt.server_id
WHERE d.app_id = $1
  AND d.status = 'healthy'
  AND dt.status = 'healthy'
  AND sm.updated_at > now() - interval '2 minutes'
`

type GetAverageMetricsForAppRow struct {
	CpuPercent    float64 `json:"cpu_percent"`
	MemoryPercent float64 `json:"memory_percent"`
	SampleCount   int32   `json:"sample_count"`
}

func (q *Queries) GetAverageMetricsForApp(ctx context.Context, appID uuid.UUID) (GetAverageMetricsForAppRow, error) {
	row := q.db.QueryRow(ctx, getAverageMetricsForApp, appID)
	var i GetAverageMetricsForAppRow
	err := row.Scan(&i.CpuPercent, &i.MemoryPercent, &i.SampleCount)
	return i, err
}

const listHealthyContainersByApp = `-- name: ListHealthyContainersByApp :many
SELECT
    dt.id AS target_id,
    d.id AS deployment_id,
    dt.container_id,
    dt.server_id,
    s.name AS server_name,
    s.agent_id,
    d.created_at
FROM deployment_targets dt
JOIN deployments d ON d.id = dt.deployment_id
JOIN servers s ON s.id = dt.server_id
WHERE d.app_id = $1
  AND d.status = 'healthy'
  AND dt.status = 'healthy'
  AND dt.container_id IS NOT NULL
ORDER BY d.created_at DESC
`

type ListHealthyContainersByAppRow struct {
	TargetID     uuid.UUID `json:"target_id"`
	DeploymentID uuid.UUID `json:"deployment_id"`
	ContainerID  *string   `json:"container_id"`
	ServerID     uuid.UUID `json:"server_id"`
	ServerName   string    `json:"server_name"`
	AgentID      *string   `json:"agent_id"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) ListHealthyContainersByApp(ctx context.Context, appID uuid.UUID) ([]ListHealthyContainersByAppRow, error) {
	rows, err := q.db.Query(ctx, listHealthyContainersByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHealthyContainersByAppRow{}
	for rows.Next() {
		var i ListHealthyContainersByAppRow
		if err := rows.Scan(
			&i.TargetID,
			&i.DeploymentID,
			&i.ContainerID,
			&i.ServerID,
			&i.ServerName,
			&i.AgentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertServerMetrics = `-- name: UpsertServerMetrics :exec
INSERT INTO server_metrics (server_id, cpu_percent, memory_total, memory_used, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (server_id) DO UPDATE SET
    cpu_percent = EXCLUDED.cpu_percent,
    memory_total = EXCLUDED.memory_total,
    memory_used = EXCLUDED.memory_used,
    updated_at = now()
`

type UpsertServerMetricsParams struct {
	ServerID    uuid.UUID `json:"server_id"`
	CpuPercent  float64   `json:"cpu_percent"`
	MemoryTotal int64     `json:"memory_total"`
	MemoryUsed  int64     `json:"memory_used"`
}

func (q *Queries) UpsertServerMetrics(ctx context.Context, arg UpsertServerMetricsParams) error {
	_, err := q.db.Exec(ctx, upsertServerMetrics,
		arg.ServerID,
		arg.CpuPercent,
		arg.MemoryTotal,
		arg.MemoryUsed,
	)
	return err
}
