// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: server_tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteServerTag = `-- name: DeleteServerTag :exec
DELETE FROM server_tags WHERE server_id = $1 AND key = $2
`

type DeleteServerTagParams struct {
	ServerID uuid.UUID `json:"server_id"`
	Key      string    `json:"key"`
}

func (q *Queries) DeleteServerTag(ctx context.Context, arg DeleteServerTagParams) error {
	_, err := q.db.Exec(ctx, deleteServerTag, arg.ServerID, arg.Key)
	return err
}

const listServerTags = `-- name: ListServerTags :many
SELECT id, server_id, key, value FROM server_tags WHERE server_id = $1 ORDER BY key
`

func (q *Queries) ListServerTags(ctx context.Context, serverID uuid.UUID) ([]ServerTag, error) {
	rows, err := q.db.Query(ctx, listServerTags, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServerTag{}
	for rows.Next() {
		var i ServerTag
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Key,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setServerTag = `-- name: SetServerTag :one
INSERT INTO server_tags (server_id, key, value)
VALUES ($1, $2, $3)
ON CONFLICT (server_id, key) DO UPDATE SET value = EXCLUDED.value
RETURNING id, server_id, key, value
`

type SetServerTagParams struct {
	ServerID uuid.UUID `json:"server_id"`
	Key      string    `json:"key"`
	Value    string    `json:"value"`
}

func (q *Queries) SetServerTag(ctx context.Context, arg SetServerTagParams) (ServerTag, error) {
	row := q.db.QueryRow(ctx, setServerTag, arg.ServerID, arg.Key, arg.Value)
	var i ServerTag
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Key,
		&i.Value,
	)
	return i, err
}
