// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: server_resources.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getServerResources = `-- name: GetServerResources :one
SELECT server_id, cpu_model, cpu_cores, memory_total, memory_available, kernel_version, docker_version, disks, network_interfaces, updated_at FROM server_resources WHERE server_id = $1
`

func (q *Queries) GetServerResources(ctx context.Context, serverID uuid.UUID) (ServerResource, error) {
	row := q.db.QueryRow(ctx, getServerResources, serverID)
	var i ServerResource
	err := row.Scan(
		&i.ServerID,
		&i.CpuModel,
		&i.CpuCores,
		&i.MemoryTotal,
		&i.MemoryAvailable,
		&i.KernelVersion,
		&i.DockerVersion,
		&i.Disks,
		&i.NetworkInterfaces,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertServerResources = `-- name: UpsertServerResources :exec
INSERT INTO server_resources (server_id, cpu_model, cpu_cores, memory_total, memory_available, kernel_version, docker_version, disks, network_interfaces, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
ON CONFLICT (server_id) DO UPDATE SET
    cpu_model = EXCLUDED.cpu_model,
    cpu_cores = EXCLUDED.cpu_cores,
    memory_total = EXCLUDED.memory_total,
    memory_available = EXCLUDED.memory_available,
    kernel_version = EXCLUDED.kernel_version,
    docker_version = EXCLUDED.docker_version,
    disks = EXCLUDED.disks,
    network_interfaces = EXCLUDED.network_interfaces,
    updated_at = now()
`

type UpsertServerResourcesParams struct {
	ServerID          uuid.UUID       `json:"server_id"`
	CpuModel          *string         `json:"cpu_model"`
	CpuCores          *int32          `json:"cpu_cores"`
	MemoryTotal       *int64          `json:"memory_total"`
	MemoryAvailable   *int64          `json:"memory_available"`
	KernelVersion     *string         `json:"kernel_version"`
	DockerVersion     *string         `json:"docker_version"`
	Disks             json.RawMessage `json:"disks"`
	NetworkInterfaces json.RawMessage `json:"network_interfaces"`
}

func (q *Queries) UpsertServerResources(ctx context.Context, arg UpsertServerResourcesParams) error {
	_, err := q.db.Exec(ctx, upsertServerResources,
		arg.ServerID,
		arg.CpuModel,
		arg.CpuCores,
		arg.MemoryTotal,
		arg.MemoryAvailable,
		arg.KernelVersion,
		arg.DockerVersion,
		arg.Disks,
		arg.NetworkInterfaces,
	)
	return err
}
