// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: servers.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createServer = `-- name: CreateServer :one
INSERT INTO servers (team_id, name, hostname, public_ip, ssh_port, ssh_user, os, os_version, arch, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id, team_id, agent_id, name, hostname, public_ip, ssh_port, ssh_user, os, os_version, arch, status, last_seen_at, created_at, updated_at, cluster_id
`

type CreateServerParams struct {
	TeamID    uuid.UUID  `json:"team_id"`
	Name      string     `json:"name"`
	Hostname  string     `json:"hostname"`
	PublicIp  netip.Addr `json:"public_ip"`
	SshPort   int32      `json:"ssh_port"`
	SshUser   string     `json:"ssh_user"`
	Os        *string    `json:"os"`
	OsVersion *string    `json:"os_version"`
	Arch      *string    `json:"arch"`
	Status    string     `json:"status"`
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, createServer,
		arg.TeamID,
		arg.Name,
		arg.Hostname,
		arg.PublicIp,
		arg.SshPort,
		arg.SshUser,
		arg.Os,
		arg.OsVersion,
		arg.Arch,
		arg.Status,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.AgentID,
		&i.Name,
		&i.Hostname,
		&i.PublicIp,
		&i.SshPort,
		&i.SshUser,
		&i.Os,
		&i.OsVersion,
		&i.Arch,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClusterID,
	)
	return i, err
}

const deleteServer = `-- name: DeleteServer :exec
DELETE FROM servers WHERE id = $1 AND team_id = $2
`

type DeleteServerParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) DeleteServer(ctx context.Context, arg DeleteServerParams) error {
	_, err := q.db.Exec(ctx, deleteServer, arg.ID, arg.TeamID)
	return err
}

const getServerByAgentID = `-- name: GetServerByAgentID :one
SELECT id, team_id, agent_id, name, hostname, public_ip, ssh_port, ssh_user, os, os_version, arch, status, last_seen_at, created_at, updated_at, cluster_id FROM servers WHERE agent_id = $1
`

func (q *Queries) GetServerByAgentID(ctx context.Context, agentID *string) (Server, error) {
	row := q.db.QueryRow(ctx, getServerByAgentID, agentID)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.AgentID,
		&i.Name,
		&i.Hostname,
		&i.PublicIp,
		&i.SshPort,
		&i.SshUser,
		&i.Os,
		&i.OsVersion,
		&i.Arch,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClusterID,
	)
	return i, err
}

const getServerByID = `-- name: GetServerByID :one
SELECT id, team_id, agent_id, name, hostname, public_ip, ssh_port, ssh_user, os, os_version, arch, status, last_seen_at, created_at, updated_at, cluster_id FROM servers WHERE id = $1 AND team_id = $2
`

type GetServerByIDParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) GetServerByID(ctx context.Context, arg GetServerByIDParams) (Server, error) {
	row := q.db.QueryRow(ctx, getServerByID, arg.ID, arg.TeamID)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.AgentID,
		&i.Name,
		&i.Hostname,
		&i.PublicIp,
		&i.SshPort,
		&i.SshUser,
		&i.Os,
		&i.OsVersion,
		&i.Arch,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClusterID,
	)
	return i, err
}

const listServersByTeam = `-- name: ListServersByTeam :many
SELECT id, team_id, agent_id, name, hostname, public_ip, ssh_port, ssh_user, os, os_version, arch, status, last_seen_at, created_at, updated_at, cluster_id FROM servers WHERE team_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListServersByTeam(ctx context.Context, teamID uuid.UUID) ([]Server, error) {
	rows, err := q.db.Query(ctx, listServersByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Server{}
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.AgentID,
			&i.Name,
			&i.Hostname,
			&i.PublicIp,
			&i.SshPort,
			&i.SshUser,
			&i.Os,
			&i.OsVersion,
			&i.Arch,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClusterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServersNeedingStatusUpdate = `-- name: ListServersNeedingStatusUpdate :many
SELECT id, status, last_seen_at FROM servers
WHERE status IN ('online', 'degraded') AND team_id IS NOT NULL
`

type ListServersNeedingStatusUpdateRow struct {
	ID         uuid.UUID          `json:"id"`
	Status     string             `json:"status"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) ListServersNeedingStatusUpdate(ctx context.Context) ([]ListServersNeedingStatusUpdateRow, error) {
	rows, err := q.db.Query(ctx, listServersNeedingStatusUpdate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServersNeedingStatusUpdateRow{}
	for rows.Next() {
		var i ListServersNeedingStatusUpdateRow
		if err := rows.Scan(&i.ID, &i.Status, &i.LastSeenAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServerAgentID = `-- name: UpdateServerAgentID :exec
UPDATE servers SET agent_id = $2, status = 'online', last_seen_at = now(), updated_at = now() WHERE id = $1
`

type UpdateServerAgentIDParams struct {
	ID      uuid.UUID `json:"id"`
	AgentID *string   `json:"agent_id"`
}

func (q *Queries) UpdateServerAgentID(ctx context.Context, arg UpdateServerAgentIDParams) error {
	_, err := q.db.Exec(ctx, updateServerAgentID, arg.ID, arg.AgentID)
	return err
}

const updateServerOS = `-- name: UpdateServerOS :exec
UPDATE servers SET os = $2, os_version = $3, arch = $4, updated_at = now() WHERE id = $1
`

type UpdateServerOSParams struct {
	ID        uuid.UUID `json:"id"`
	Os        *string   `json:"os"`
	OsVersion *string   `json:"os_version"`
	Arch      *string   `json:"arch"`
}

func (q *Queries) UpdateServerOS(ctx context.Context, arg UpdateServerOSParams) error {
	_, err := q.db.Exec(ctx, updateServerOS,
		arg.ID,
		arg.Os,
		arg.OsVersion,
		arg.Arch,
	)
	return err
}

const updateServerStatus = `-- name: UpdateServerStatus :exec
UPDATE servers SET status = $2, last_seen_at = $3, updated_at = now() WHERE id = $1
`

type UpdateServerStatusParams struct {
	ID         uuid.UUID          `json:"id"`
	Status     string             `json:"status"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) UpdateServerStatus(ctx context.Context, arg UpdateServerStatusParams) error {
	_, err := q.db.Exec(ctx, updateServerStatus, arg.ID, arg.Status, arg.LastSeenAt)
	return err
}
