// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ssh_keys.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const attachSSHKeyToServer = `-- name: AttachSSHKeyToServer :exec
INSERT INTO server_ssh_keys (server_id, ssh_key_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AttachSSHKeyToServerParams struct {
	ServerID uuid.UUID `json:"server_id"`
	SshKeyID uuid.UUID `json:"ssh_key_id"`
}

func (q *Queries) AttachSSHKeyToServer(ctx context.Context, arg AttachSSHKeyToServerParams) error {
	_, err := q.db.Exec(ctx, attachSSHKeyToServer, arg.ServerID, arg.SshKeyID)
	return err
}

const createSSHKey = `-- name: CreateSSHKey :one
INSERT INTO ssh_keys (team_id, name, public_key, private_key_encrypted, key_type, fingerprint)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, team_id, name, public_key, private_key_encrypted, key_type, fingerprint, created_at, updated_at
`

type CreateSSHKeyParams struct {
	TeamID              uuid.UUID `json:"team_id"`
	Name                string    `json:"name"`
	PublicKey           string    `json:"public_key"`
	PrivateKeyEncrypted []byte    `json:"private_key_encrypted"`
	KeyType             string    `json:"key_type"`
	Fingerprint         string    `json:"fingerprint"`
}

func (q *Queries) CreateSSHKey(ctx context.Context, arg CreateSSHKeyParams) (SshKey, error) {
	row := q.db.QueryRow(ctx, createSSHKey,
		arg.TeamID,
		arg.Name,
		arg.PublicKey,
		arg.PrivateKeyEncrypted,
		arg.KeyType,
		arg.Fingerprint,
	)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.PublicKey,
		&i.PrivateKeyEncrypted,
		&i.KeyType,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSSHKey = `-- name: DeleteSSHKey :exec
DELETE FROM ssh_keys WHERE id = $1 AND team_id = $2
`

type DeleteSSHKeyParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) DeleteSSHKey(ctx context.Context, arg DeleteSSHKeyParams) error {
	_, err := q.db.Exec(ctx, deleteSSHKey, arg.ID, arg.TeamID)
	return err
}

const detachSSHKeyFromServer = `-- name: DetachSSHKeyFromServer :exec
DELETE FROM server_ssh_keys WHERE server_id = $1 AND ssh_key_id = $2
`

type DetachSSHKeyFromServerParams struct {
	ServerID uuid.UUID `json:"server_id"`
	SshKeyID uuid.UUID `json:"ssh_key_id"`
}

func (q *Queries) DetachSSHKeyFromServer(ctx context.Context, arg DetachSSHKeyFromServerParams) error {
	_, err := q.db.Exec(ctx, detachSSHKeyFromServer, arg.ServerID, arg.SshKeyID)
	return err
}

const getSSHKeyByID = `-- name: GetSSHKeyByID :one
SELECT id, team_id, name, public_key, private_key_encrypted, key_type, fingerprint, created_at, updated_at FROM ssh_keys WHERE id = $1 AND team_id = $2
`

type GetSSHKeyByIDParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) GetSSHKeyByID(ctx context.Context, arg GetSSHKeyByIDParams) (SshKey, error) {
	row := q.db.QueryRow(ctx, getSSHKeyByID, arg.ID, arg.TeamID)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.PublicKey,
		&i.PrivateKeyEncrypted,
		&i.KeyType,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSSHKeyForServer = `-- name: GetSSHKeyForServer :one
SELECT sk.id, sk.team_id, sk.name, sk.public_key, sk.private_key_encrypted, sk.key_type, sk.fingerprint, sk.created_at, sk.updated_at FROM ssh_keys sk
JOIN server_ssh_keys ssk ON ssk.ssh_key_id = sk.id
WHERE ssk.server_id = $1
LIMIT 1
`

func (q *Queries) GetSSHKeyForServer(ctx context.Context, serverID uuid.UUID) (SshKey, error) {
	row := q.db.QueryRow(ctx, getSSHKeyForServer, serverID)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.PublicKey,
		&i.PrivateKeyEncrypted,
		&i.KeyType,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSSHKeysByTeam = `-- name: ListSSHKeysByTeam :many
SELECT id, team_id, name, public_key, key_type, fingerprint, created_at, updated_at
FROM ssh_keys WHERE team_id = $1 ORDER BY created_at DESC
`

type ListSSHKeysByTeamRow struct {
	ID          uuid.UUID `json:"id"`
	TeamID      uuid.UUID `json:"team_id"`
	Name        string    `json:"name"`
	PublicKey   string    `json:"public_key"`
	KeyType     string    `json:"key_type"`
	Fingerprint string    `json:"fingerprint"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) ListSSHKeysByTeam(ctx context.Context, teamID uuid.UUID) ([]ListSSHKeysByTeamRow, error) {
	rows, err := q.db.Query(ctx, listSSHKeysByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSSHKeysByTeamRow{}
	for rows.Next() {
		var i ListSSHKeysByTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.PublicKey,
			&i.KeyType,
			&i.Fingerprint,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
