// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: terminal_sessions.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTerminalSession = `-- name: CreateTerminalSession :one
INSERT INTO terminal_sessions (team_id, user_id, app_id, server_id, container_name, replica_index, session_type, client_ip)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, team_id, user_id, app_id, server_id, container_name, replica_index, session_type, started_at, ended_at, duration_seconds, client_ip
`

type CreateTerminalSessionParams struct {
	TeamID        uuid.UUID   `json:"team_id"`
	UserID        uuid.UUID   `json:"user_id"`
	AppID         pgtype.UUID `json:"app_id"`
	ServerID      uuid.UUID   `json:"server_id"`
	ContainerName *string     `json:"container_name"`
	ReplicaIndex  *int32      `json:"replica_index"`
	SessionType   string      `json:"session_type"`
	ClientIp      *netip.Addr `json:"client_ip"`
}

func (q *Queries) CreateTerminalSession(ctx context.Context, arg CreateTerminalSessionParams) (TerminalSession, error) {
	row := q.db.QueryRow(ctx, createTerminalSession,
		arg.TeamID,
		arg.UserID,
		arg.AppID,
		arg.ServerID,
		arg.ContainerName,
		arg.ReplicaIndex,
		arg.SessionType,
		arg.ClientIp,
	)
	var i TerminalSession
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.AppID,
		&i.ServerID,
		&i.ContainerName,
		&i.ReplicaIndex,
		&i.SessionType,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.ClientIp,
	)
	return i, err
}

const endTerminalSession = `-- name: EndTerminalSession :exec
UPDATE terminal_sessions
SET ended_at = now(), duration_seconds = EXTRACT(EPOCH FROM (now() - started_at))::INT
WHERE id = $1
`

func (q *Queries) EndTerminalSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, endTerminalSession, id)
	return err
}

const listTerminalSessionsByTeam = `-- name: ListTerminalSessionsByTeam :many
SELECT id, team_id, user_id, app_id, server_id, container_name, replica_index, session_type, started_at, ended_at, duration_seconds, client_ip FROM terminal_sessions
WHERE team_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListTerminalSessionsByTeamParams struct {
	TeamID uuid.UUID `json:"team_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListTerminalSessionsByTeam(ctx context.Context, arg ListTerminalSessionsByTeamParams) ([]TerminalSession, error) {
	rows, err := q.db.Query(ctx, listTerminalSessionsByTeam, arg.TeamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TerminalSession{}
	for rows.Next() {
		var i TerminalSession
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.AppID,
			&i.ServerID,
			&i.ContainerName,
			&i.ReplicaIndex,
			&i.SessionType,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationSeconds,
			&i.ClientIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
