// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (team_id, user_id, name, token_hash, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, team_id, user_id, name, token_hash, scopes, last_used_at, expires_at, revoked_at, created_at
`

type CreateAPITokenParams struct {
	TeamID    uuid.UUID          `json:"team_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Name      string             `json:"name"`
	TokenHash string             `json:"token_hash"`
	Scopes    []string           `json:"scopes"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.TeamID,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, team_id, user_id, name, token_hash, scopes, last_used_at, expires_at, revoked_at, created_at FROM api_tokens WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPITokensByTeam = `-- name: ListAPITokensByTeam :many
SELECT id, team_id, user_id, name, scopes, last_used_at, expires_at, created_at
FROM api_tokens
WHERE team_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

type ListAPITokensByTeamRow struct {
	ID         uuid.UUID          `json:"id"`
	TeamID     uuid.UUID          `json:"team_id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	Scopes     []string           `json:"scopes"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

func (q *Queries) ListAPITokensByTeam(ctx context.Context, teamID uuid.UUID) ([]ListAPITokensByTeamRow, error) {
	rows, err := q.db.Query(ctx, listAPITokensByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPITokensByTeamRow{}
	for rows.Next() {
		var i ListAPITokensByTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.Name,
			&i.Scopes,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :exec
UPDATE api_tokens SET revoked_at = now() WHERE id = $1 AND team_id = $2
`

type RevokeAPITokenParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) error {
	_, err := q.db.Exec(ctx, revokeAPIToken, arg.ID, arg.TeamID)
	return err
}

const updateTokenLastUsed = `-- name: UpdateTokenLastUsed :exec
UPDATE api_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) UpdateTokenLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateTokenLastUsed, id)
	return err
}
