// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: traffic.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTrafficBackendsByRoute = `-- name: CountTrafficBackendsByRoute :one
SELECT COUNT(*)::INT FROM traffic_backends WHERE route_id = $1
`

func (q *Queries) CountTrafficBackendsByRoute(ctx context.Context, routeID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countTrafficBackendsByRoute, routeID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createTrafficEvent = `-- name: CreateTrafficEvent :one
INSERT INTO traffic_events (route_id, actor_id, actor_type, event_type, message, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, route_id, actor_id, actor_type, event_type, message, metadata, created_at
`

type CreateTrafficEventParams struct {
	RouteID   uuid.UUID   `json:"route_id"`
	ActorID   pgtype.UUID `json:"actor_id"`
	ActorType string      `json:"actor_type"`
	EventType string      `json:"event_type"`
	Message   string      `json:"message"`
	Metadata  []byte      `json:"metadata"`
}

func (q *Queries) CreateTrafficEvent(ctx context.Context, arg CreateTrafficEventParams) (TrafficEvent, error) {
	row := q.db.QueryRow(ctx, createTrafficEvent,
		arg.RouteID,
		arg.ActorID,
		arg.ActorType,
		arg.EventType,
		arg.Message,
		arg.Metadata,
	)
	var i TrafficEvent
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.ActorID,
		&i.ActorType,
		&i.EventType,
		&i.Message,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const ensureTrafficRoute = `-- name: EnsureTrafficRoute :one
INSERT INTO traffic_routes (app_id, environment_id, domain)
VALUES ($1, $2, $3)
ON CONFLICT (app_id, environment_id, domain)
DO UPDATE SET updated_at = now()
RETURNING id, app_id, environment_id, domain, mode, status, created_at, updated_at
`

type EnsureTrafficRouteParams struct {
	AppID         uuid.UUID `json:"app_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
	Domain        string    `json:"domain"`
}

func (q *Queries) EnsureTrafficRoute(ctx context.Context, arg EnsureTrafficRouteParams) (TrafficRoute, error) {
	row := q.db.QueryRow(ctx, ensureTrafficRoute, arg.AppID, arg.EnvironmentID, arg.Domain)
	var i TrafficRoute
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.EnvironmentID,
		&i.Domain,
		&i.Mode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrafficRoute = `-- name: GetTrafficRoute :one
SELECT id, app_id, environment_id, domain, mode, status, created_at, updated_at FROM traffic_routes WHERE id = $1
`

func (q *Queries) GetTrafficRoute(ctx context.Context, id uuid.UUID) (TrafficRoute, error) {
	row := q.db.QueryRow(ctx, getTrafficRoute, id)
	var i TrafficRoute
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.EnvironmentID,
		&i.Domain,
		&i.Mode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrafficRouteByAppEnvironment = `-- name: GetTrafficRouteByAppEnvironment :one
SELECT id, app_id, environment_id, domain, mode, status, created_at, updated_at FROM traffic_routes
WHERE app_id = $1 AND environment_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetTrafficRouteByAppEnvironmentParams struct {
	AppID         uuid.UUID `json:"app_id"`
	EnvironmentID uuid.UUID `json:"environment_id"`
}

func (q *Queries) GetTrafficRouteByAppEnvironment(ctx context.Context, arg GetTrafficRouteByAppEnvironmentParams) (TrafficRoute, error) {
	row := q.db.QueryRow(ctx, getTrafficRouteByAppEnvironment, arg.AppID, arg.EnvironmentID)
	var i TrafficRoute
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.EnvironmentID,
		&i.Domain,
		&i.Mode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTrafficBackendsByRoute = `-- name: ListTrafficBackendsByRoute :many
SELECT tb.id, tb.route_id, tb.deployment_id, tb.label, tb.weight, tb.status, tb.created_at, tb.updated_at, d.status AS deployment_status, d.replicas_ready, d.replicas_desired,
       b.commit_sha, b.image_tag
FROM traffic_backends tb
JOIN deployments d ON d.id = tb.deployment_id
JOIN builds b ON b.id = d.build_id
WHERE tb.route_id = $1
ORDER BY tb.created_at DESC
`

type ListTrafficBackendsByRouteRow struct {
	ID               uuid.UUID `json:"id"`
	RouteID          uuid.UUID `json:"route_id"`
	DeploymentID     uuid.UUID `json:"deployment_id"`
	Label            string    `json:"label"`
	Weight           int32     `json:"weight"`
	Status           string    `json:"status"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	DeploymentStatus string    `json:"deployment_status"`
	ReplicasReady    int32     `json:"replicas_ready"`
	ReplicasDesired  int32     `json:"replicas_desired"`
	CommitSha        string    `json:"commit_sha"`
	ImageTag         string    `json:"image_tag"`
}

func (q *Queries) ListTrafficBackendsByRoute(ctx context.Context, routeID uuid.UUID) ([]ListTrafficBackendsByRouteRow, error) {
	rows, err := q.db.Query(ctx, listTrafficBackendsByRoute, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrafficBackendsByRouteRow{}
	for rows.Next() {
		var i ListTrafficBackendsByRouteRow
		if err := rows.Scan(
			&i.ID,
			&i.RouteID,
			&i.DeploymentID,
			&i.Label,
			&i.Weight,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeploymentStatus,
			&i.ReplicasReady,
			&i.ReplicasDesired,
			&i.CommitSha,
			&i.ImageTag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrafficBackendsForSync = `-- name: ListTrafficBackendsForSync :many
SELECT tb.id AS backend_id, tb.deployment_id, tb.label, tb.weight,
       d.status AS deployment_status
FROM traffic_backends tb
JOIN deployments d ON d.id = tb.deployment_id
WHERE tb.route_id = $1
  AND tb.status = 'active'
  AND tb.weight > 0
  AND d.status = 'healthy'
ORDER BY tb.created_at DESC
`

type ListTrafficBackendsForSyncRow struct {
	BackendID        uuid.UUID `json:"backend_id"`
	DeploymentID     uuid.UUID `json:"deployment_id"`
	Label            string    `json:"label"`
	Weight           int32     `json:"weight"`
	DeploymentStatus string    `json:"deployment_status"`
}

func (q *Queries) ListTrafficBackendsForSync(ctx context.Context, routeID uuid.UUID) ([]ListTrafficBackendsForSyncRow, error) {
	rows, err := q.db.Query(ctx, listTrafficBackendsForSync, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrafficBackendsForSyncRow{}
	for rows.Next() {
		var i ListTrafficBackendsForSyncRow
		if err := rows.Scan(
			&i.BackendID,
			&i.DeploymentID,
			&i.Label,
			&i.Weight,
			&i.DeploymentStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrafficEventsByRoute = `-- name: ListTrafficEventsByRoute :many
SELECT id, route_id, actor_id, actor_type, event_type, message, metadata, created_at FROM traffic_events
WHERE route_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTrafficEventsByRouteParams struct {
	RouteID uuid.UUID `json:"route_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListTrafficEventsByRoute(ctx context.Context, arg ListTrafficEventsByRouteParams) ([]TrafficEvent, error) {
	rows, err := q.db.Query(ctx, listTrafficEventsByRoute, arg.RouteID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrafficEvent{}
	for rows.Next() {
		var i TrafficEvent
		if err := rows.Scan(
			&i.ID,
			&i.RouteID,
			&i.ActorID,
			&i.ActorType,
			&i.EventType,
			&i.Message,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrafficRoutesByApp = `-- name: ListTrafficRoutesByApp :many
SELECT id, app_id, environment_id, domain, mode, status, created_at, updated_at FROM traffic_routes
WHERE app_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTrafficRoutesByApp(ctx context.Context, appID uuid.UUID) ([]TrafficRoute, error) {
	rows, err := q.db.Query(ctx, listTrafficRoutesByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrafficRoute{}
	for rows.Next() {
		var i TrafficRoute
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.EnvironmentID,
			&i.Domain,
			&i.Mode,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTrafficBackendStatus = `-- name: SetTrafficBackendStatus :one
UPDATE traffic_backends
SET status = $3, updated_at = now()
WHERE id = $1 AND route_id = $2
RETURNING id, route_id, deployment_id, label, weight, status, created_at, updated_at
`

type SetTrafficBackendStatusParams struct {
	ID      uuid.UUID `json:"id"`
	RouteID uuid.UUID `json:"route_id"`
	Status  string    `json:"status"`
}

func (q *Queries) SetTrafficBackendStatus(ctx context.Context, arg SetTrafficBackendStatusParams) (TrafficBackend, error) {
	row := q.db.QueryRow(ctx, setTrafficBackendStatus, arg.ID, arg.RouteID, arg.Status)
	var i TrafficBackend
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.DeploymentID,
		&i.Label,
		&i.Weight,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTrafficBackendWeight = `-- name: UpdateTrafficBackendWeight :one
UPDATE traffic_backends
SET weight = $3, updated_at = now()
WHERE id = $1 AND route_id = $2
RETURNING id, route_id, deployment_id, label, weight, status, created_at, updated_at
`

type UpdateTrafficBackendWeightParams struct {
	ID      uuid.UUID `json:"id"`
	RouteID uuid.UUID `json:"route_id"`
	Weight  int32     `json:"weight"`
}

func (q *Queries) UpdateTrafficBackendWeight(ctx context.Context, arg UpdateTrafficBackendWeightParams) (TrafficBackend, error) {
	row := q.db.QueryRow(ctx, updateTrafficBackendWeight, arg.ID, arg.RouteID, arg.Weight)
	var i TrafficBackend
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.DeploymentID,
		&i.Label,
		&i.Weight,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTrafficBackend = `-- name: UpsertTrafficBackend :one
INSERT INTO traffic_backends (route_id, deployment_id, label, weight, status)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (route_id, deployment_id)
DO UPDATE SET label = EXCLUDED.label, status = EXCLUDED.status, updated_at = now()
RETURNING id, route_id, deployment_id, label, weight, status, created_at, updated_at
`

type UpsertTrafficBackendParams struct {
	RouteID      uuid.UUID `json:"route_id"`
	DeploymentID uuid.UUID `json:"deployment_id"`
	Label        string    `json:"label"`
	Weight       int32     `json:"weight"`
	Status       string    `json:"status"`
}

func (q *Queries) UpsertTrafficBackend(ctx context.Context, arg UpsertTrafficBackendParams) (TrafficBackend, error) {
	row := q.db.QueryRow(ctx, upsertTrafficBackend,
		arg.RouteID,
		arg.DeploymentID,
		arg.Label,
		arg.Weight,
		arg.Status,
	)
	var i TrafficBackend
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.DeploymentID,
		&i.Label,
		&i.Weight,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
