// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name, email_verify_token, email_verify_expires)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password_hash, name, email_verified, email_verify_token, email_verify_expires, password_reset_token, password_reset_expires, created_at, updated_at
`

type CreateUserParams struct {
	Email              string             `json:"email"`
	PasswordHash       string             `json:"password_hash"`
	Name               string             `json:"name"`
	EmailVerifyToken   *string            `json:"email_verify_token"`
	EmailVerifyExpires pgtype.Timestamptz `json:"email_verify_expires"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.EmailVerifyToken,
		arg.EmailVerifyExpires,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.EmailVerified,
		&i.EmailVerifyToken,
		&i.EmailVerifyExpires,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, email_verified, email_verify_token, email_verify_expires, password_reset_token, password_reset_expires, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.EmailVerified,
		&i.EmailVerifyToken,
		&i.EmailVerifyExpires,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, email_verified, email_verify_token, email_verify_expires, password_reset_token, password_reset_expires, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.EmailVerified,
		&i.EmailVerifyToken,
		&i.EmailVerifyExpires,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByResetToken = `-- name: GetUserByResetToken :one
SELECT id, email, password_hash, name, email_verified, email_verify_token, email_verify_expires, password_reset_token, password_reset_expires, created_at, updated_at FROM users WHERE password_reset_token = $1 AND password_reset_expires > now()
`

func (q *Queries) GetUserByResetToken(ctx context.Context, passwordResetToken *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByResetToken, passwordResetToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.EmailVerified,
		&i.EmailVerifyToken,
		&i.EmailVerifyExpires,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByVerifyToken = `-- name: GetUserByVerifyToken :one
SELECT id, email, password_hash, name, email_verified, email_verify_token, email_verify_expires, password_reset_token, password_reset_expires, created_at, updated_at FROM users WHERE email_verify_token = $1 AND email_verify_expires > now()
`

func (q *Queries) GetUserByVerifyToken(ctx context.Context, emailVerifyToken *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByVerifyToken, emailVerifyToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.EmailVerified,
		&i.EmailVerifyToken,
		&i.EmailVerifyExpires,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPasswordResetToken = `-- name: SetPasswordResetToken :exec
UPDATE users SET password_reset_token = $2, password_reset_expires = $3, updated_at = now()
WHERE id = $1
`

type SetPasswordResetTokenParams struct {
	ID                   uuid.UUID          `json:"id"`
	PasswordResetToken   *string            `json:"password_reset_token"`
	PasswordResetExpires pgtype.Timestamptz `json:"password_reset_expires"`
}

func (q *Queries) SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, setPasswordResetToken, arg.ID, arg.PasswordResetToken, arg.PasswordResetExpires)
	return err
}

const setEmailVerifyToken = `-- name: SetEmailVerifyToken :exec
UPDATE users SET email_verify_token = $2, email_verify_expires = $3, updated_at = now()
WHERE id = $1
`

type SetEmailVerifyTokenParams struct {
	ID                 uuid.UUID          `json:"id"`
	EmailVerifyToken   *string            `json:"email_verify_token"`
	EmailVerifyExpires pgtype.Timestamptz `json:"email_verify_expires"`
}

func (q *Queries) SetEmailVerifyToken(ctx context.Context, arg SetEmailVerifyTokenParams) error {
	_, err := q.db.Exec(ctx, setEmailVerifyToken, arg.ID, arg.EmailVerifyToken, arg.EmailVerifyExpires)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users SET password_hash = $2, password_reset_token = NULL, password_reset_expires = NULL, updated_at = now()
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users SET email_verified = true, email_verify_token = NULL, email_verify_expires = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) VerifyUserEmail(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, id)
	return err
}
