// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: volumes.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createVolume = `-- name: CreateVolume :one
INSERT INTO volumes (team_id, cluster_id, server_id, name, size_gb, filesystem, status, host_path)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, team_id, cluster_id, server_id, name, size_gb, used_bytes, filesystem, mount_path, container_name, status, host_path, created_at, updated_at
`

type CreateVolumeParams struct {
	TeamID     uuid.UUID `json:"team_id"`
	ClusterID  uuid.UUID `json:"cluster_id"`
	ServerID   uuid.UUID `json:"server_id"`
	Name       string    `json:"name"`
	SizeGb     int32     `json:"size_gb"`
	Filesystem string    `json:"filesystem"`
	Status     string    `json:"status"`
	HostPath   string    `json:"host_path"`
}

func (q *Queries) CreateVolume(ctx context.Context, arg CreateVolumeParams) (Volume, error) {
	row := q.db.QueryRow(ctx, createVolume,
		arg.TeamID,
		arg.ClusterID,
		arg.ServerID,
		arg.Name,
		arg.SizeGb,
		arg.Filesystem,
		arg.Status,
		arg.HostPath,
	)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ClusterID,
		&i.ServerID,
		&i.Name,
		&i.SizeGb,
		&i.UsedBytes,
		&i.Filesystem,
		&i.MountPath,
		&i.ContainerName,
		&i.Status,
		&i.HostPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVolumeSnapshot = `-- name: CreateVolumeSnapshot :one
INSERT INTO volume_snapshots (volume_id, size_bytes, storage_type, storage_path)
VALUES ($1, $2, $3, $4)
RETURNING id, volume_id, size_bytes, storage_type, storage_path, created_at
`

type CreateVolumeSnapshotParams struct {
	VolumeID    uuid.UUID `json:"volume_id"`
	SizeBytes   int64     `json:"size_bytes"`
	StorageType string    `json:"storage_type"`
	StoragePath string    `json:"storage_path"`
}

func (q *Queries) CreateVolumeSnapshot(ctx context.Context, arg CreateVolumeSnapshotParams) (VolumeSnapshot, error) {
	row := q.db.QueryRow(ctx, createVolumeSnapshot,
		arg.VolumeID,
		arg.SizeBytes,
		arg.StorageType,
		arg.StoragePath,
	)
	var i VolumeSnapshot
	err := row.Scan(
		&i.ID,
		&i.VolumeID,
		&i.SizeBytes,
		&i.StorageType,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVolume = `-- name: DeleteVolume :exec
DELETE FROM volumes WHERE id = $1 AND team_id = $2
`

type DeleteVolumeParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) DeleteVolume(ctx context.Context, arg DeleteVolumeParams) error {
	_, err := q.db.Exec(ctx, deleteVolume, arg.ID, arg.TeamID)
	return err
}

const deleteVolumeSnapshot = `-- name: DeleteVolumeSnapshot :exec
DELETE FROM volume_snapshots WHERE id = $1
`

func (q *Queries) DeleteVolumeSnapshot(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVolumeSnapshot, id)
	return err
}

const getVolume = `-- name: GetVolume :one
SELECT id, team_id, cluster_id, server_id, name, size_gb, used_bytes, filesystem, mount_path, container_name, status, host_path, created_at, updated_at FROM volumes WHERE id = $1 AND team_id = $2
`

type GetVolumeParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) GetVolume(ctx context.Context, arg GetVolumeParams) (Volume, error) {
	row := q.db.QueryRow(ctx, getVolume, arg.ID, arg.TeamID)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ClusterID,
		&i.ServerID,
		&i.Name,
		&i.SizeGb,
		&i.UsedBytes,
		&i.Filesystem,
		&i.MountPath,
		&i.ContainerName,
		&i.Status,
		&i.HostPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVolumeAnyTeam = `-- name: GetVolumeAnyTeam :one
SELECT id, team_id, cluster_id, server_id, name, size_gb, used_bytes, filesystem, mount_path, container_name, status, host_path, created_at, updated_at FROM volumes WHERE id = $1
`

func (q *Queries) GetVolumeAnyTeam(ctx context.Context, id uuid.UUID) (Volume, error) {
	row := q.db.QueryRow(ctx, getVolumeAnyTeam, id)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ClusterID,
		&i.ServerID,
		&i.Name,
		&i.SizeGb,
		&i.UsedBytes,
		&i.Filesystem,
		&i.MountPath,
		&i.ContainerName,
		&i.Status,
		&i.HostPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVolumeSnapshot = `-- name: GetVolumeSnapshot :one
SELECT id, volume_id, size_bytes, storage_type, storage_path, created_at FROM volume_snapshots WHERE id = $1
`

func (q *Queries) GetVolumeSnapshot(ctx context.Context, id uuid.UUID) (VolumeSnapshot, error) {
	row := q.db.QueryRow(ctx, getVolumeSnapshot, id)
	var i VolumeSnapshot
	err := row.Scan(
		&i.ID,
		&i.VolumeID,
		&i.SizeBytes,
		&i.StorageType,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return i, err
}

const listVolumeSnapshots = `-- name: ListVolumeSnapshots :many
SELECT id, volume_id, size_bytes, storage_type, storage_path, created_at FROM volume_snapshots WHERE volume_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListVolumeSnapshots(ctx context.Context, volumeID uuid.UUID) ([]VolumeSnapshot, error) {
	rows, err := q.db.Query(ctx, listVolumeSnapshots, volumeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VolumeSnapshot{}
	for rows.Next() {
		var i VolumeSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.VolumeID,
			&i.SizeBytes,
			&i.StorageType,
			&i.StoragePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVolumesByCluster = `-- name: ListVolumesByCluster :many
SELECT id, team_id, cluster_id, server_id, name, size_gb, used_bytes, filesystem, mount_path, container_name, status, host_path, created_at, updated_at FROM volumes WHERE team_id = $1 AND cluster_id = $2 ORDER BY created_at DESC
`

type ListVolumesByClusterParams struct {
	TeamID    uuid.UUID `json:"team_id"`
	ClusterID uuid.UUID `json:"cluster_id"`
}

func (q *Queries) ListVolumesByCluster(ctx context.Context, arg ListVolumesByClusterParams) ([]Volume, error) {
	rows, err := q.db.Query(ctx, listVolumesByCluster, arg.TeamID, arg.ClusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Volume{}
	for rows.Next() {
		var i Volume
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ClusterID,
			&i.ServerID,
			&i.Name,
			&i.SizeGb,
			&i.UsedBytes,
			&i.Filesystem,
			&i.MountPath,
			&i.ContainerName,
			&i.Status,
			&i.HostPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVolumesByServer = `-- name: ListVolumesByServer :many
SELECT id, team_id, cluster_id, server_id, name, size_gb, used_bytes, filesystem, mount_path, container_name, status, host_path, created_at, updated_at FROM volumes WHERE team_id = $1 AND server_id = $2 ORDER BY created_at DESC
`

type ListVolumesByServerParams struct {
	TeamID   uuid.UUID `json:"team_id"`
	ServerID uuid.UUID `json:"server_id"`
}

func (q *Queries) ListVolumesByServer(ctx context.Context, arg ListVolumesByServerParams) ([]Volume, error) {
	rows, err := q.db.Query(ctx, listVolumesByServer, arg.TeamID, arg.ServerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Volume{}
	for rows.Next() {
		var i Volume
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ClusterID,
			&i.ServerID,
			&i.Name,
			&i.SizeGb,
			&i.UsedBytes,
			&i.Filesystem,
			&i.MountPath,
			&i.ContainerName,
			&i.Status,
			&i.HostPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVolumesByStatus = `-- name: ListVolumesByStatus :many
SELECT id, team_id, cluster_id, server_id, name, size_gb, used_bytes, filesystem, mount_path, container_name, status, host_path, created_at, updated_at FROM volumes WHERE team_id = $1 AND status = $2 ORDER BY created_at DESC
`

type ListVolumesByStatusParams struct {
	TeamID uuid.UUID `json:"team_id"`
	Status string    `json:"status"`
}

func (q *Queries) ListVolumesByStatus(ctx context.Context, arg ListVolumesByStatusParams) ([]Volume, error) {
	rows, err := q.db.Query(ctx, listVolumesByStatus, arg.TeamID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Volume{}
	for rows.Next() {
		var i Volume
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ClusterID,
			&i.ServerID,
			&i.Name,
			&i.SizeGb,
			&i.UsedBytes,
			&i.Filesystem,
			&i.MountPath,
			&i.ContainerName,
			&i.Status,
			&i.HostPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVolumesByTeam = `-- name: ListVolumesByTeam :many
SELECT id, team_id, cluster_id, server_id, name, size_gb, used_bytes, filesystem, mount_path, container_name, status, host_path, created_at, updated_at FROM volumes WHERE team_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListVolumesByTeam(ctx context.Context, teamID uuid.UUID) ([]Volume, error) {
	rows, err := q.db.Query(ctx, listVolumesByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Volume{}
	for rows.Next() {
		var i Volume
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ClusterID,
			&i.ServerID,
			&i.Name,
			&i.SizeGb,
			&i.UsedBytes,
			&i.Filesystem,
			&i.MountPath,
			&i.ContainerName,
			&i.Status,
			&i.HostPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVolumeAttachment = `-- name: UpdateVolumeAttachment :one
UPDATE volumes
SET mount_path = $4,
    container_name = $5,
    status = $3,
    updated_at = now()
WHERE id = $1 AND team_id = $2
RETURNING id, team_id, cluster_id, server_id, name, size_gb, used_bytes, filesystem, mount_path, container_name, status, host_path, created_at, updated_at
`

type UpdateVolumeAttachmentParams struct {
	ID            uuid.UUID `json:"id"`
	TeamID        uuid.UUID `json:"team_id"`
	Status        string    `json:"status"`
	MountPath     *string   `json:"mount_path"`
	ContainerName *string   `json:"container_name"`
}

func (q *Queries) UpdateVolumeAttachment(ctx context.Context, arg UpdateVolumeAttachmentParams) (Volume, error) {
	row := q.db.QueryRow(ctx, updateVolumeAttachment,
		arg.ID,
		arg.TeamID,
		arg.Status,
		arg.MountPath,
		arg.ContainerName,
	)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ClusterID,
		&i.ServerID,
		&i.Name,
		&i.SizeGb,
		&i.UsedBytes,
		&i.Filesystem,
		&i.MountPath,
		&i.ContainerName,
		&i.Status,
		&i.HostPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVolumeHostPath = `-- name: UpdateVolumeHostPath :exec
UPDATE volumes
SET host_path = $2, updated_at = now()
WHERE id = $1
`

type UpdateVolumeHostPathParams struct {
	ID       uuid.UUID `json:"id"`
	HostPath string    `json:"host_path"`
}

func (q *Queries) UpdateVolumeHostPath(ctx context.Context, arg UpdateVolumeHostPathParams) error {
	_, err := q.db.Exec(ctx, updateVolumeHostPath, arg.ID, arg.HostPath)
	return err
}

const updateVolumeServer = `-- name: UpdateVolumeServer :one
UPDATE volumes
SET server_id = $3, status = $4, updated_at = now()
WHERE id = $1 AND team_id = $2
RETURNING id, team_id, cluster_id, server_id, name, size_gb, used_bytes, filesystem, mount_path, container_name, status, host_path, created_at, updated_at
`

type UpdateVolumeServerParams struct {
	ID       uuid.UUID `json:"id"`
	TeamID   uuid.UUID `json:"team_id"`
	ServerID uuid.UUID `json:"server_id"`
	Status   string    `json:"status"`
}

func (q *Queries) UpdateVolumeServer(ctx context.Context, arg UpdateVolumeServerParams) (Volume, error) {
	row := q.db.QueryRow(ctx, updateVolumeServer,
		arg.ID,
		arg.TeamID,
		arg.ServerID,
		arg.Status,
	)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ClusterID,
		&i.ServerID,
		&i.Name,
		&i.SizeGb,
		&i.UsedBytes,
		&i.Filesystem,
		&i.MountPath,
		&i.ContainerName,
		&i.Status,
		&i.HostPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVolumeSize = `-- name: UpdateVolumeSize :one
UPDATE volumes
SET size_gb = $3, updated_at = now()
WHERE id = $1 AND team_id = $2
RETURNING id, team_id, cluster_id, server_id, name, size_gb, used_bytes, filesystem, mount_path, container_name, status, host_path, created_at, updated_at
`

type UpdateVolumeSizeParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
	SizeGb int32     `json:"size_gb"`
}

func (q *Queries) UpdateVolumeSize(ctx context.Context, arg UpdateVolumeSizeParams) (Volume, error) {
	row := q.db.QueryRow(ctx, updateVolumeSize, arg.ID, arg.TeamID, arg.SizeGb)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ClusterID,
		&i.ServerID,
		&i.Name,
		&i.SizeGb,
		&i.UsedBytes,
		&i.Filesystem,
		&i.MountPath,
		&i.ContainerName,
		&i.Status,
		&i.HostPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVolumeStatus = `-- name: UpdateVolumeStatus :one
UPDATE volumes
SET status = $3, updated_at = now()
WHERE id = $1 AND team_id = $2
RETURNING id, team_id, cluster_id, server_id, name, size_gb, used_bytes, filesystem, mount_path, container_name, status, host_path, created_at, updated_at
`

type UpdateVolumeStatusParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateVolumeStatus(ctx context.Context, arg UpdateVolumeStatusParams) (Volume, error) {
	row := q.db.QueryRow(ctx, updateVolumeStatus, arg.ID, arg.TeamID, arg.Status)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ClusterID,
		&i.ServerID,
		&i.Name,
		&i.SizeGb,
		&i.UsedBytes,
		&i.Filesystem,
		&i.MountPath,
		&i.ContainerName,
		&i.Status,
		&i.HostPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVolumeStatusAnyTeam = `-- name: UpdateVolumeStatusAnyTeam :exec
UPDATE volumes
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateVolumeStatusAnyTeamParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateVolumeStatusAnyTeam(ctx context.Context, arg UpdateVolumeStatusAnyTeamParams) error {
	_, err := q.db.Exec(ctx, updateVolumeStatusAnyTeam, arg.ID, arg.Status)
	return err
}

const updateVolumeUsage = `-- name: UpdateVolumeUsage :exec
UPDATE volumes
SET used_bytes = $2, updated_at = now()
WHERE id = $1
`

type UpdateVolumeUsageParams struct {
	ID        uuid.UUID `json:"id"`
	UsedBytes int64     `json:"used_bytes"`
}

func (q *Queries) UpdateVolumeUsage(ctx context.Context, arg UpdateVolumeUsageParams) error {
	_, err := q.db.Exec(ctx, updateVolumeUsage, arg.ID, arg.UsedBytes)
	return err
}
