// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wireguard_peers.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countFailedPeersByCluster = `-- name: CountFailedPeersByCluster :one
SELECT count(*) FROM wireguard_peers wp
JOIN cluster_members cm ON wp.member_id = cm.id
WHERE cm.cluster_id = $1 AND wp.status = 'failed'
`

func (q *Queries) CountFailedPeersByCluster(ctx context.Context, clusterID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFailedPeersByCluster, clusterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTotalPeersByCluster = `-- name: CountTotalPeersByCluster :one
SELECT count(*) FROM wireguard_peers wp
JOIN cluster_members cm ON wp.member_id = cm.id
WHERE cm.cluster_id = $1
`

func (q *Queries) CountTotalPeersByCluster(ctx context.Context, clusterID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTotalPeersByCluster, clusterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWireGuardPeer = `-- name: CreateWireGuardPeer :one
INSERT INTO wireguard_peers (member_id, peer_member_id, status)
VALUES ($1, $2, 'pending') RETURNING id, member_id, peer_member_id, status, last_handshake_at, last_check_at, rtt_ms, created_at
`

type CreateWireGuardPeerParams struct {
	MemberID     uuid.UUID `json:"member_id"`
	PeerMemberID uuid.UUID `json:"peer_member_id"`
}

func (q *Queries) CreateWireGuardPeer(ctx context.Context, arg CreateWireGuardPeerParams) (WireguardPeer, error) {
	row := q.db.QueryRow(ctx, createWireGuardPeer, arg.MemberID, arg.PeerMemberID)
	var i WireguardPeer
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.PeerMemberID,
		&i.Status,
		&i.LastHandshakeAt,
		&i.LastCheckAt,
		&i.RttMs,
		&i.CreatedAt,
	)
	return i, err
}

const deletePeersByMember = `-- name: DeletePeersByMember :exec
DELETE FROM wireguard_peers WHERE member_id = $1 OR peer_member_id = $1
`

func (q *Queries) DeletePeersByMember(ctx context.Context, memberID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePeersByMember, memberID)
	return err
}

const getPeerStatus = `-- name: GetPeerStatus :one
SELECT status FROM wireguard_peers WHERE member_id = $1 AND peer_member_id = $2
`

type GetPeerStatusParams struct {
	MemberID     uuid.UUID `json:"member_id"`
	PeerMemberID uuid.UUID `json:"peer_member_id"`
}

func (q *Queries) GetPeerStatus(ctx context.Context, arg GetPeerStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, getPeerStatus, arg.MemberID, arg.PeerMemberID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const listPeersByCluster = `-- name: ListPeersByCluster :many
SELECT wp.id, wp.member_id, wp.peer_member_id, wp.status, wp.last_handshake_at, wp.last_check_at, wp.rtt_ms, wp.created_at,
       cm_from.wireguard_ip AS from_ip, s_from.name AS from_server_name,
       cm_to.wireguard_ip AS to_ip, s_to.name AS to_server_name
FROM wireguard_peers wp
JOIN cluster_members cm_from ON wp.member_id = cm_from.id
JOIN cluster_members cm_to ON wp.peer_member_id = cm_to.id
JOIN servers s_from ON cm_from.server_id = s_from.id
JOIN servers s_to ON cm_to.server_id = s_to.id
WHERE cm_from.cluster_id = $1
`

type ListPeersByClusterRow struct {
	ID              uuid.UUID          `json:"id"`
	MemberID        uuid.UUID          `json:"member_id"`
	PeerMemberID    uuid.UUID          `json:"peer_member_id"`
	Status          string             `json:"status"`
	LastHandshakeAt pgtype.Timestamptz `json:"last_handshake_at"`
	LastCheckAt     pgtype.Timestamptz `json:"last_check_at"`
	RttMs           *int32             `json:"rtt_ms"`
	CreatedAt       time.Time          `json:"created_at"`
	FromIp          netip.Addr         `json:"from_ip"`
	FromServerName  string             `json:"from_server_name"`
	ToIp            netip.Addr         `json:"to_ip"`
	ToServerName    string             `json:"to_server_name"`
}

func (q *Queries) ListPeersByCluster(ctx context.Context, clusterID uuid.UUID) ([]ListPeersByClusterRow, error) {
	rows, err := q.db.Query(ctx, listPeersByCluster, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPeersByClusterRow{}
	for rows.Next() {
		var i ListPeersByClusterRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.PeerMemberID,
			&i.Status,
			&i.LastHandshakeAt,
			&i.LastCheckAt,
			&i.RttMs,
			&i.CreatedAt,
			&i.FromIp,
			&i.FromServerName,
			&i.ToIp,
			&i.ToServerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeersByMember = `-- name: ListPeersByMember :many
SELECT wp.id, wp.member_id, wp.peer_member_id, wp.status, wp.last_handshake_at, wp.last_check_at, wp.rtt_ms, wp.created_at, cm.wireguard_ip AS peer_ip, s.name AS peer_server_name
FROM wireguard_peers wp
JOIN cluster_members cm ON wp.peer_member_id = cm.id
JOIN servers s ON cm.server_id = s.id
WHERE wp.member_id = $1
`

type ListPeersByMemberRow struct {
	ID              uuid.UUID          `json:"id"`
	MemberID        uuid.UUID          `json:"member_id"`
	PeerMemberID    uuid.UUID          `json:"peer_member_id"`
	Status          string             `json:"status"`
	LastHandshakeAt pgtype.Timestamptz `json:"last_handshake_at"`
	LastCheckAt     pgtype.Timestamptz `json:"last_check_at"`
	RttMs           *int32             `json:"rtt_ms"`
	CreatedAt       time.Time          `json:"created_at"`
	PeerIp          netip.Addr         `json:"peer_ip"`
	PeerServerName  string             `json:"peer_server_name"`
}

func (q *Queries) ListPeersByMember(ctx context.Context, memberID uuid.UUID) ([]ListPeersByMemberRow, error) {
	rows, err := q.db.Query(ctx, listPeersByMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPeersByMemberRow{}
	for rows.Next() {
		var i ListPeersByMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.PeerMemberID,
			&i.Status,
			&i.LastHandshakeAt,
			&i.LastCheckAt,
			&i.RttMs,
			&i.CreatedAt,
			&i.PeerIp,
			&i.PeerServerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePeerHealth = `-- name: UpdatePeerHealth :exec
UPDATE wireguard_peers SET
    status = $3,
    last_handshake_at = $4,
    last_check_at = now(),
    rtt_ms = $5
WHERE member_id = $1 AND peer_member_id = $2
`

type UpdatePeerHealthParams struct {
	MemberID        uuid.UUID          `json:"member_id"`
	PeerMemberID    uuid.UUID          `json:"peer_member_id"`
	Status          string             `json:"status"`
	LastHandshakeAt pgtype.Timestamptz `json:"last_handshake_at"`
	RttMs           *int32             `json:"rtt_ms"`
}

func (q *Queries) UpdatePeerHealth(ctx context.Context, arg UpdatePeerHealthParams) error {
	_, err := q.db.Exec(ctx, updatePeerHealth,
		arg.MemberID,
		arg.PeerMemberID,
		arg.Status,
		arg.LastHandshakeAt,
		arg.RttMs,
	)
	return err
}

const upsertWireGuardPeer = `-- name: UpsertWireGuardPeer :exec
INSERT INTO wireguard_peers (member_id, peer_member_id, status)
VALUES ($1, $2, $3)
ON CONFLICT (member_id, peer_member_id) DO UPDATE SET
    status = EXCLUDED.status,
    last_check_at = now()
`

type UpsertWireGuardPeerParams struct {
	MemberID     uuid.UUID `json:"member_id"`
	PeerMemberID uuid.UUID `json:"peer_member_id"`
	Status       string    `json:"status"`
}

func (q *Queries) UpsertWireGuardPeer(ctx context.Context, arg UpsertWireGuardPeerParams) error {
	_, err := q.db.Exec(ctx, upsertWireGuardPeer, arg.MemberID, arg.PeerMemberID, arg.Status)
	return err
}
